### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/msix-docs#100]
Is there an example walk-through tutorial of how to package an application, like how MSI can be made with WiX? I don't see anything like that here.

In this documentation I do not see any example projects, example files, example folder structures, or really anything of a final product. Everything is spread across many many pages with no connecting thread. This documentation is not usable to me to make a very simple project and deploy it as an IT professional.

For example, I would like to:
1) Put a file on the disk
2) Put a link to that file on the Start Menu
3) Send the package to a user and have them install it

I do not see any quick, logical way of accomplishing my goals with the information currently provided, or way to see what a finished product looks like. Nor do I see a compelling argument to developers for moving to this format from existing solutions, which are trivial to use.

WiX has a great example of a tutorial here. It defines the problem, explains how they solve the problem, and then delivers a concise solution built with their framework.
`https://www.firegiant.com/wix/tutorial/`

Thank you, hope my feedback helps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896bae75-1efb-9fae-bb47-60acb4d51b77
* Version Independent ID: c77ef381-91fc-c97b-c138-e4a4f74728a8
* Content: [Manual app packaging - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/manual-packaging-root)
* Content Source: [msix-src/package/manual-packaging-root.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/manual-packaging-root.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
HI @SwiftOnSecurity , thank you for the feedback. 
In general, here are the steps to manually create an MSIX: 
1. Create a package manifest and add Target-based unplated assets (optional)
2. Create an MSIX package or bundle with the MakeAppx.exe tool	
3. Create a certificate for package signing	
4. Sign an app package using SignTool	

We did recently restructure our docs so that they are scenario base. If the material presented in the docs is insufficient we will take that as feedback and work to provide better examples.

**Comment by sharlaakers** [comment]
Hi @SwiftOnSecurity, 

We have now updates our documentation to better follow along with the workflow that one might go through when creating an MSIX. You can start at the Overview page [here ](https://docs.microsoft.com/windows/msix/packaging-tool/create-an-msix-overview)on how to create an MSIX with an existing installer. If you are interested in examples, we have a series of [lab exercises](https://github.com/Microsoft/msix-labs) that you can go through, showing off different features of MSIX. If you feel we are still missing information, please let us know as we are always working to improve our documentation. 

Best,
Sharla
