### ISSUE TITLE
Creating .MSIX package from Visual Studio on Windows 8.1

### ISSUE THREAD

**Issue by RoyceLithgo** [MicrosoftDocs/msix-docs#101]
I cannot find anywhere on the internet information on how one actually creates a .MSIX package in a Windows 8.1 development environment (WPF .NET Core on VS 2019). Seeing as MSIX Core is for deployment in such an environment, don't you think it's conceivable that the dev may also be done in Windows 8.1? Every tutorial out there assumes Windows 10 as the dev environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37eced72-23b9-9555-6388-38b996277863
* Version Independent ID: 2d144a55-69a9-b4fe-8891-78a2f72b20d8
* Content: [MSIX Core - MSIX](https://docs.microsoft.com/en-us/windows/msix/msix-core/msixcore)
* Content Source: [msix-src/msix-core/msixcore.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/msix-core/msixcore.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by Huios** [comment]
Hi @RoyceLithgo 

If you're using VS 2019 you can package your app as an MSIX on Windows 8.1. You'll need to make sure you have the UWP workload installed, it's required for MSIX packaging and you can get it by running the VS installer.
The only caveat is that you won't be able to debug the app (F5) for testing as the required APIs to debug the MSIX package are not available on Windows 8.1. 

Tanaka (MSFT)
