### ISSUE TITLE
App package publish Create App Package wizard - 'installer location' help text need

### ISSUE THREAD

**Issue by OzBob** [MicrosoftDocs/msix-docs#102]
https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps#create-your-app-package-upload-file-using-visual-studio

The output location is hardcoded in the .html file produced.

When uploading the package files to a website, the URL is incorrect, I suggest that it should be a relative URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9757ffa-ccdb-e9f3-3f74-6f147dd04066
* Version Independent ID: 15b5e687-f04d-d893-81fe-8fc86b63fe2d
* Content: [Packaging MSIX apps - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps#create-your-app-package-upload-file-using-visual-studio)
* Content Source: [msix-src/package/packaging-uwp-apps.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/packaging-uwp-apps.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by OzBob** [comment]
The 'Installer Location' in the Packaging project wizard needs a link to documentation to explain that:

The intended destination and web/file/unc location of the package, .appinstaller and other files must match the 'Installer Location' or the links in the index.html file will be wrong and a "file missing" error will appear when clicking on the the 'get the app' button on the index.html file.

**Comment by Huios** [comment]
Thanks for the feedback @OzBob . We're forwarding it to the Visual Studio Team to help add the link/guidance for the 'Installer Location'.

Tanaka (MSFT)
