### ISSUE TITLE
Setting 'Ensure that the 'generate conversion template file for each package' no longer there ?

### ISSUE THREAD

**Issue by kadorken** [MicrosoftDocs/msix-docs#103]
The step indicating 'Ensure that the 'generate conversion template file for each package' does not appear in the settings of the MSIX Packaging Tool Version 1.2019.1220.0 that I just obtained from the app store.
However there is an option called 'Generate a command line file with each package' which I am assuming is the equivalent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13a26776-a63c-41d1-2cda-5d00035dff19
* Version Independent ID: 8cf73641-4132-f505-8b94-c333edc8597d
* Content: [How to generate a template file for command line conversions - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/generate-template-file)
* Content Source: [msix-src/packaging-tool/generate-template-file.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/generate-template-file.md)
* Product: **msix**
* GitHub Login: @sharlaakers
* Microsoft Alias: **shakers**

**Comment by sharlaakers** [comment]
fixed
