### ISSUE TITLE
Missing \

### ISSUE THREAD

**Issue by bergerpascal** [MicrosoftDocs/msix-docs#11]
The Path in the topic Considerations is missing a \ between users and %username%. It should be  C:\Users\%username%\Desktop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9950111d-3095-3377-aed7-80a7469a34c3
* Version Independent ID: 3d559665-a358-09be-37a8-d38fa45da8af
* Content: [Duplicate MSIX Packaging Tool Settings across multiple devices - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/duplicate-mpt-settings-across-devices)
* Content Source: [msix-src/packaging-tool/duplicate-mpt-settings-across-devices.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/duplicate-mpt-settings-across-devices.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
This was fixed and closed.
