### ISSUE TITLE
Powershell script even with the proper input does nothing.

### ISSUE THREAD

**Issue by dreeves14** [MicrosoftDocs/msix-docs#111]
Poor explanation of how to get the Token

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93165f41-8dfc-0316-f37a-1df2e8a8fd8c
* Version Independent ID: b15947b8-83fe-7bd8-1d76-ebd040c28258
* Content: [Sign an MSIX package with Device Guard signing - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/signing-package-device-guard-signing#feedback)
* Content Source: [msix-src/package/signing-package-device-guard-signing.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/signing-package-device-guard-signing.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Hi @dreeves14 we are working to improve our docs walk through. We'll be making changes shortly.
