### ISSUE TITLE
Get an Azure AD access token

### ISSUE THREAD

**Issue by dreeves14** [MicrosoftDocs/msix-docs#112]
These directions are awful and once you get to the powershell script sample and make it your own it doesn't do anything. All the other resources lead you down a coding rabbit hole.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93165f41-8dfc-0316-f37a-1df2e8a8fd8c
* Version Independent ID: b15947b8-83fe-7bd8-1d76-ebd040c28258
* Content: [Sign an MSIX package with Device Guard signing - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/signing-package-device-guard-signing#feedback)
* Content Source: [msix-src/package/signing-package-device-guard-signing.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/signing-package-device-guard-signing.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Hi @dreeves14 , thanks for the feedback. We are contently updating our docs. We understand that creating the script to obtain the Azure AD access token can be painful. Where you about to successfully create and register your app in the Azure portal?

**Comment by dreeves14** [comment]
Possibly… it’s a desktop app that I’m trying to package as an MSIX from an EXE to then distribute via Intune.

For whatever reason when I launch the finished MSIX package it says my CN which pulls in via the Device Guard cert and if I use my Microsoft account for which I am the global admin of the MSFT for Business store I had the right permissions. I do see entries today of items going through but when I launch the app to test it says it’s not verified publisher and won’t install.

-DR
    
    
    
    Dalton Reeves    
    Senior Systems Administrator + Technology    
    P (314) 655-5523 | F (314) 309-3103    
    dreeves@anderscpa.com | anderscpa.com    
    800 Market Street, Suite 500 | St. Louis, MO 63101   

    ANDERS CPAs + ADVISORS

**Comment by dianmsft** [comment]
You would need to download and install your organization's root certificate for Device Guard. Do the following: 
1. Sign in to the Microsoft Store for Business.
2. Select Manage and then select Settings.
3. View Devices.
4. View Download your organization's root certificate for use with Device Guard
5. Click Download

**Comment by dianmsft** [comment]
Let us know if the instructions help. Feel free to reopen the issue or create a new one.

**Comment by dreeves14** [comment]
I’m sorry was there supposed to be a link there? Im not seeing any directions.

-DR
    
    
    
    Dalton Reeves    
    Senior Systems Administrator + Technology    
    P (314) 655-5523 | F (314) 309-3103    
    dreeves@anderscpa.com | anderscpa.com    
    800 Market Street, Suite 500 | St. Louis, MO 63101   

    ANDERS CPAs + ADVISORS
