### ISSUE TITLE
How could I pack a self-contained .net core app into an appxbundle file.

### ISSUE THREAD

**Issue by Summpot** [MicrosoftDocs/msix-docs#114]
I tried many methods, including using Directory.Build.targets and Directory.Build.props or directly modifying .wapproj, but I didn't succeed in the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bead27ac-8ed3-9886-26e2-47f49ea1efc0
* Version Independent ID: f354c6b6-b2e0-e070-dd0d-c3452a5635fb
* Content: [Package a desktop app from source code using Visual Studio - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net)
* Content Source: [msix-src/desktop/desktop-to-uwp-packaging-dot-net.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-packaging-dot-net.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by sbanni** [comment]
The .wapproj creates a self-contained .netcore application by default when you generate the bundle.  If you would like to always create the self-contained you would have to modify the .netcore project itself to have the self-contained property.

**Comment by Summpot** [comment]
Thanks!
