### ISSUE TITLE
Writing Unit Tests for packaged desktop apps

### ISSUE THREAD

**Issue by LokiMidgard** [MicrosoftDocs/msix-docs#116]
I have a packaged a desktop app to access some new features.

In order to test this app, this tests need to run in an app container (I think it's calld this). As far as I know there is currently only one project type that support this. Uwp test projects. But A UWP test project can't reference a .Netcore 3.1 App.

The documentation says to test your project (and I agree) but we can't only relay on manual tests for this. So how do I write unit test for this kind of projects?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12379f43-c827-669f-6aeb-4b4d8650cfdf
* Version Independent ID: fadedb99-8dfe-7371-105a-2944bc8d9766
* Content: [Prepare to package a desktop application (MSIX) - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-prepare)
* Content Source: [msix-src/desktop/desktop-to-uwp-prepare.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-prepare.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by samiranshah** [comment]
Hi @LokiMidgard, this issue is more relevant to the Microsoft Project Reunion, creating an issue/feature proposal here (https://github.com/microsoft/ProjectReunion) would be the right next step.
Thanks!
