### ISSUE TITLE
still has links to .appx not .msix in the example

### ISSUE THREAD

**Issue by aclinick** [MicrosoftDocs/msix-docs#119]
ms-appinstaller:?source=http://mywebservice.azureedge.net/HubApp.appx should be ms-appinstaller:?source=http://mywebservice.azureedge.net/HubApp.msix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0414d22b-2b74-000f-9d7b-47f6dcb0e45e
* Version Independent ID: 0e72ec33-b8ad-af27-bcb9-16a45936e2a1
* Content: [Installing Windows 10 apps from a web page - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/installing-windows10-apps-web#feedback)
* Content Source: [msix-src/app-installer/installing-windows10-apps-web.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/installing-windows10-apps-web.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by sharlaakers** [comment]
Fixed.
