### ISSUE TITLE
Group policies affecting update

### ISSUE THREAD

**Issue by julienshepherd** [MicrosoftDocs/msix-docs#12]
Is there any group policy that will prevent the Appx Deployment Server service to check the appinstaller web location for updates? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e69e20f-7cfc-aa28-85b8-f2deb8a69873
* Version Independent ID: c3fffd4b-4405-c347-2db8-95c5c0928de5
* Content: [App Installer file update settings - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/update-settings)
* Content Source: [msix-src/app-installer/update-settings.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/update-settings.md)
* Product: **msix**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by c-don** [comment]
@julienshepherd - No. Group policy isnt aware of AppInstaller files.
