### ISSUE TITLE
Link to related docs

### ISSUE THREAD

**Issue by ChainReactive** [MicrosoftDocs/msix-docs#120]
This doc is a nice overview.  Standing alone, however, it doesn't dive deep enough for getting the job done.  Additional details are needed and available elsewhere.  It's just a matter of linking to those related docs.

As I read through this doc, here's a running list of related docs for linking:

  * *Check .NET Native compatibility* section should link to [.NET Native](https://docs.microsoft.com/en-us/dotnet/framework/net-native/).
  * *Configure a package with the manifest designer* section should link to [App icons and logos](https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9757ffa-ccdb-e9f3-3f74-6f147dd04066
* Version Independent ID: 15b5e687-f04d-d893-81fe-8fc86b63fe2d
* Content: [Packaging MSIX apps - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps#configure-a-package-with-the-manifest-designer)
* Content Source: [msix-src/package/packaging-uwp-apps.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/packaging-uwp-apps.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
I believe this has been fixed. let us know if there is still an issue
