### ISSUE TITLE
Sideloaded app with auto update

### ISSUE THREAD

**Issue by pw3107** [MicrosoftDocs/msix-docs#122]
What path needs to be used when creating app packages for the auto update feature to work when deploying from Azure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bb47a2e-6082-1edf-a69f-e5802743f721
* Version Independent ID: d65ce9f2-0f4f-181f-915a-018001d810b9
* Content: [Distribute a Windows 10 app from an Azure web app - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/web-install-azure)
* Content Source: [msix-src/app-installer/web-install-azure.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/web-install-azure.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by Huios** [comment]
Hi @pw3107,

Are using the AppInstaller file?  If so, your main package URI needs to point to the location of your package on Azure.

Have a look at - https://docs.microsoft.com/en-us/windows/msix/app-installer/app-installer-file-overview#hosting-the-app-installer-file-for-downloads-and-updates
