### ISSUE TITLE
MSIX Update non-Store apps start after install

### ISSUE THREAD

**Issue by chris579** [MicrosoftDocs/msix-docs#123]
The docs nicely describe how to update an app. However, when a user decides to perform an update he expects that the app starts again afterwards. How can this be achieved? When using `DeploymentOptions.ForceApplicationShutdown` (which is needed in this case) the app just shuts down.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61dbc475-482a-3e2f-b41e-bb9d35d100e5
* Version Independent ID: 93e1b53d-8150-5693-ca85-acb317f1f666
* Content: [Update non-Store published apps from your code - MSIX](https://docs.microsoft.com/en-us/windows/msix/non-store-developer-updates)
* Content Source: [msix-src/non-store-developer-updates.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/non-store-developer-updates.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **diahar**

**Comment by looterz** [comment]
A way to automatically update & restart would be greatly appreciated, so that the user does not have to manually restart the application.

**Comment by Huios** [comment]
@looterz and @chris579,

Passing in AddPackageOptions.ForceTargetAppShutdown should restart the app is its UWP, for non-UWP apps you can call [RegisterApplicationRestart](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#updates) first. 
We're updating the doc to make this clear.

**Comment by looterz** [comment]
> 
> 
> @looterz and @chris579,
> 
> Passing in AddPackageOptions.ForceTargetAppShutdown should restart the app is its UWP, for non-UWP apps you can call [RegisterApplicationRestart](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#updates) first.
> We're updating the doc to make this clear.

Awesome, thanks for the clarification.
