### ISSUE TITLE
What to do if create app package says "Incorrect Program Format"

### ISSUE THREAD

**Issue by absinghal** [MicrosoftDocs/msix-docs#126]
Pl provide steps on what should be done if following error is encountered on "Create an app package"

Severity	Code	Description	Project	File	Line	Suppression State
Error		PRI175: 0x8007000b - Processing Resources failed with error: An attempt was made to load a program with an incorrect format.	AppSystem.Wap	GENERATEPROJECTPRIFILE	1	

Executing the project is running file. The above error comes up only on "Create an app package". Have tried with AnyCPU and x86/x64 platforms.

**Comment by dianmsft** [comment]
Hi, error code means that the format of DLL or executable being loaded is invalid. Are you seeing this error through Visual Studio?

**Comment by absinghal** [comment]
Yes. Have both x64 and x86 dlls in the application folder. Package format is neutral because we load relevant dll depending on platform using assembly resolve.

**Comment by Huios** [comment]
@absinghal,

That error usually implies that the packaging process encountered corrupted PRI (resource) files. Regenerating your assets and any resources may help. If that doesn't work, please file a Feedback Hub item reproducing the error, for our devs to investigate. Please file it under the category Developer Platform > Desktop Bridge.

**Comment by absinghal** [comment]
In order for the issue to be complete for future reference, it is same as described here:

https://developercommunity.visualstudio.com/content/problem/1135173/cant-create-app-packages-for-a-windows-application-1.html

Still waiting for the fix as mentioned in the post.
