### ISSUE TITLE
Provide instructions or link for instructions to obtaining Client ID and Key. 

### ISSUE THREAD

**Issue by enqui** [MicrosoftDocs/msix-docs#128]
Provide instructions or link for instructions to obtaining Client ID and Key. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9757ffa-ccdb-e9f3-3f74-6f147dd04066
* Version Independent ID: 15b5e687-f04d-d893-81fe-8fc86b63fe2d
* Content: [Packaging MSIX apps - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps)
* Content Source: [msix-src/package/packaging-uwp-apps.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/packaging-uwp-apps.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Hi @enqui we have instructions to obtain Client ID and Key here: https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps#automate-store-submissions 

Instructions are as follows: 
Go to the [Partner Center dashboard](https://partner.microsoft.com/dashboard) and sign in with your Azure AD credentials.

On the Partner Center dashboard, select the gear icon (near the upper right corner of the dashboard) and then select Developer settings.

In the Settings menu in the left pane, click Users.

Click the name of your Azure AD application to go to the application's settings. On this page, copy the Tenant ID and Client ID values.

In the Keys section, click Add new key. On the next screen, copy the Key value, which corresponds to the client secret. You will not be able to access this info again after you leave this page, so make sure to not lose it. For more information, see [Manage keys for an Azure AD application.](https://docs.microsoft.com/windows/uwp/publish/add-users-groups-and-azure-ad-applications#manage-keys-for-an-azure-ad-application)

let us know if this is not enough and additional information is needed
