### ISSUE TITLE
"For more information, see this article" redirects back to this article

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/msix-docs#129]
The "this article" link at the end of the article redirects back to the article that contains the link:

> Support for file system plug-ins and customizations while the executable of the main application is in a VFS is planned for the next major release of Windows. You can preview this support starting in Windows 10 Insider Preview Build 18312 or later. For more information, see [this article](https://docs.microsoft.com/en-us/windows/msix/modification-package-1903).

I suspect the entire paragraph should be removed, because the article already contains the "Modification packages on Windows 10, version 1903, and later" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ef494e-4c2f-e7dd-d8c6-915e0aadab18
* Version Independent ID: fd2a9514-09d3-ab99-291e-96fcf97ee357
* Content: [Customize your Enterprise apps with modification packages - MSIX](https://docs.microsoft.com/en-us/windows/msix/modification-packages#modification-packages-on-windows-10-version-1903-and-later)
* Content Source: [msix-src/modification-packages.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/modification-packages.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
This has been fixed

**Comment by KalleOlaviNiemitalo** [comment]
> This has been fixed

Apparently in <https://github.com/MicrosoftDocs/msix-docs/commit/cd323db697c7bbec66aa528ed18c0c6a70a8f7dc>.
