### ISSUE TITLE
Creating MSIX without having an installer

### ISSUE THREAD

**Issue by ssrakesh** [MicrosoftDocs/msix-docs#13]
all the instructions assumes to have an existing installer pass to MsixPackagingTool. 
Is there a way to create MSIX with just raw application files/contents?

**Comment by c-don** [comment]
@ssrakesh - There are a few ways you can get create MSIX package. 
1. Use MSIX Packaging Tool 
    - Providing an insaller is optional in the UI. Keep it blank and in the monitoring phase, perform the actions with your raw application. The tool should pick up all the artifacts and package them into a MSIX package. 
2. Use [Visual Studio Packaging Project](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-packaging-dot-net?context=/windows/msix/render)
3. Use makeappx.exe(tool in the Windows 10 SDK) to create the package
    - You will need to construct a manifest file to use makeappx

If you can share more information regarding your scenario, we can provide a recommendation on which option is the best one for you.
