### ISSUE TITLE
'Version Package Manifest' giving error with this sample code

### ISSUE THREAD

**Issue by chendrixson** [MicrosoftDocs/msix-docs#130]
Below is what I was getting from my build pipeline.  Seems like  I fixed this by putting it all on the same line, and maybe removing the semicolon at the end.  Here's what I ended up with that worked.

- powershell: |
   [Reflection.Assembly]::LoadWithPartialName("System.Xml.Linq")
   $path = "PlanomaticPackage/Package.appxmanifest"
   $doc = [System.Xml.Linq.XDocument]::Load($path)
   $xName = [System.Xml.Linq.XName]"{http://schemas.microsoft.com/appx/manifest/foundation/windows10}Identity"
   $doc.Root.Element($xName).Attribute("Version").Value = "$(major).$(minor).$(build).$(revision)"
   $doc.Save($path)
  displayName: 'Version Package Manifest'

and the error:
Cannot convert argument "name", with value: "System.Xml.Linq.XName", for "Element" to type "System.Xml.Linq.XName": 
"Cannot convert the "System.Xml.Linq.XName" value of type "System.RuntimeType" to type "System.Xml.Linq.XName"."
At D:\a\_temp\a49d836d-2d06-4c14-ad96-e3cf22881399.ps1:8 char:1
+ $doc.Root.Element($xName).Attribute("Version").Value =
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e7e624-229c-a7f4-caf7-c09767d5f942
* Version Independent ID: 8a980367-fc9c-b208-0246-a436cecf4688
* Content: [Set up a CI/CD pipeline to automate your MSIX builds and deployments - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/azure-dev-ops#feedback)
* Content Source: [msix-src/desktop/azure-dev-ops.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/azure-dev-ops.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by johannescolmsee** [comment]
To fix it use that code instead (call static "factory method" Get)
   $xName =
     [System.Xml.Linq.XName]::Get(
       "{http://schemas.microsoft.com/appx/manifest/foundation/windows10}Identity");
