### ISSUE TITLE
Regarding PowerShell Script 

### ISSUE THREAD

**Issue by pk2311** [MicrosoftDocs/msix-docs#132]
Could you help with correct PS script please

**Comment by dianmsft** [comment]
Hi @pk2311 can you be more specific? Also feel free to post the question in our community http://aka.ms/msixcommunity

**Comment by pk2311** [comment]
Hey Dian, thanks for checking. My bad, i got this figured out. However i am facing some issues with signtool to sign MSIX using json token. I'll i the above link you had mentioned
