### ISSUE TITLE
This stopped working recently with error _CheckForGenerateAppxPackageOnBuild

### ISSUE THREAD

**Issue by cpyfferoen** [MicrosoftDocs/msix-docs#133]
I had a completely working solution - devops pipeline - had released 13 versions of my app - and now I can't get it to work with this error.

`The target "_CheckForGenerateAppxPackageOnBuild" does not exist in the project.`

I didn't have the `<GenerateAppxPackageOnBuild>true/false</>` in my *.wapproj at all. Obviously adding it gets the build to work - but I can't publish in Visual Studio, msbuild cli, or in Azure DevOps.

So now I can't deploy my app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9757ffa-ccdb-e9f3-3f74-6f147dd04066
* Version Independent ID: 15b5e687-f04d-d893-81fe-8fc86b63fe2d
* Content: [Packaging MSIX apps - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps)
* Content Source: [msix-src/package/packaging-uwp-apps.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/packaging-uwp-apps.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by Xeeynamo** [comment]
I have the same problem for multi target framework projects. The version of MSBuild used is `16.6.0-preview-20126-02+13cfe7fc5`.

**Comment by Huios** [comment]
Hi @cpyfferoen,

This issue should be fixed as of Visual Studio 16.7-preview.1

**Comment by Huios** [comment]
@Xeeynamo 
Unfortunately the Windows App Packaging Project currently doesn't support multi framework projects.
