### ISSUE TITLE
VS 2019 Signing with EV cert

### ISSUE THREAD

**Issue by pdxlongriver** [MicrosoftDocs/msix-docs#135]
When I go to step 4 "Select Signing Method" &gt; "Yes Select a Certificate" &gt; "Select from Store" &gt; "Select a Certificate" &gt;  and no certificate comes up. Buttons of ok and cancel which both do the same thing. I have a TrustId EV in the certificate store that I am trying to use although it is not found and I don't see any options to browse and select it. Also I don't see any documentation on the Select from Store option. I assume signing with an EV cert is a happy path scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9757ffa-ccdb-e9f3-3f74-6f147dd04066
* Version Independent ID: 15b5e687-f04d-d893-81fe-8fc86b63fe2d
* Content: [Packaging MSIX apps - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps)
* Content Source: [msix-src/package/packaging-uwp-apps.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/packaging-uwp-apps.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by ebptwllc** [comment]
Im using digicert EV Code sign usb dongle and advanced installer. 

my workflow is to first build with AI, then use the same contents to makeappx, then sign with Digicert Windows Utility. its a bit more work than native vs2019 but it works. 

i hope this helps

**Comment by pdxlongriver** [comment]
Thank you for the comment. It is good to know a path that works with the combination of things that we are working with. I will give it a shot. Is it possible to exchange contact info for questions?

**Comment by japarson** [comment]
@pdxlongriver Have you resolved this issue? Unfortunately, the MSIX packaging wizard does not currently support EV code signing. Also, I'm not sure it's possible to import an EV certificate to the user certificate store, which is possibly why you're not seeing it. Can you clarify how you were able to do that?
