### ISSUE TITLE
Shouldn't the revision be left alone, per Microsoft Store requirements?

### ISSUE THREAD

**Issue by jons-aura** [MicrosoftDocs/msix-docs#136]
The example shows   
```major: 1
  minor: 0
  build: 0
  revision: $[counter('rev', 0)]
```
but according to https://docs.microsoft.com/en-us/windows/uwp/publish/package-version-numbering the revision should not be touched by anything other than the Microsoft Store. I would guess the counter variable should be applied to the "build" section of the version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e7e624-229c-a7f4-caf7-c09767d5f942
* Version Independent ID: 8a980367-fc9c-b208-0246-a436cecf4688
* Content: [Set up a CI/CD pipeline to automate your MSIX builds and deployments - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/azure-dev-ops#feedback)
* Content Source: [msix-src/desktop/azure-dev-ops.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/azure-dev-ops.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by Huios** [comment]
Hi @jons-aura,

If you're distributing your app to the Microsoft Store then the revision shouldn't be updated but it's okay to update it if you're distributing it outside the Microsoft store e.g. via your Website. The value you choose to apply the counter depends on how you want to bum up the version for your CI pipeline.
