### ISSUE TITLE
Not able to sign MSIX

### ISSUE THREAD

**Issue by pk2311** [MicrosoftDocs/msix-docs#137]
Could you please help with some example when it comes to using signtool along with .json file. i keep getting this error:
PS C:\Program Files (x86)\Windows Kits\10\bin\10.0.19613.0\x64&gt; .\signtool.exe sign /fd sha256 /dlib .\dgsslib.dll /dmdf .\output.json C:\temp\VLC_3.10.0.0_x64__h91ms92gdsmmt.msix

Number of errors: 1

.\signtool.exe : SignTool Error: This file format cannot be signed because it is not recognized.
At line:1 char:1
+ .\signtool.exe sign /fd sha256 /dlib .\dgsslib.dll /dmdf .\output.jso ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (SignTool Error:...not recognized.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
SignTool Error: An error occurred while attempting to sign: C:\temp\VLC_3.10.0.0_x64__h91ms92gdsmmt.msix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93165f41-8dfc-0316-f37a-1df2e8a8fd8c
* Version Independent ID: b15947b8-83fe-7bd8-1d76-ebd040c28258
* Content: [Sign an MSIX package with Device Guard signing - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/signing-package-device-guard-signing#feedback)
* Content Source: [msix-src/package/signing-package-device-guard-signing.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/signing-package-device-guard-signing.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by pk2311** [comment]
This is due to issues with SDK sign tool. Was able to figure this out

**Comment by coop3406** [comment]
what is the proper version ?

**Comment by pk2311** [comment]
Please use the win10 insider preview version

**Comment by coop3406** [comment]
I have installed signtool from insider kit 20140

signtool file version = 10.0.20140.1001 / 31 May 2020

and I get the same error message


c:\Program Files (x86)\Windows Kits\10\bin\10.0.20140.0\x64>.\signtool.exe sign /debug /fd sha256 /dlib DgssLib.dll /dmdf c:\temp\MSIX\Lightaria-MSIX.json c:\temp\MSIX\notepad-plus-plus_1.0.3.0_x64_Lightaria.msix
SignTool Error: This file format cannot be signed because it is not recognized.
SignTool Error: An error occurred while attempting to sign: c:\temp\MSIX\notepad-plus-plus_1.0.3.0_x64_Lightaria.msix

Number of files successfully Signed: 0
Number of warnings: 0
Number of errors: 1

**Comment by pk2311** [comment]
Try downloading the SDK package again as below and see if you are able to sign successfully 
<img width="597" alt="S1" src="https://user-images.githubusercontent.com/37248711/85156837-43b55b80-b278-11ea-9212-19f2c37b6f95.png">
<img width="312" alt="S2" src="https://user-images.githubusercontent.com/37248711/85156855-4a43d300-b278-11ea-8808-652c625161d8.png">

**Comment by coop3406** [comment]
Still having issues

OS Build            20150.1000
SDK Build          10.0.20145.0
Signtool            10.0.20145.1001
MSIX                  1.2020.603.0

SDK Config
![image](https://user-images.githubusercontent.com/33760923/85291521-6ea5d800-b44f-11ea-9b79-51338b35e783.png)


Error Message

c:\Program Files (x86)\Windows Kits\10\bin\10.0.20145.0\x64>.\signtool.exe sign /debug /fd sha256 /dlib DgssLib.dll /dmdf c:\temp\Lightaria-MSIX.json c:\temp\notepad-pp_1.0.0.0_x64.msix
SignTool Error: An unexpected internal error has occurred.
Error information: "Error: SignerSign() failed."  (-2145844847/0x80190191)

**Comment by coop3406** [comment]
And Second Virtual Machine 

Virtual Machine 2
(Hyper-V quick MSIX VM)

OS Build 18363.753
SDK Build 10.0.20145.0
Signtool 10.0.20145.1001
MSIX 1.2020.402.0

SDK Config

![image](https://user-images.githubusercontent.com/33760923/85293539-5aafa580-b452-11ea-8e92-161b06258cd6.png)


Error Message

c:\Program Files (x86)\Windows Kits\10\bin\10.0.20145.0\x64>.\signtool.exe sign /debug /fd sha256 /dlib DgssLib.dll /dmdf c:\temp\Lightaria-MSIX.json c:\temp\notepad-pp_1.0.0.0_x64.msix
SignTool Error: An unexpected internal error has occurred.
Error information: "Error: SignerSign() failed." (-2145844847/0x80190191)

**Comment by pk2311** [comment]
You could create a regular hyper-v VM instead of quick create and try installing all the SDK options (i.e. ensure all the check boxes are selected)
