### ISSUE TITLE
Non-Windows 10 platforms

### ISSUE THREAD

**Issue by cglong** [MicrosoftDocs/msix-docs#138]
According to [the main MSIX page](https://docs.microsoft.com/en-us/windows/msix/overview#highlights), MSIX is also supported on non-Windows 10 platforms. If you go to the [MSIX GitHub repo](https://github.com/Microsoft/msix-packaging), you see mentions of Windows 7, iOS and Android, confirming this. Just wondering if this page should be updated to include those other platforms as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95b83f04-01b6-c494-1e2a-dcddecaa7dc8
* Version Independent ID: 758db7a1-fd48-56fc-1e82-0fbd7ad3f7dc
* Content: [Supported platforms - MSIX](https://docs.microsoft.com/en-us/windows/msix/supported-platforms#feedback)
* Content Source: [msix-src/supported-platforms.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/supported-platforms.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Hi @cglong I updated the supported platform page to include this.
