### ISSUE TITLE
WPF

### ISSUE THREAD

**Issue by chrisevans9629** [MicrosoftDocs/msix-docs#139]
Can you access the package manager api from a wpf app packaged with msix?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61dbc475-482a-3e2f-b41e-bb9d35d100e5
* Version Independent ID: 93e1b53d-8150-5693-ca85-acb317f1f666
* Content: [Update non-Store published apps from your code - MSIX](https://docs.microsoft.com/en-us/windows/msix/non-store-developer-updates#feedback)
* Content Source: [msix-src/non-store-developer-updates.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/non-store-developer-updates.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **diahar**

**Comment by Huios** [comment]
Hi @chrisevans9629 

Yes you should be able to. Are you having any issues?

**Comment by chrisevans9629** [comment]
I believe I was able to access the api using the desktopuwp nuget package.
