### ISSUE TITLE
Doesn't seem to actually link to the github project?

### ISSUE THREAD

**Issue by contextfree** [MicrosoftDocs/msix-docs#14]
It says "MSIX SDK is an open source project on GitHub. Here you access to the full source and instructions on how to build the binaries for each platform are available here." but I don't see the actual link.

Also, the grammar of this sentence is weird: "Here you access to the full source and instructions on how to build the binaries for each platform are available here." Was the "Here you" meant to be removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9194e0c9-d66b-cd6a-6bc4-30b8f46f1e12
* Version Independent ID: 4de9b609-ecfc-9527-8173-4b1c1afaab66
* Content: [MSIX SDK - MSIX](https://docs.microsoft.com/en-us/windows/msix/msix-sdk/sdk-overview#feedback)
* Content Source: [msix-src/msix-sdk/sdk-overview.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/msix-sdk/sdk-overview.md)
* Product: **msix**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. You're right, this article should link to the SDK repo at [https://github.com/Microsoft/msix-packaging](https://github.com/Microsoft/msix-packaging). I have updated the article with this link and revised several other grammatical issues such as the one you pointed out.
