### ISSUE TITLE
Behaviour of differential update for non-store distribution

### ISSUE THREAD

**Issue by amalabeygunawardana** [MicrosoftDocs/msix-docs#142]
It appears that MSIX downloads differential (delta) only in Windows store scenarios. When served via a custom web site, it appears to be downloading the full MSIX archive. Can you clarify this behaviour in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 301a223f-e298-88d1-24ba-3c6b645fcc21
* Version Independent ID: 67ffea0e-c3bf-3a88-cf74-3c83a508d353
* Content: [Differential updates MSIX app package - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/managing-your-msix-deployment-update)
* Content Source: [msix-src/desktop/managing-your-msix-deployment-update.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/managing-your-msix-deployment-update.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by Huios** [comment]
Hi @amalabeygunawardana,

Differential updates should work for non-store updates as well. an you please clarify how you're deploying your application and what's indicating the entire file is being downloaded?

**Comment by amalabey** [comment]
Thanks for the response! Please keep this open and I will get back to you with my findings. Meanwhile, can you please explain how can you only download the delta, when the `AppxBlockMap.xml` is inside the `package.appxbundle`? Without downloading the `package.appxbundle` file and extract it, how do you access the `AppxBlockMap.xml`?

**Comment by Huios** [comment]
Hi @amalabey 

We use http range requests to access the AppxBlockMap.xml and determine the deltas between package versions. You can find more info here - https://docs.microsoft.com/en-us/windows/msix/desktop/managing-your-msix-deployment-update

Cheers,
Tanaka
