### ISSUE TITLE
Not working for WPF Core 3.1

### ISSUE THREAD

**Issue by DrGriff** [MicrosoftDocs/msix-docs#144]
I and several colleagues have tried this, but to no avail.  Try creating a brand new WPF Core (.netcore 3.1) application and then follow the instructions in this page to deploy it as a "sideloaded" application to a UNC path.  Lots of errors when trying to publish.  See this [StackOverflow](https://stackoverflow.com/questions/61826678/publish-wpf-core-using-msix-multiple-problems) post for further details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bead27ac-8ed3-9886-26e2-47f49ea1efc0
* Version Independent ID: f354c6b6-b2e0-e070-dd0d-c3452a5635fb
* Content: [Package a desktop app from source code using Visual Studio - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net)
* Content Source: [msix-src/desktop/desktop-to-uwp-packaging-dot-net.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-packaging-dot-net.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by anarvekar-msft** [comment]
@DrGriff Are you still experiencing an issue with this? For future reference, our Tech community is a better place for troubleshooting help https://techcommunity.microsoft.com/t5/msix-packaging-and-tools/bd-p/MSIX-Packaging

**Comment by anarvekar-msft** [comment]
If you are still experiencing this problem, please reopen the issue
