### ISSUE TITLE
Format - <a /> tags are not rendered correctly

### ISSUE THREAD

**Issue by KiruyaMomochi** [MicrosoftDocs/msix-docs#148]
For example,
```markdown
<a id="installer-conversion" />

#### Package an application that has an installer (.msi) file
Point to the installer file by using the ``Installer`` parameter.

```cmd
DesktopAppConverter.exe -Installer C:\Installer\MyAppSetup.msi -Destination C:\Output\MyApp -PackageName "MyApp" -Publisher "CN=MyPublisher" -Version 0.0.0.1
```
is rendered as
![image](https://user-images.githubusercontent.com/65301509/83399418-c3979500-a433-11ea-918b-589bac75cf72.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0cbfaf-6e77-2b74-6b37-72028327fde4
* Version Independent ID: a4b4ac93-3b46-84f2-bd6b-7ad1709c4003
* Content: [Package an app using the Desktop App Converter (Desktop Bridge) - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-run-desktop-app-converter)
* Content Source: [msix-src/desktop/desktop-to-uwp-run-desktop-app-converter.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-run-desktop-app-converter.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by mcleanbyron** [comment]
Thanks for submitting this feedback. We have fixed the issues and republished the article.
