### ISSUE TITLE
Article needs cleanup.

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/msix-docs#149]
This article seems misleading.  The second paragraph states:

"Only keys under HKLM\Software are part of the package; keys under HKCU or other parts of the registry are not. Writes to keys or values in the package are not allowed. Writes to keys or values not part of the package are allowed as long as the user has permission."

Clearly MSIX packages do include HKCU registry keys.  Likely, the intent was to indicate that how HKLM and HKCU keys contained in the package file are treated are different, causing the effect of the third line.  But as written, it seems to indicate that MSIX packages cannot contain HKCU keys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e4d8ed3-8929-6b26-24df-578abf277bb6
* Version Independent ID: 4827fb32-31b6-5329-1879-e66098c75c6d
* Content: [Behind the scenes of the Desktop Bridge - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes#registry)
* Content Source: [msix-src/desktop/desktop-to-uwp-behind-the-scenes.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-behind-the-scenes.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by samiranshah** [comment]
Fixed in PR https://github.com/MicrosoftDocs/msix-pr/pull/654
