### ISSUE TITLE
Requirement to be an insider is no longer true

### ISSUE THREAD

**Issue by chendrixson** [MicrosoftDocs/msix-docs#150]
I don't think this is really the case anymore:
Participation in the Windows Insider Program (if you're using an Insider build)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95dd77e9-0c0a-3d24-8e7e-d8f32ecd36b0
* Version Independent ID: 84f5e738-9f68-cfb3-68e8-abed3d5f0182
* Content: [MSIX Packaging Tool Overview - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/tool-overview)
* Content Source: [msix-src/packaging-tool/tool-overview.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/tool-overview.md)
* Product: **msix**
* GitHub Login: @sharlaakers
* Microsoft Alias: **shakers**

**Comment by sharlaakers** [comment]
This is still true. If you are using a Windows Insider build, you need to ensure that your Windows Insider settings are properly configured, as the MSIX Packaging Tool Driver is installed as a Feature on Demand, which requires alignment with your build.
