### ISSUE TITLE
Is the Device Mode section outdated?

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/msix-docs#154]
I looked but the sections I'm finding in settings don't talk about Sideload anymore. I only see two things:
1. Update & Security, For developers, has a single Developer Mode toggle, not multiple options.
2. Apps, Apps & features, Chose where to get apps has a Microsoft Store only option, but I think it's no longer on by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5029ae62-c2de-bb03-0c1f-ada1e60c697d
* Version Independent ID: a7f66acc-0b1b-bcc0-b1a4-7eae63ee041e
* Content: [Sign a Windows 10 app package - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/signing-package-overview)
* Content Source: [msix-src/package/signing-package-overview.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/signing-package-overview.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Thanks for pointing this out. Additional text has been added to the page.
