### ISSUE TITLE
Supporting applications that write inside app folder

### ISSUE THREAD

**Issue by fro0116** [MicrosoftDocs/msix-docs#157]
Hi, I was trying to migrate an in-house legacy application packaged using App-V to MSIX. When I try to run the package, it fails with an error saying access is denied. 

After some research it appears the issue is this: https://github.com/MicrosoftDocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-behind-the-scenes.md

> Writes to files/folders in the app package are not allowed.

The application is known to store settings and whatnot inside its root directory. It's not feasible to change this behavior as we have hundreds of apps that do this. All of them were working fine in App-V because App-V redirects writes inside the application folder as well.

I'm wondering if it's possible to work around this limitation somehow? Or if you have plans to add support for this use case? If not, it looks like my organization won't be able to adopt MSIX for a large portion of our app portfolio.

**Comment by dianmsft** [comment]
How are you converting your apps? Have you tried Package Support Framework? https://docs.microsoft.com/en-us/windows/msix/psf/package-support-framework-overview

**Comment by dianmsft** [comment]
Closing issue. Please let us know if this issue is still persistent
