### ISSUE TITLE
Can install since the signing certificate has expired

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/msix-docs#158]
App will not install due to being signed with an certificate which expired last year.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b86dc038-4654-aeed-09db-8e702fba499c
* Version Independent ID: 50ec40a3-0fcb-1d68-782d-d1efbaf69312
* Content: [AppInstaller File Builder tool - MSIX](https://docs.microsoft.com/en-us/windows/msix/toolkit/msix-toolkit-appinstallerfilebuilder)
* Content Source: [msix-src/toolkit/msix-toolkit-appinstallerfilebuilder.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/toolkit/msix-toolkit-appinstallerfilebuilder.md)
* Product: **msix**
* GitHub Login: @RDMacLachlan
* Microsoft Alias: **romaclac**

**Comment by jgudmundson-RETSD** [comment]
You NEED to timestamp so apps can install after the cert expires.  I use sectigo eith Device Guard.  https://sectigo.com/resource-library/time-stamping-server.   Just take the timestamp url (http://timestamp.sectigo.com) and add it when you're signing.

**Comment by mjfusa** [comment]
AppInstallerFileBuilder_1.2019.1001.0.msix installs now.  Looks like it was re-signed back in June. Closing.
