### ISSUE TITLE
Unable to "Add new key"

### ISSUE THREAD

**Issue by plettb** [MicrosoftDocs/msix-docs#159]
I'm trying to follow the instructions on this page to "[Retrieve the credentials required for submissions](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps#retrieve-the-credentials-required-for-submissions)".  However, when I get to step 5, I don't see a "Keys" section at all.  Following the link to [this page](https://docs.microsoft.com/en-us/windows/uwp/publish/add-users-groups-and-azure-ad-applications#manage-keys-for-an-azure-ad-application) doesn't help - there simply doesn't appear to be an option to "Add new key".  What am I doing wrong?  I'd like to think I'm not the only person encountering this problem, so maybe more clarification is needed?

This is what I see (note:  nothing about keys):

![KeyIssue01](https://user-images.githubusercontent.com/13162376/85977911-63dccd00-b992-11ea-97cd-3022b9c13ce9.png)

Any help would be much appreciated!
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0ca4c24-058f-a798-15a1-6cd3649e45cb
* Version Independent ID: 63dec3d2-273a-a8cc-1a40-e5af423e856b
* Content: [Packaging MSIX apps - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps)
* Content Source: [msix-src/package/packaging-uwp-apps.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/packaging-uwp-apps.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by sharlaakers** [comment]
Please reopen if this is still an issue.
