### ISSUE TITLE
Credentials are not optional

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/msix-docs#16]
&gt; You will be presented with user and password fields to provide credentials for the VM if there are any

The username field is required, not optional, on my machine. Unclear if that is dependent on the VM. I created the VM using the MSIX Packaging Environment template from Hyper-V Quick Create. It is unclear what the credentials of that VM are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45e4355-afe9-ad10-0772-032b2ff288bd
* Version Independent ID: 3d281169-5030-2859-4c83-9cfc9fc3f653
* Content: [Create an application package with MSI or App-V on a VM - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/create-app-package-msi-vm)
* Content Source: [msix-src/packaging-tool/create-app-package-MSI-VM.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/create-app-package-MSI-VM.md)
* Product: **msix**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by c-don** [comment]
The credentials that are requested are of the VM that you want to connect to and do the conversion in. You will need to enter the credentials of that VM.

**Comment by hansmbakker** [comment]
Understood, but the text makes it sound as if it is possible to have a VM without credentials?

When I created the VM (using Quick Create) I didn't know upfront that I would need to set up a local account to make it work. Using my personal Microsoft account did not work.

**Comment by dianmsft** [comment]
Updated the text to be more clear that the credentials that are requested are of the VM that you want to connect to and do the conversion in. You will need to enter the credentials of that VM.
