### ISSUE TITLE
logos difficult to read in dark mode

### ISSUE THREAD

**Issue by aclinick** [MicrosoftDocs/msix-docs#160]
Trying out dark mode and noticed that you can't really read quite a few of the logos.  I think because the pngs have transparency.  Not sure what the design guidelines are for dark mode on docs for this.  A white background would make them work for sure but might look a bit ugly in dark mode - i'm clearly not the best person to discuss colors though :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b4773f4-e24d-7644-f5ac-fea26a5f5f95
* Version Independent ID: 0de07bea-5912-9005-51d2-b5fcb8bc31dd
* Content: [MSIX partners - MSIX](https://docs.microsoft.com/en-us/windows/msix/partners)
* Content Source: [msix-src/partners.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/partners.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Updates were made with the current logos provided.
