### ISSUE TITLE
Please add some examples about signing the packages while signing them using certificate stored in certificate store 

### ISSUE THREAD

**Issue by Sri-Boddupalli** [MicrosoftDocs/msix-docs#161]
[Enter feedback here]
We are not using the .PFX file to sign packages because our security team is hesitant to provide password for more number of people which might be easy to get out of hands. So our security guy added certficate purchased from DigiCert to one of the utility server ti which packagers have access to and using following command to sign the packages. 

signtool sign /fd SHA256 /v /sm /s My /n "ABC Corporation" /t http://timestamp.digicert.com file.msix

But this is not working for us as expected. I logged a post in tech community here is the issue 
https://techcommunity.microsoft.com/t5/msix-deployment/msix-package-signing-issue-with-certificate-installed-in-a/m-p/1499926

Please include more examples with clear distinction between certs added to store and .pfx file. 
Thanks,
Sri

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76957695-dd9c-1158-f1f0-7e02e48d3903
* Version Independent ID: 44e2e900-9809-2895-3bdd-b549cc451ea1
* Content: [Sign an app package using SignTool - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/sign-app-package-using-signtool)
* Content Source: [msix-src/package/sign-app-package-using-signtool.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/sign-app-package-using-signtool.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Updating the page to add links to docs that have more examples.
