### ISSUE TITLE
Removed Trusted Publishers as it is not a valid store

### ISSUE THREAD

**Issue by jvintzel** [MicrosoftDocs/msix-docs#162]
The docs reference that you can trusted under Trusted Publishers, but only Trusted People and Trusted Root Certification Authority are supported for MSIX.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3a8483-a56e-7f3d-8c25-1d8b18943342
* Version Independent ID: 3b8e451b-95b5-3d26-c7ec-160fef01d85e
* Content: [Troubleshoot installation issues with the App Installer file - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/troubleshoot-appinstaller-issues#trusted-certificates)
* Content Source: [msix-src/app-installer/troubleshoot-appinstaller-issues.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/troubleshoot-appinstaller-issues.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by bitcrazed** [comment]
Thanks for filing John. Have submitted PR #164 for your review.
