### ISSUE TITLE
Msix Packaging Tool monitored files position

### ISSUE THREAD

**Issue by Gaoyifei1011** [MicrosoftDocs/msix-docs#163]
Msix Packaging Tool会监视当前系统运行的安装程序，在安装程序运行完成后会捕捉对当前系统修改后的所有行为。默认安装程序会把应用安装在Program Files或者Program Files(x86)目录下，在之前被废弃的Desktop App Converter中捕捉到的应用在安装在Program Files或者Program Files(x86)目录下时会自动把捕捉后的文件放在Appx包的根目录下，但在Msix Packaging Tool中会放到VFS\ProgramFilesX64或者VFS\ProgramFilesX86目录下，为什么会有这样的改变？在Advanced Installer中生成的MSIX安装包也会放到根目录下。如果这是一个BUG，希望可以在未来的Msix Packaging Tool进行微调一下。
Msix Packaging Tool monitors the package installer that is running on the current system and captures all the changes made to the current system after the installer is finished.The default installer will install the application in the Program Files or Program Files(x86) directory. Applications captured in the previously deprecated Desktop App Converter will automatically put the captured Files in the root directory of the Appx package when installed in the Program Files or Program Files(x86) directory.But in Msix Packaging Tool, it will be put in the directory of VFS\ProgramFilesX64 or VFS\ProgramFilesX86.The MSIX package installer generated in Advanced Installer also goes to the root directory.If this is a BUG, hopefully it can be tweaked in the future Msix Packaging Tool.

**Comment by dianmsft** [comment]
@Gaoyifei1011 are you still seeing this?

**Comment by dianmsft** [comment]
Closing for now, let us know if you have any issues
