### ISSUE TITLE
Signing UWP app for Windows Store got worse than year ago.

### ISSUE THREAD

**Issue by Qws** [MicrosoftDocs/msix-docs#165]
[Voer hier feedback in]
There is no AppxManifest.xml in VS2019 UWP project?

Why is the Signing app got so cumbersome, like I released UWP app year ago and it was way more pleasant than this new system, in fact, I can't even call it a system, it feels like you have destroyed it. It's chaotic mess to sign a key.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 8e95ba48-8d07-d390-d49b-801d70730bae
* Version Independent ID: 047d2736-f14e-610c-7396-89d2eae0f9cc
* Content: [Create a certificate for package signing - MSIX](https://docs.microsoft.com/nl-nl/windows/msix/package/create-certificate-package-signing)
* Content Source: [msix-src/package/create-certificate-package-signing.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/create-certificate-package-signing.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by Huios** [comment]
Forwarded issue to the Visual Studio team - https://developercommunity.visualstudio.com/idea/1223010/feedback-signing-uwp-app-for-windows-store-improve.html
