### ISSUE TITLE
Bad links on Pages - Deters Users away from the platform

### ISSUE THREAD

**Issue by LouMM** [MicrosoftDocs/msix-docs#166]
There are many pages that have bad links.
**Example:** https://docs.microsoft.com/en-US/windows/msix/package/device-architecture
**git:** https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/device-architecture.md
In this example, the  **_Windows 10 on ARM_** links are broken. Maybe use aka.ms ?
Cheers!

**Comment by dianmsft** [comment]
This has been fixed.
