### ISSUE TITLE
2020.709 release notes missing.

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/msix-docs#168]
[Enter feedback here]
Version 2020.709 was released to the insider's build (at least) last week. Release notes are missing here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2308559b-f8db-9fc7-a261-f92854214512
* Version Independent ID: 5b165ada-648f-f794-ade8-f6bdaa5af73d
* Content: [MSIX packaging tool insider program - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/insider-program)
* Content Source: [msix-src/packaging-tool/insider-program.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/insider-program.md)
* Product: **msix**
* GitHub Login: @sharlaakers
* Microsoft Alias: **shakers**

**Comment by sharlaakers** [comment]
Hi Tim, 

The release notes are now live.
