### ISSUE TITLE
Editing pre/post build events don't stick

### ISSUE THREAD

**Issue by chitturs** [MicrosoftDocs/msix-docs#169]
This is VERY frustrating. Adding something like copy foo $(TargetOutDir) in the pre or post-build event editor when saved just disappears. Searching the net looks like a known bug due to some ordering issue inside the .wapproj. Can we fix it please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bead27ac-8ed3-9886-26e2-47f49ea1efc0
* Version Independent ID: f354c6b6-b2e0-e070-dd0d-c3452a5635fb
* Content: [Package a desktop app from source code using Visual Studio - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net)
* Content Source: [msix-src/desktop/desktop-to-uwp-packaging-dot-net.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-packaging-dot-net.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by Huios** [comment]
Issue was forwarded to the Visual Studio team - https://developercommunity.visualstudio.com/content/problem/1223013/windows-app-packaging-project-pre-and-post-build-e.html
