### ISSUE TITLE
Restrict Permissions

### ISSUE THREAD

**Issue by philbarr** [MicrosoftDocs/msix-docs#17]
Do we really have to allow full read/write access to the entire public to use this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e73fcc-e961-749e-13e2-11fe5b2691dd
* Version Independent ID: 96e45113-f396-63af-ba9f-2e5c1e55a107
* Content: [Hosting Windows 10 app packages on AWS for web install - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/web-install-aws#feedback)
* Content Source: [msix-src/app-installer/web-install-aws.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/web-install-aws.md)
* Product: **msix**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by c-don** [comment]
the write access is required to upload content to the bucket for the owner. The public will only require read permissions.

**Comment by philbarr** [comment]
Ok, do we really have to give complete public read access to our s3 bucket? I tried applying permissions and using a signed url but App Installer rejects the URL.

**Comment by c-don** [comment]
Yes. You will need to give read access to your S3 bucket. There might be a way to only provide read access to a particular folder. 

What is the error that you see in App Installer?
