### ISSUE TITLE
Permission For Optional Packages In Store Submission Is Unclear

### ISSUE THREAD

**Issue by jcg3675** [MicrosoftDocs/msix-docs#170]
Page states that the dev must receive permission from MS prior to submitting an app to the Store with optional packages. The link to learn more about getting permission leads to a rather generic page on developer.microsoft.com with no mention of this. The resources linked on that page do have information about app submissions, but nothing about optional packages, let alone getting permission. Is permission still required prior to submitting an optional package app to the Store? How do I request approval?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c69bcb8c-0ac5-f63e-fc74-d2ea8570a000
* Version Independent ID: 60d94b38-c12a-3d1a-3367-9a1ba799be70
* Content: [Optional packages and related set authoring - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/optional-packages)
* Content Source: [msix-src/package/optional-packages.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/optional-packages.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
In the middle of restructuring the documentation to provide clarity. Will put this as a backlog item.
