### ISSUE TITLE
Why don't Microsoft use this?

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/msix-docs#173]
You've gone to all the trouble of creating MSIX, yet Microsoft still release software with exe installs.

Visual Studio, VSCode, Azure Storage Explorer for example.

If you're doing this then make it a prerequisite that all MS built software must go MSIX first (preferably in the Windows Store) so that Admins can mange things properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91be9c0-26f6-d263-099d-e58df9eee583
* Version Independent ID: 31f6e0f8-3951-9c04-f1c4-619a9c07a5fa
* Content: [What is MSIX? - MSIX](https://docs.microsoft.com/en-us/windows/msix/overview)
* Content Source: [msix-src/overview.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/overview.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
We are discussing internally with other Microsoft products about MSIX as their installer technology. You can let the products know you are interested in deploying their product as an MSIX in your environment.
