### ISSUE TITLE
AWS CDN usage with ms-appinstaller protocol

### ISSUE THREAD

**Issue by tylersouthard** [MicrosoftDocs/msix-docs#179]
The article references using a CDN to distribute a package hosted on S3. Our organization uses AWS CloudFront as a CDN for our S3 buckets. If I try to use a URL for the ms-appinstaller source that uses the CDN to access the package, I get the error "Error in parsing the app package." If I explicitly use the S3 URL that references the particular region (s3.eu-central-1.amazonaws.com), then it works fine. I would have thought my case would be supported, since the article is about using AWS to distribute a package via a CDN.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e73fcc-e961-749e-13e2-11fe5b2691dd
* Version Independent ID: 96e45113-f396-63af-ba9f-2e5c1e55a107
* Content: [Distribute a Windows 10 app from an AWS web service - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/web-install-aws)
* Content Source: [msix-src/app-installer/web-install-aws.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/web-install-aws.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by samiranshah** [comment]
Hi @tylersouthard, this issue is similar to https://github.com/MicrosoftDocs/msix-docs/issues/176. 
Since vanity URLs are not supported at this time, please make sure the original url ends with `.appinstaller`.

**Comment by samiranshah** [comment]
Closing this issue. Please reopen if required.
