### ISSUE TITLE
App Installer emitting a "Catastrophic error (0x8000FFFF)" on some machines

### ISSUE THREAD

**Issue by nbevans** [MicrosoftDocs/msix-docs#186]
We've been having this issue most of the year and it seems to be getting worse (that's the feeling anyway).

We have an B2B app which we sideload onto our customer machines via a `ms-appinstaller` web link. This app is a fully native UWP app. It is not a Desktop Bridge app.

Some machines can no longer install the app via the App Installer and it produces the `Catastrophic error (0x8000FFFF)` message as the error output.

I have inspected the `AILog.txt` from one such machine and it doesn't really provide any further insight as to the cause. But here is the relevant excerpt from that log anyway:

```
[Fri Oct  9 14:21:28 2020]{13164} ERROR: DeploymentCompletionCallback -> Install Operation Failed. Error Code: 0x8000ffff, Extended Error Code: 0x00000000
[Fri Oct  9 14:21:28 2020]{13164} DeploymentCompletionCallback -> deploymentResult.ErrorText() contains no meaningful value. Value: Unspecified error
[Fri Oct  9 14:21:28 2020]{13164} GetErrorMessageFromHResult -> Message: [Catastrophic failure]
[Fri Oct  9 14:21:28 2020]{13164} DeploymentCompletionCallback -> fallbackErrorText: Catastrophic failure (0x8000ffff)
```

So far we have to work around the issue by using PowerShell's `Add-AppxPackage "url to .appinstaller file" -AppInstallerFile` command which works flawlessly every time.

The problem though is that auto-updates (as per the clauses defined in the `.appinstaller` file) do not work. And nor does updating manually via running the `ms-appinstaller` link and clicking the Update button on App Installer. So it means we have to update via PowerShell as well which is clearly not a good experience for our end-users.

**Comment by Huios** [comment]
Hi @nbevans 

Thanks for reporting this. To help us diagnose the issue, can you please make a Feedback Hub submission in the **Developer Platform  > App Deployment** category, while reproducing the error. Please  attempt both the ms-appinstaller link and Add-AppxPackage based installation when submitting the repro. Can you please also attach a copy of your .appinstaller file, and then  post the link to your Feedback Hub submission on here when you're done.

Thanks,
Tanaka

**Comment by nbevans** [comment]
Hi @Huios We are just trying to get access to a machine with the problem then we will follow these steps.

**Comment by nbevans** [comment]
We managed to get access to a customer machine with the issue and followed your instructions above.

Here is a link to the Feedback Hub data that we recorded during both App Installer's attempt and then the successful Add-AppxPackage invocation:

https://aka.ms/AAa0c73

The data also includes the .appinstaller file and AILog.txt

Apologies for the delays in getting this data for you.

Thank you!

**Comment by Huios** [comment]
Hi @nbevans 

Thanks for filing the feedback! I'm forwarding this to our devs for investigation.

Cheers,
Tanaka

**Comment by nbevans** [comment]
> Hi @nbevans
> 
> Thanks for filing the feedback! I'm forwarding this to our devs for investigation.
> 
> Cheers,
> Tanaka

Just wondering if you have any news on this yet?

We're currently holding off releasing app updates because of this issue - so the impact is pretty high, for what it's worth.

**Comment by nbevans** [comment]
@chendrixson

**Comment by wcheng-msft** [comment]
Please re-file the feedback. The previous feedback failed to capture any logs and unfortunately the communication got lost in the shuffle.

**Comment by nbevans** [comment]
I submitted more feedback hub data: https://aka.ms/AAcg41e

**Comment by wcheng-msft** [comment]
@nbevans  Are you still seeing the 0x8000FFFF error too? That might be a different issue, so please file another feedback if you're able to reproduce failures with that error code.

Your feedback shows an 0x80D05011 error; we have a fix for the 0x80D05011 error in the next OS release, and are investigating whether we can release that in a patch to the existing releases. This is unfortunately an unexpected cache issue in the downloading mechanism used to retrieve the appinstaller file, so the issue should disappear after reboot. We don't have a reliable workaround for this.

**Comment by nbevans** [comment]
Apologies - I got my error codes mixed up. I have not seen the "Catastrophic error" 0x8000FFFF for a while but I aren't actively recording every case which occurs. I am of course keeping an eye out for it - along with any other interesting App Installer failures.

**Comment by samiranshah** [comment]
Closing for now. Please reopen if you have further questions.

**Comment by nbevans** [comment]
It happened again - on latest App Installer.

![image](https://user-images.githubusercontent.com/542188/145241004-7157dc37-a643-4928-97a3-27a4f2908269.png)

**Comment by wbokkers** [comment]
This needs to be reopened! Users still get this error message on installing from .appinstaller.

**Comment by nbevans** [comment]
Was getting this error on a customer with App Installer (0x8000FFFF)

Managed to get it to install via Add-AppxPackage command in the end after encountering this error. Had to uninstall some CoreRuntime package from All Users first in order for our installer to succeed. Bizarre.

Afterwards, I uninstalled the app. And tried App Installer again. Same 0x8000FFFF error. But Add-AppxPackage worked a second time absolutely fine.

**I am continually amazed by the disparity between App Installer and Add-AppxPackage. What are they doing different? Surely App Installer is just a UI shell wrapping around the same infrastructure used by the PowerShell command!?**

```
PS C:\Users\joebloggs> add-appxpackage -appinstallerfile "file:///C:/Users/joebloggs/Downloads/myapp.mobile.uwp%20(4).appinstaller"                  add-appxpackage : Deployment failed with HRESULT: 0x80073CFB, The provided package is already installed, and reinstallation of the package was blocked.       Check the AppXDeployment-Server event log for details.                                                                                                        Deployment of package Microsoft.NET.CoreRuntime.2.2_2.2.27902.3_x86__8wekyb3d8bbwe was blocked because the provided package has the same identity as an       already-installed package but the contents are different. Increment the version number of the package to be installed, or remove the old package for every    user on the system before installing this package.
NOTE: For additional information, look for [ActivityId] 29869d5d-24d6-0005-0b2b-8829d624d801 in the Event Log or use the command line Get-AppPackageLog
-ActivityID 29869d5d-24d6-0005-0b2b-8829d624d801
At line:1 char:1
+ add-appxpackage -appinstallerfile "file:///C:/Users/Mel.Kashuba/Downl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (file:///C:/User...4).appinstaller:String) [Add-AppxPackage], PSInvalidOperationException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```


```
remove-appxpackage -allusers "Microsoft.NET.CoreRuntime.2.2_2.2.27902.3_x86__8wekyb3d8bbwe"
```

**Comment by wbokkers** [comment]
We decided to create or own installer: a console app written in C++ that:

- Downloads the .appinstaller file
- Creates a powershell script with Add-AppxPackage -AppInstallerFile ...
- Runs the powershell script

This works much better than the official AppInstaller app.

**Comment by nbevans** [comment]
Yeah we have something similar too as a backup option. However in this case that too went wrong because of some bizarre file conflict:

> Deployment of package Microsoft.NET.CoreRuntime.2.2_2.2.27902.3_x86__8wekyb3d8bbwe was blocked because the provided package has the same identity as an already-installed package but the contents are different.

Had to manually uninstall this package using `Remove-AppxPackage -AllUsers` command.
