### ISSUE TITLE
Notify readers that ApplicationSettingsBase is unsupported

### ISSUE THREAD

**Issue by trympet** [MicrosoftDocs/msix-docs#187]
Desktop bridge does not support ApplicationSettingsBase. This should be noted so developers can use `ApplicationData.LocalSettings` instead.

Here are some StackOverflow questions mentioning this issue, answered by Microsoft employees:
[Desktop Bridge - Upgrade Settings not working](https://stackoverflow.com/questions/54349735/desktop-bridge-upgrade-settings-not-working)
[Windows Forms to UWP app via Desktop Bridge - User Settings are lost/reset on UWP app Upgrade](https://stackoverflow.com/questions/49561940/windows-forms-to-uwp-app-via-desktop-bridge-user-settings-are-lost-reset-on-uw?rq=1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12379f43-c827-669f-6aeb-4b4d8650cfdf
* Version Independent ID: fadedb99-8dfe-7371-105a-2944bc8d9766
* Content: [Prepare to package a desktop application (MSIX) - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-prepare)
* Content Source: [msix-src/desktop/desktop-to-uwp-prepare.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-prepare.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by anarvekar-msft** [comment]
Please feel free to reopen if this is still an issue for you
