### ISSUE TITLE
AppInstaller File Builder is "Untrusted app"

### ISSUE THREAD

**Issue by wadim1611** [MicrosoftDocs/msix-docs#189]
Can not install AppInstaller File Builder because it is an "Untrusted app"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b86dc038-4654-aeed-09db-8e702fba499c
* Version Independent ID: 50ec40a3-0fcb-1d68-782d-d1efbaf69312
* Content: [AppInstaller File Builder tool - MSIX](https://docs.microsoft.com/en-us/windows/msix/toolkit/msix-toolkit-appinstallerfilebuilder)
* Content Source: [msix-src/toolkit/msix-toolkit-appinstallerfilebuilder.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/toolkit/msix-toolkit-appinstallerfilebuilder.md)
* Product: **msix**
* GitHub Login: @RDMacLachlan
* Microsoft Alias: **romaclac**

**Comment by nbevans** [comment]
You need to install the app's certificate in your Trusted Publishers store.

**Comment by jvintzel** [comment]
There is actually a bug with timestamping and the App Installer app (the app used to drive the double click installation).  We are working on a servicing fix to resolve.  In the meantime you can install the app using Add-AppPackage PowerShell cmdlet.

**Comment by jgudmundson-RETSD** [comment]
@jvintzel Would this bug happen to be that the DGSSv2 is distributing certificates that are expiring in one day?

**Comment by Huios** [comment]
This issue should now be fixed in the latest version of App Installer - 1.4.3161.0
