### ISSUE TITLE
PDF error

### ISSUE THREAD

**Issue by sinand99** [MicrosoftDocs/msix-docs#19]
Download PDF option does not work. Please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91be9c0-26f6-d263-099d-e58df9eee583
* Version Independent ID: 31f6e0f8-3951-9c04-f1c4-619a9c07a5fa
* Content: [What is MSIX? - MSIX](https://docs.microsoft.com/en-us/windows/msix/overview)
* Content Source: [msix-src/overview.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/overview.md)
* Product: **msix**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue. We are looking into it and will update this thread when we know more.

**Comment by RAJU2529** [comment]
i have downloaded  pdf successfully .

**Comment by mcleanbyron** [comment]
Yes, this is now fixed. Thanks for reporting the error.
