### ISSUE TITLE
Number requirement list

### ISSUE THREAD

**Issue by ju2pom** [MicrosoftDocs/msix-docs#193]
Hi,
It could be useful to have a numbered list instead of unordered list of requirements.
This would be easier for everybody to refer to a specific point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12379f43-c827-669f-6aeb-4b4d8650cfdf
* Version Independent ID: fadedb99-8dfe-7371-105a-2944bc8d9766
* Content: [Prepare to package a desktop application (MSIX) - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-prepare)
* Content Source: [msix-src/desktop/desktop-to-uwp-prepare.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-prepare.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by dianmsft** [comment]
Thanks for the feedback. At some point we will be going through some of the documentation to make it easier to digest. We'll put this in our backlog as a documentation to look through.
