### ISSUE TITLE
Configure App Installer File through the Visual Studio project

### ISSUE THREAD

**Issue by mgregory22** [MicrosoftDocs/msix-docs#194]
The article tells me how to edit the .appinstaller file to adjust the update settings, but how do I adjust them in the project?  It's a build product.  I don't want to have to edit that file every time it's built.  I don't understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e69e20f-7cfc-aa28-85b8-f2deb8a69873
* Version Independent ID: c3fffd4b-4405-c347-2db8-95c5c0928de5
* Content: [App Installer file update settings - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/update-settings)
* Content Source: [msix-src/app-installer/update-settings.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/update-settings.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by Huios** [comment]
Hey @mgregory22 

What kind of build product is it, is this part of a CI/CD Pipeline or a local version of your app project in Visual Studio. Once you have created an App Installer file with the values you need, you can use that separate file and modify it apart from the build project. However, if you want to update it with each build locally, have a look at this - https://techcommunity.microsoft.com/t5/windows-dev-appconsult/introducing-the-new-app-installer-template-in-visual-studio-2019/ba-p/739019

**Comment by mgregory22** [comment]
Thank you so much for the reply!  Those articles are just what I needed!

Sorry for the lack of details.  I'm talking about a WPF app that we're building in Visual Studio and using an MSIX project to publish it to our local network, where a dozen users will access it when it's ready.

We just want to be able to give the users the ability to rollback to a previous version, prompt for confirmation before updating, etc.

**Comment by mgregory22** [comment]
Wait, I closed this issue prematurely.  Well, I guess now I'm talking about a different issue, but I set the ForceUpdateFromAnyVersion flag, and now I'm not sure how to perform a downgrade.  I fished around in the share and ran the .msixbundle of one the previous versions, but the behavior hasn't changed.  It still says a newer version is installed and I can only launch it.
