### ISSUE TITLE
Do desktop applications in Microsoft Store still have to support Windows 10 in S mode?

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/msix-docs#197]
The page claims:

> After you've created your Windows app package, please test your application to ensure that it works correctly on systems that run Windows 10 S. All apps submitted to the Microsoft Store must be compatible with Windows 10 S. Apps that aren't compatible won't be accepted in the store. See Test your Windows app for Windows 10 S.

However, according to <https://github.com/microsoft/terminal/issues/7724#issuecomment-698427871>, Microsoft's own Windows Terminal is not intended to work in S mode, even though it is being distributed in Microsoft Store. The claim may thus be out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12379f43-c827-669f-6aeb-4b4d8650cfdf
* Version Independent ID: fadedb99-8dfe-7371-105a-2944bc8d9766
* Content: [Prepare to package a desktop application (MSIX) - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-prepare)
* Content Source: [msix-src/desktop/desktop-to-uwp-prepare.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-prepare.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by sharlaakers** [comment]
Hi, 

This is still true, the Windows Terminal has a special exception waiver. 

Best,
Sharla
