### ISSUE TITLE
Change the title to cover more scenarios (not only UWP)

### ISSUE THREAD

**Issue by rido-min** [MicrosoftDocs/msix-docs#2]
MSIX/Appinstaller can be used to deploy not only UWP apps, the title of this page, and child pages is misleading

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 212730b4-6110-a2cd-f35a-12d7b0436c53
* Version Independent ID: 24ee02b5-a5bf-03e4-fe47-4cb21fc68b57
* Content: [Install UWP apps with App Installer](https://docs.microsoft.com/en-us//windows/msix/app-installer/app-installer-root)
* Content Source: [msix-src/app-installer/app-installer-root.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/app-installer-root.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by c-don** [comment]
Fixed the docs. thanks for the feedback.
