### ISSUE TITLE
ClickOnce reinvention?

### ISSUE THREAD

**Issue by miegir** [MicrosoftDocs/msix-docs#20]
ClickOnce reinvention?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 6501c0eb-cd77-1c38-116c-f6af06c4df13
* Version Independent ID: 7f9ae262-0f8d-43b4-c594-9c69aeacea36
* Content: [App Installer file overview - MSIX](https://docs.microsoft.com/ru-ru/windows/msix/app-installer/app-installer-file-overview#feedback)
* Content Source: [msix-src/app-installer/app-installer-file-overview.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/app-installer-file-overview.md)
* Product: **msix**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by c-don** [comment]
Hi @miegir - AppInstaller file does aim to provide the functionality provided by clickonce.
