### ISSUE TITLE
Running on .net solution outputs exe but not msix file

### ISSUE THREAD

**Issue by james1301** [MicrosoftDocs/msix-docs#204]
Hi I am using a pipeline with the MSIX Build and Package task, which succeeds but it only has an .exe file but no msix in the output?

Do I need to have the packaging project in my solution to use MSIX? I thought this sounded like it would package it, outside of this?

**Comment by samiranshah** [comment]
Hi @james1301, Yes, you do need the Windows Application Packaging Project to create an MSIX package, this is because the build and package task needs the Package.appxmanifest file.
