### ISSUE TITLE
Missing command line option

### ISSUE THREAD

**Issue by BenHagueLucidity** [MicrosoftDocs/msix-docs#205]
The page doesn't mention the --machinePassword switch for connecting to remote computers. Also doesn't mention that the switches are case sensitive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fad6dc2e-0d05-9bfb-498e-306e1dc8d572
* Version Independent ID: 323e44fe-70c8-8be8-db1e-7b9dec4bdaf7
* Content: [Create a package using the command line interface - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/package-conversion-command-line)
* Content Source: [msix-src/packaging-tool/package-conversion-command-line.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/package-conversion-command-line.md)
* Product: **msix**
* GitHub Login: @sharlaakers
* Microsoft Alias: **shakers**

**Comment by sharlaakers** [comment]
Documentation is updated.
