### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by hotcakex** [MicrosoftDocs/msix-docs#206]
Hi,
there is a grammar error in this document, where it says:

"It is highly recommended that Timestamping is used when signing your app with a certificate. Timestamping preserves the signature allowing the app package to **BE** accepted by app"

so before "accepted by app" there needs to be a "be"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5029ae62-c2de-bb03-0c1f-ada1e60c697d
* Version Independent ID: a7f66acc-0b1b-bcc0-b1a4-7eae63ee041e
* Content: [Sign a Windows 10 app package - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/signing-package-overview)
* Content Source: [msix-src/package/signing-package-overview.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/signing-package-overview.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
This has been fixed
