### ISSUE TITLE
Could do with more information to help diagnosing problems

### ISSUE THREAD

**Issue by yowl** [MicrosoftDocs/msix-docs#208]
https://docs.microsoft.com/en-us/windows/msix/app-installer/troubleshoot-appinstaller-issues#app-installer-event-logs

This says to check the logs, but not what to do with the information that is there.   For example this log message

```
The last successful state reached was Resolved. Failure occurred before reaching the next state Approved. hr: 0x8000FFFF
```

Its not that helpful, where are you meant to go from here?  What are the "states" that the installer goes through, where might it fail?  What does each "state" do?  Basically the user is left with stackoverflow or a premier support ticket.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3a8483-a56e-7f3d-8c25-1d8b18943342
* Version Independent ID: 3b8e451b-95b5-3d26-c7ec-160fef01d85e
* Content: [Troubleshoot installation issues with the App Installer file - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/troubleshoot-appinstaller-issues)
* Content Source: [msix-src/app-installer/troubleshoot-appinstaller-issues.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/troubleshoot-appinstaller-issues.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Hi, thanks for reaching out and identifying an area where we can improve our documentation. To view logs please go to this documentation - https://docs.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting?context=/windows/msix/render

**Comment by yowl** [comment]
Thanks, as you can see my error is not on that page.  I ended up creating a Premier support ticket (at some cost), that's still open so maybe if the resolution is useful I can post it here.

**Comment by dianmsft** [comment]
Of course. Can you describe what your are doing when you got this error? were you installing your MSIX package in a particular way?

**Comment by yowl** [comment]
Installing via AppInstaller.  From Edge, go to the generated AppInstaller html page and click the install button.  I'm not sure its worth you looking too closely at my specific case as it its probably an environment issue as the AppInstaller works in other environments.

**Comment by dianmsft** [comment]
Closing for now. Please reopen if needed.
