### ISSUE TITLE
Symbolic Links

### ISSUE THREAD

**Issue by sp-stuart-harrison** [MicrosoftDocs/msix-docs#21]
It would appear that the certificates cannot be supplied using symbolic links, the StoreKey must be a physical file on the disk.
I can't see any good reason why this should be the case, but nevertheless, it exists as a restriction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930536bd-243e-3024-1c8d-b352384a2718
* Version Independent ID: 518c2651-df80-73fb-f28c-a48e8dde863d
* Content: [Create an App Installer file with Visual Studio - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/create-appinstallerfile-vs)
* Content Source: [msix-src/app-installer/create-appinstallerfile-vs.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/create-appinstallerfile-vs.md)
* Product: **msix**
* GitHub Login: @ridomin
* Microsoft Alias: **rmpablos**

**Comment by c-don** [comment]
Hi @sp-stuart-harrison  - are you referring to certificates to sign the app package? can you provide more information about your scenario.

**Comment by sp-stuart-harrison** [comment]
Sure, we have an automatically-generated packaging project, created using "premake" (https://premake.github.io/).
In order to supply this tool with the required data, we have "external" files that need to be injected into the creation process, currently:
- MyApp.appxmanifest
- MyApp_StoreKey.pfx
- MyApp.StoreAssociation.xml
- Images/... (contains LargeTile, SmallTile, etc)

These files are stored in a higher-level folder, e.g. C:\Dev\MyApp\Prep, and I would like to be able to "symbolically link" to the files when we create the Packaging project (currently in, e.g. C:\Dev\MyApp\Packaging\).  This is to overcome a restriction that the .wapproj cannot access files outside the project root folder (e.g. anything with "..\" at the start).
Symbolic links work for the Images folder and the appxmanifest file, but for some reason not the StoreKey.pfx and the StoreAssociation.xml.
I get the error "A signing key is required in order to package this project. Please specify a PackageCertificateKeyFile or PackageCertificateThumbprint value in the project file." which implies the build process can't read the StoreKey if it's a symbolic link.

I'm using Windows 10, running the command "mklink (targetpath) (sourcepath)" where both targetpath and sourcepath are absolute (i.e. not relative) paths.

**Comment by dianmsft** [comment]
HI @sp-stuart-harrison can you verify if you are still running into this issue?

**Comment by sp-stuart-harrison** [comment]
@dianmsft Yes, it's still an issue for us.

**Comment by dianmsft** [comment]
@sp-stuart-harrison can you file feedback on this and we can take a look at what is going on. Please write back with the Title of the feedback.
