### ISSUE TITLE
AppInstaller Protocol Not Recognised

### ISSUE THREAD

**Issue by jonrmorgan99** [MicrosoftDocs/msix-docs#214]
I can't understand what this means:

![image](https://user-images.githubusercontent.com/77990149/111647464-6c17b980-87fa-11eb-808f-58aaa2bf11ac.png)

I'm trying to get appinstaller to run an MSIX package of a desktop winforms app. I created in VS2019  and deployed to LocalHost.
Everything I've read suggests all I need to do is click on Install Now in the Index.html page supplied, but when I do that I get this message from FIrefox:

![image](https://user-images.githubusercontent.com/77990149/111648109-f829e100-87fa-11eb-987e-f0e650216bd1.png)

How do I get the browser to recognise the appinstaller protocol ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e2aa1ef-b0f5-912e-a012-6510a92d8861
* Version Independent ID: 8abd36f6-a781-07c3-4bf7-bfec7d4b7f88
* Content: [Distribute a Windows 10 app from an IIS server - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/web-install-iis)
* Content Source: [msix-src/app-installer/web-install-IIS.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/web-install-IIS.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by RDMacLachlan** [comment]
Hi @jonrmorgan99, 

Thank you for the feedback, I have some follow-up questions to better understand your experience. Could you please provide guidance to the following questions:

- Which Operating System are you using (EG: Windows 10 20H1 Enterprise)? 
- Does this happen when you attempt to install the Windows App using Microsoft Edge?
- Does your Windows App link contain "ms-appinstaller?source=" as a prefix to your Windows App's location?

I look forward to hearing from you on this.

Thank you,
Roy MacLachlan

**Comment by jonrmorgan99** [comment]
Hi Roy,

 

Thanks for picking up this issue.

 

I’m on Version  10.0.19042 Build 19042. I don’t use Edge – I’m using Firefox.

Yes, the app link does contain "ms-appinstaller?source=" as a prefix to my Windows App's location.

 

As it’s been several weeks since I posted this issue, I’ve abandoned MSIX for the time being and am now using net5 ClickOnce for deployment.

If you have a solution/workaround I can try another MSIX build.

 

Regards

 

Jon

**Comment by RDMacLachlan** [comment]
Hi @jonrmorgan99, 

Just wanted to give you an update, as I am working on re-creating your experience and will respond with more details afterwards.

Thank you,
Roy

**Comment by RDMacLachlan** [comment]
Hi @jonrmorgan99,

I've tried to re-create your error, and was unable to using a default build of the Windows 10 Operating System.

Can you please run the following command to see if you have the required Desktop App installed on your test machine:
_Get-AppxPackage *DesktopAppInstaller*_

Let me know what the results of your cmdlet run look like.

**Comment by RDMacLachlan** [comment]
Hi Jon,

To answer your question, the required Windows App is: **Microsoft.DesktopAppInstaller**. I appreciate your willingness to work with me on investigating this issue that you had experienced.

If possible, are you able to share the Windows App that you had created with me?


### **Troubleshooting Steps:**
1. Using Windows Run, test launch your Windows App using _ms-appinstaller?source="<Path>"_ as your run command. Make sure to remove _<Path>_ and replace with the path to your Windows App.

1. Verify the settings are correct for the File Type Association. Open the Windows Settings App and navigate to **Apps >> Default apps** then scroll to the bottom and select the **Choose default apps by file type** link. Look for the following Files Types and their Associated Apps in the list:

  | FileType | Associated App |
  |----------|-------------------|
  | *.appinstaller | App Installer |
  | *.msix | App Installer |
  | *.appx | App Installer |
  | *.msixbundle | App Installer |
  | *.appxbundle | App Installer |

3. Launch the website from both FireFox and Edge browsers, and attempt to install the Windows Apps:
https://royappauthtest.z13.web.core.windows.net/

> **Please Note** that the Windows Apps is signed using a non-thirdparty trusted certificate, and as you do not have this certificate installed the install is expected to fail because it is an untrusted app. The goal is to confirm that the Desktop App Installer file launches with the appropriate information.

**Comment by jonrmorgan99** [comment]
Thanks RD.

 

My *.appinstaller file type had been re-allocated. Resetting to associate it with App Installer fixed the problem.

 

However I’m staying with ClickOnce, at least for the time being. 

I only need to deploy a small WInform desktop app. but require in-app updating which I implemented in NetFx using the Application.Deployment class.

Unfortunately this was removed in Net5, although some of its functionality may be replaced at some stage.

 

Is in-app updating available with MSIX – I couldn’t see it in the docs ?

**Comment by RDMacLachlan** [comment]
Hi Jon,

Currently the Windows AppInstaller file provides the support you want for delivering your Windows Apps from an online source, and with the AppInstaller file you can configure the automation of the update checks (See Docs Article: [App Installer file update settings - MSIX | Microsoft Docs](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows%2Fmsix%2Fapp-installer%2Fupdate-settings&data=04%7C01%7CRoy.MacLachlan%40microsoft.com%7Cb27872e6d805442c44f408d919836c0f%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637568874635526547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GWACqjo56RZGwF0LhYPNZLzqzrEStXkL966%2FinjlTlQ%3D&reserved=0)).

Available in Windows 10 Insider Builds is the ability to embed an AppInstaller file in your Windows App enabling you to configure automatic update settings, and the ability to prompt for authentication to secured storage locations allowing you to protect or prevent unwanted access to your Windows AppInstaller file, and the Windows App installation media.

**Comment by jonrmorgan99** [comment]
Thanks Roy. That sounds promising. I'll checkout the Insider Builds for in-app updating support. Jon
