### ISSUE TITLE
Missing FOD location for the Windows 10 20H2 MSIX Drivers

### ISSUE THREAD

**Issue by roymaclachlan** [MicrosoftDocs/msix-docs#216]
Article outlines the location for the MSIX Drivers for previous versions of Windows, but not for the MSIX Driver on Windows 10 20H2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39e02e6d-02b2-fc96-2ef2-ae27d1d60ae8
* Version Independent ID: ce70da72-0526-53e1-f005-9f64641ed286
* Content: [Using the MSIX Packaging Tool in a disconnected environment - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/disconnected-environment)
* Content Source: [msix-src/packaging-tool/disconnected-environment.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/disconnected-environment.md)
* Product: **msix**
* GitHub Login: @sharlaakers
* Microsoft Alias: **shakers**

**Comment by sharlaakers** [comment]
Documentation has been updated.
