### ISSUE TITLE
Partner Update Details for MSIX Partners

### ISSUE THREAD

**Issue by danielwilliamscamwood** [MicrosoftDocs/msix-docs#217]
Hello

We have an updated PNG and URL for our Camwood profile on for the MSIX Partners Page. Can you let me know how to update with the latest information for Camwood.

Thank you

Daniel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b4773f4-e24d-7644-f5ac-fea26a5f5f95
* Version Independent ID: 0de07bea-5912-9005-51d2-b5fcb8bc31dd
* Content: [MSIX partners - MSIX](https://docs.microsoft.com/en-us/windows/msix/partners)
* Content Source: [msix-src/partners.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/partners.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
This has been updated.
