### ISSUE TITLE
How to create the SLN file?.

### ISSUE THREAD

**Issue by amalkabraham001** [MicrosoftDocs/msix-docs#218]
Hi team,

The document is vague. it is not telling about how to create the SLN file or what all it contains?. As a novice to MSIX via devops, I dont know where I need to give my executable which will be get created to MSIX. Please add a link on how to create SLN or explain the relevance of the variables you are using in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 117dd71d-8f8c-3615-a844-bbc0c076327b
* Version Independent ID: 962ddf35-8f87-fe37-d90c-dcca230f4f28
* Content: [MSIX Packaging Extension - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/msix-packaging-extension?tabs=yaml)
* Content Source: [msix-src/desktop/msix-packaging-extension.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/msix-packaging-extension.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by samiranshah** [comment]
Hi @amalkabraham001 the .sln file mentioned here is your solution file from your windows app source code. If you are looking to build an MSIX package from your windows app source code and then use CI/CD, you can start here: https://docs.microsoft.com/en-us/windows/msix/desktop/source-code-overview
