### ISSUE TITLE
The <File> tag should have override option.

### ISSUE THREAD

**Issue by jigneshdesaiIndia** [MicrosoftDocs/msix-docs#219]
The <File< tag should have override option.   Helpful when MainApplication has config.txt, but we want packaging should override if the file already exists in the destination folder.  Actually by default override should be true for any file mentioned in packaging folder project.

 ```
  <Package ID="x64" ProcessorArchitecture="x64">
      <Files>
        <File DestinationPath="MainApplication\config.txt" SourcePath="config.txt"  Override="true" />
        </Files>
    </Package>

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d968f14c-c080-a081-0007-480ca4e1f4bd
* Version Independent ID: 42f3d929-bb46-e075-09e2-7cd7ebddfe2e
* Content: [Package creation with the packaging layout - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/packaging-layout)
* Content Source: [msix-src/package/packaging-layout.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/packaging-layout.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Thanks for writing this. We currently do not support the override. I've put this in our backlog. Feel free to post feature request ask in  our tech community https://techcommunity.microsoft.com/t5/msix/ct-p/MSIX under the Ideas section
