### ISSUE TITLE
Application Packaging Project does not recognize language resources.

### ISSUE THREAD

**Issue by jigneshdesaiIndia** [MicrosoftDocs/msix-docs#220]
I have 15+ languages resource file in main project (WPF).  I am using Application Packaging Project to package WPF project. 

Application Packaging Project's Package.appxmanifest does not consider multilingual resx files available in source project.   The final output of the manifest file has following lines and it does not add any other languages.  as a result when package is uploaded on store it only shows en-US as supported languages.

<Resources>
  <Resource Language="EN-US"/>
  <Resource Scale="200"/>
</Resources>

**Comment by edwardskrod** [comment]
@jigneshdesaiIndia   

Thank you for bringing this to our attention.  Can you please post the final output of the manifest file?   

What version of Visual Studio are you using?

**Comment by jigneshdesaiIndia** [comment]
Few Lines are changed to hide sensitive information…

manifest file output as below.

Regards


<?xml version="1.0" encoding="utf-8"?>

<Package
  xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
  xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
  xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"
  IgnorableNamespaces="uap rescap">

  <Identity
    Name="xxx……….."
    Publisher="CN=ED……"
    Version="3.0.7.0" />

  <Properties>
    <DisplayName> Calendar</DisplayName>
    <PublisherDisplayName> LLC</PublisherDisplayName>
    <Logo>Images\StoreLogo.png</Logo>
  </Properties>

  <Dependencies>
    <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.0.0" MaxVersionTested="10.0.0.0" />
    <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.14393.0" MaxVersionTested="10.0.14393.0" />
  </Dependencies>

  <Resources>
    <Resource Language="x-generate"/>
  </Resources>

  <Applications>
    <Application Id="App"
      Executable="$targetnametoken$.exe"
      EntryPoint="$targetentrypoint$">
      <uap:VisualElements
        DisplayName=" Calendar"
        Description=" into csv format."
        BackgroundColor="transparent"
        Square150x150Logo="Images\Square150x150Logo.png"
        Square44x44Logo="Images\Square44x44Logo.png">
        <uap:DefaultTile Wide310x150Logo="Images\Wide310x150Logo.png"  Square71x71Logo="Images\SmallTile.png" Square310x310Logo="Images\LargeTile.png">
        </uap:DefaultTile >
        <uap:SplashScreen Image="Images\SplashScreen.png" />
      </uap:VisualElements>
    </Application>
  </Applications>

  <Capabilities>
    <Capability Name="internetClient" />
    <rescap:Capability Name="runFullTrust" />
  </Capabilities>
</Package>

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by edwardskrod** [comment]
One last question, what version of VS are you using?

**Comment by jigneshdesaiIndia** [comment]
Microsoft Visual Studio Professional 2019
Version 16.9.4

Regards


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by edwardskrod** [comment]
This is "by design."   MSIX, in general, doesn't know anything about resx/satellite assemblies.  It only can handle resw.
The way MSIX handles languages is by splitting them into different bundles.   This doesn't really work for old platforms.

It looks like you will need to edit your manifest if you want it to show that they support multiple languages.

You'll have to replace this:

  <Resources>
    <Resource Language="x-generate"/>
  </Resources>
  
 With something like this:
 
 <Resources>
  <Resource Language="EN-US" />
  <Resource Language="JA-JP" />
  <Resource Language="FR-FR" />
</Resources>

https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/manage-language-and-region
