### ISSUE TITLE
Weird grammar on app-installer/web-install-iis

### ISSUE THREAD

**Issue by lechacon** [MicrosoftDocs/msix-docs#221]
On the note for Step 7 it says:

> On newest Microsoft web technology .Net Core. Web site build using .Net Core ASP ignore web.config static content mimeMap. As a result, to proper configuration of .Net Core web site which will host your MSIX installation you need modify Configure method in Startup.cs file.

This seems to be using some weird/bad grammar to me.
For example, "to proper configuration of .Net Core web site" should probably be "to properly configure the .Net  Core web site". This is not the only issue; the whole paragraph is hard to read for me.

Also, ".Net Core" should probably be ".NET Core".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e2aa1ef-b0f5-912e-a012-6510a92d8861
* Version Independent ID: 8abd36f6-a781-07c3-4bf7-bfec7d4b7f88
* Content: [Distribute a Windows 10 app from an IIS server - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/web-install-iis)
* Content Source: [msix-src/app-installer/web-install-IIS.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/web-install-IIS.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Docs have been updated to resolve issue.

**Comment by james-winstanley** [comment]
> Docs have been updated to resolve issue.

Incorrect. The same incoherent note is still on the page.

![image](https://github.com/MicrosoftDocs/msix-docs/assets/3266204/33045648-0695-4e77-901d-3938339a930e)
