### ISSUE TITLE
Quick question - Office 2016 & Visual Studio 2019

### ISSUE THREAD

**Issue by msejaz** [MicrosoftDocs/msix-docs#224]
I've packaged apps that are in .exe format and are available as a stand-alone. Now I need to package Office 2016 that has a range of files with different extensions. MSIX Packaging Tool is asking to choose the installer I want to package. What should I actually package? 

Similarly, I also want to package Visual Studio 2019 using MSIX Packaging tool.

Please assist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 915f8c22-43ba-79bd-140a-09665fdc6dbb
* Version Independent ID: 8148245b-80c1-7062-ace3-44c61c03eff7
* Content: [MSIX resources - MSIX](https://docs.microsoft.com/en-us/windows/msix/resources)
* Content Source: [msix-src/resources.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/resources.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Hello, Windows and Office are working hard to enable M365 Apps (e.g. Word, PowerPoint, Excel) to be packaged and delivered in MSIX format with the same full extensibility that customer enjoy in C2R and MSI; we’ll communicate details and timelines as these become available. As a result we do not recommend repackaging Office at this time. 

Also we do not recommend repackaging Visual Studio 2019 at this time.
