### ISSUE TITLE
MSIX services are supported now.

### ISSUE THREAD

**Issue by sanderdewit** [MicrosoftDocs/msix-docs#229]
It seems the website with msix rules is a bit behind.
it states;
_Your application requires a kernel-mode driver or a Windows service. MSIX does not support a kernel-mode driver or a Windows service that needs to run under a system account. Instead of a Windows service, use a background task._

As since Win10 2004 packaging of Services is supported; https://docs.microsoft.com/en-us/windows/msix/packaging-tool/convert-an-installer-with-services

Later it states;
_Your application writes to the AppData folder or to the registry with the intention of sharing data with another app. After conversion, AppData is redirected to the local app data store, which is a private store for each app._
With the new insider release in combination with shared containers. this is supported.

_Your application writes to the install directory for your app. For example, your application writes to a log file that you put in the same directory as your exe. This isn't supported, so you'll need to find another location, like the local app data store._
This can be solved by applying the package support framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12379f43-c827-669f-6aeb-4b4d8650cfdf
* Version Independent ID: fadedb99-8dfe-7371-105a-2944bc8d9766
* Content: [Prepare to package a desktop application (MSIX) - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-prepare)
* Content Source: [msix-src/desktop/desktop-to-uwp-prepare.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-prepare.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by RDMacLachlan** [comment]
The documentation has been updated to reflect MSIX supports packaging of applications with services.
