### ISSUE TITLE
Links to PKI documentation are broken

### ISSUE THREAD

**Issue by juanfer-az** [MicrosoftDocs/msix-docs#231]
Links to Public Key Infra documentation (https://docs.microsoft.com/en-us/powershell/module/pkiclient/) are broken.
Examples:
- Public Key Infrastructure Cmdlets
- New-SelfSignedCertificate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e95ba48-8d07-d390-d49b-801d70730bae
* Version Independent ID: 047d2736-f14e-610c-7396-89d2eae0f9cc
* Content: [Create a certificate for package signing - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing)
* Content Source: [msix-src/package/create-certificate-package-signing.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/create-certificate-package-signing.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by juanfer-az** [comment]
Looks like they should point to https://docs.microsoft.com/en-us/powershell/module/pki

**Comment by dianmsft** [comment]
Thanks for pointing this out. The link should be fixed now
