### ISSUE TITLE
Automatic installation of software after the installation of MSIX bundle

### ISSUE THREAD

**Issue by caraevangeline** [MicrosoftDocs/msix-docs#232]
Is there any possibility of automatically downloading and installing an application from internet after completing the download of the app written in C# and packed using MSIX package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45e4355-afe9-ad10-0772-032b2ff288bd
* Version Independent ID: 3d281169-5030-2859-4c83-9cfc9fc3f653
* Content: [Create an MSIX package from any desktop installer - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/create-app-package)
* Content Source: [msix-src/packaging-tool/create-app-package.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/create-app-package.md)
* Product: **msix**
* GitHub Login: @sharlaakers
* Microsoft Alias: **shakers**

**Comment by sharlaakers** [comment]
Hi, could you provide a bit more context about your scenario? This could be taken a few different ways depending on what you really need.
