### ISSUE TITLE
Group Policy Software Installation

### ISSUE THREAD

**Issue by pippipmilk** [MicrosoftDocs/msix-docs#24]
Why on earth is Group Policy mentioned in this context with mentioning Group Policy Software Installation?  This article seems as though it was written by someone who kept hearing Group Policy mentioned in connection with application packaging but didn't realise it was Group Policy Software Installation that people were talking about.

If MSIX is going to be useful it's going to have to be able to be deployed using Group Policy Software Installation and MSI is today.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4cb9373-33f7-a4c9-18ba-ac6323d0bba8
* Version Independent ID: cc621151-fe24-7cad-8314-8a341a216458
* Content: [How Group Policy work with MSIX packaged apps - MSIX](https://docs.microsoft.com/en-us/windows/msix/group-policy-msix#feedback)
* Content Source: [msix-src/group-policy-msix.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/group-policy-msix.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Will provide additional sentence to clarify article.
