### ISSUE TITLE
Applications node not available under Packaging Project

### ISSUE THREAD

**Issue by docfresh** [MicrosoftDocs/msix-docs#240]
In this URL, under step 4, the "Applications" node is not visible when creating a new Windows Application Packaging Project: https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net

Visual Studio 16.10.0
.NET 5

![image](https://user-images.githubusercontent.com/8064022/120584944-7b200800-c3f6-11eb-8ffa-ed825fa89675.png)

Attempting to build the project yields this error: 
"Project must have a reference to an application. Please add a reference under the 'Applications' node in the Solution Explorer."

However, this node does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bead27ac-8ed3-9886-26e2-47f49ea1efc0
* Version Independent ID: f354c6b6-b2e0-e070-dd0d-c3452a5635fb
* Content: [Package a desktop app from source code using Visual Studio - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net)
* Content Source: [msix-src/desktop/desktop-to-uwp-packaging-dot-net.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-packaging-dot-net.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by edwardskrod** [comment]
In 16.10, we added a "Dependencies" Node to the Windows Application Packaging Project.   The "Applications" Node is now a sub-node under the "Dependencies" Node.

![ApplicationsNode](https://user-images.githubusercontent.com/5585130/120690869-c298a980-c473-11eb-9fa4-e425bdeeb238.png)

**Comment by edwardskrod** [comment]
The documentation for this change can be found in the Visual Studio 16.10 Release Notes:
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#WAPAnchor

**Comment by docfresh** [comment]
It is not under Dependencies either.
![image](https://user-images.githubusercontent.com/8064022/120691492-2919c980-c46c-11eb-85e2-ef3aabbcbed4.png)

**Comment by edwardskrod** [comment]
You'd have to add a Project Reference by right-clicking the Dependencies Node and click "Add Project Reference."   Add the project reference to the xns6 project.  The Applications Node should appear and should have the reference to the project.

**Comment by docfresh** [comment]
Thank you for the assistance.  It appears step 4 will need to be updated in the linked documentation.

**Comment by edwardskrod** [comment]
You're very welcome.  Docs team, please let me know if there's anything you need from me.

**Comment by samiranshah** [comment]
Thanks @docfresh for bringing this up.
Thanks @edwardskrod for your help.
Here is a PR to update our documentation https://github.com/MicrosoftDocs/msix-pr/pull/704

**Comment by samiranshah** [comment]
Closing this issue. Please reopen if required.

**Comment by Zainab-Git** [comment]
> You'd have to add a Project Reference by right-clicking the Dependencies Node and click "Add Project Reference." Add the project reference to the xns6 project. The Applications Node should appear and should have the reference to the project.
When Add Project Reference this error occured:
![Screenshot 2023-11-22 164212](https://github.com/MicrosoftDocs/msix-docs/assets/103384943/5b64d739-25a3-48a5-8265-9517339034fa)
