### ISSUE TITLE
Url redirecting you to a non-public location

### ISSUE THREAD

**Issue by pkoelemij** [MicrosoftDocs/msix-docs#245]
Under the header of "Manage access through Group Policy" there is a link that is redirecting you to https://review.docs.microsoft.com/windows/msix/group-policy-msix and not https://docs.microsoft.com/windows/msix/group-policy-msix. The link is broken because that URL isn't public. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e819f4df-eb7b-81a7-e794-183a0f9650b2
* Version Independent ID: 23a9f206-22bb-a313-243e-a1652739c254
* Content: [Distribute your MSIX in an enterprise environment - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/managing-your-msix-deployment-enterprise)
* Content Source: [msix-src/desktop/managing-your-msix-deployment-enterprise.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/managing-your-msix-deployment-enterprise.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by dianmsft** [comment]
This has been fixed
