### ISSUE TITLE
Basic http authentication for appinstaller file download

### ISSUE THREAD

**Issue by atjg** [MicrosoftDocs/msix-docs#248]
Hello. 

Can you describe if it is possible to protect the download resource with basic http authentication?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e2aa1ef-b0f5-912e-a012-6510a92d8861
* Version Independent ID: 8abd36f6-a781-07c3-4bf7-bfec7d4b7f88
* Content: [Distribute a Windows 10 app from an IIS server - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/web-install-iis)
* Content Source: [msix-src/app-installer/web-install-IIS.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/web-install-IIS.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Closing as we are following the issue with https://github.com/MicrosoftDocs/msix-docs/issues/250
