### ISSUE TITLE
It is better to add that the Msix file name should not be changed

### ISSUE THREAD

**Issue by shinnosukekubo** [MicrosoftDocs/msix-docs#249]
It is better to add that the Msix file name should not be changed

Don't change it like this
"MyApp.Package_1.0.0.0_x86_Debug.msix" to "MyApp.msix".

Probably the cause is to access the uri of the original folder name when Differential updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 301a223f-e298-88d1-24ba-3c6b645fcc21
* Version Independent ID: 67ffea0e-c3bf-3a88-cf74-3c83a508d353
* Content: [Differential updates MSIX app package - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/managing-your-msix-deployment-update)
* Content Source: [msix-src/desktop/managing-your-msix-deployment-update.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/managing-your-msix-deployment-update.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by anarvekar-msft** [comment]
I'm not clear what the question is. Could you please clarify?

As a side note, you can name your package itself literally anything. But what you name it inside the manifest is the actual identity of the app.

**Comment by shinnosukekubo** [comment]
@anarvekar-msft 
Thank you for your confirmation.

The AddAppxPackage command did not work when I renamed the Msix file published by the Visual Studio packaging project.

not worked
`Add-AppxPackage https://mywebserver/{renamed name}.msix`

worked
`Add-AppxPackage https://mywebserver/{origin name}.msix`

If it's msix in local storage instead of https, it works.
`Add-AppxPackage C:\localstorage\{renamed name}.msix`

I thought that there was a problem with the file name when updating the difference of msix.

**Comment by anarvekar-msft** [comment]
@shinnosukekubo Thanks for the clarification. There shouldn't be a limitation on the name of the package.

Could you please share the urls of the apps you are trying to install so I can try and reproduce the error?

**Comment by shinnosukekubo** [comment]
@anarvekar-msft 
Now that we have reproduced it, write the url and the procedure.

not worked
`Add-AppxPackage https://msixteststorage.blob.core.windows.net/msix/WapProjTemplate1.msix`

I just renamed msix.
worked
`Add-AppxPackage https://msixteststorage.blob.core.windows.net/msix/WapProjTemplate2.msix`

It seems that there was a problem with the behavior until the issuance of msix.

·procedure
I had two packaging projects in one .sln.
"WapProjTemplate1"
"WpaProjTemplate1.Demo"

In this state, if you change the "issued msix file name to "WapProjTemplate1", the phenomenon will occur.

Any file name other than "WapProjTemplate1" will work, but this name will not work.

When I had one packaging project, it worked fine, so I think it has something to do with it.
What is the relationship between having two packaging projects and the Msix filenames?

sourcecode
https://github.com/shinnosukekubo/WpfApp5

Thank you

**Comment by anarvekar-msft** [comment]
I spoke with some folks about what you are seeing. We think we have an idea of what the problem might be. It might be related to a local caching issue when using the uri.

Can you either create a folder in your azure storage blob, and store the msix file there, or create a new storage blob and store the msix file there? Essentially we want to change the path, but keep the filename the same.

**Comment by shinnosukekubo** [comment]
@anarvekar-msft 
I tried it today and both URIs worked.

I would like to check the local cache when it occurs again.

Thank you for your support!
