### ISSUE TITLE
UpdateBlocksActivation requires 1903?

### ISSUE THREAD

**Issue by ridomin** [MicrosoftDocs/msix-docs#25]
This doc mentions that UpdateBlocksActivation is available from 1809, but some users report it only works from 1903.

https://github.com/microsoft/devops-for-windows-apps/issues/25#issuecomment-500182815

Please clarify

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e69e20f-7cfc-aa28-85b8-f2deb8a69873
* Version Independent ID: c3fffd4b-4405-c347-2db8-95c5c0928de5
* Content: [App Installer file update settings - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/update-settings#feedback)
* Content Source: [msix-src/app-installer/update-settings.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/update-settings.md)
* Product: **msix**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for pointing this out. UpdateBlocksActivation was added to the schema for 1809 but it turns out it isn't actually supported by AppInstaller at run time until 1903. I have updated the article.
