### ISSUE TITLE
What should be passed as the volume?

### ISSUE THREAD

**Issue by yowl** [MicrosoftDocs/msix-docs#254]
The example is nice, but its not clear what to pass as the volume, could that be explained here?

i.e. here:
```
public async void CheckForAppInstallerUpdatesAndLaunchAsync(string targetPackageFullName, PackageVolume packageVolume)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61dbc475-482a-3e2f-b41e-bb9d35d100e5
* Version Independent ID: 93e1b53d-8150-5693-ca85-acb317f1f666
* Content: [Update non-Store published apps from your code - MSIX](https://docs.microsoft.com/en-us/windows/msix/non-store-developer-updates)
* Content Source: [msix-src/non-store-developer-updates.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/non-store-developer-updates.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **diahar**

**Comment by anarvekar-msft** [comment]
Thank you for your question @yowl . PackageVolume is this: https://docs.microsoft.com/en-us/uwp/api/Windows.Management.Deployment.PackageVolume?view=winrt-20348

It's basically C: or D:, whichever drive the package was installed to.

**Comment by yowl** [comment]
Thanks, when requesting an update, does it have to be the same as where the package was installed originally, or can it be `ew PackageManager().GetDefaultPackageVolume()` ?

**Comment by anarvekar-msft** [comment]
@yowl It has to be the same as where the package was installed originally. To find the PackageVolume you can use FindPackageVolumes. It returns a list of PackageVolumes and you can pass the one you want to the method.

https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.findpackagevolumes?view=winrt-20348

You only need to do this for the first time install.  If you're doing an update, you can just pass in null for packageVolume parameter and skip that step

**Comment by yowl** [comment]
`
> You only need to do this for the first time install. If you're doing an update, you can just pass in null for packageVolume parameter and skip that step
`

Ah, thanks a lot, that is what I needed to know.
