### ISSUE TITLE
Scary warnings when enabling out of store updates

### ISSUE THREAD

**Issue by yowl** [MicrosoftDocs/msix-docs#255]
When you following the instructions https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/non-store-developer-updates.md#update-non-store-published-app-packages-from-your-code  and add the requires capability `packageManagement`, your users are faced with this

![image](https://user-images.githubusercontent.com/2720041/132040400-7a0b018e-578d-41f9-9963-e42636adbdff.png)

Which reads like "by installing this app, it will have the ability to mess with other apps installation"   Is that really the case, if so, then there should be another capability or something, which just lets it changes its own installation and a corresponding message.

**Comment by samiranshah** [comment]
Hi @yowl, the intent of the pop-up is to inform the user of the information/apps/capabilities this app can access, not to scare the user or mess with other apps installation. Here's some more information about App capability declarations https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations

**Comment by yowl** [comment]
Thanks, but I stand by my argument.  This capability gives the app the permission to "manage other apps directly." (quote from your link).   There is not a good reason why my app should be doing that, and so it would be better if there was another permission, "manage just this app".

**Comment by samiranshah** [comment]
Thanks for your feedback @yowl. We will look at it in a future release.

**Comment by samiranshah** [comment]
Hi @yowl, I see that the documentation might have been a bit confusing. To clarify, you'd need to declare the capability for cross publisher scenario, but managing your own app should work without declaring capabilities. I've updated the documentation with this clarification.
Thanks!
