### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by stonar89** [MicrosoftDocs/msix-docs#257]
i dont know how to resolve this issue with your information sorry 

App installation failed with error message: Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80070570. (0x80070570)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3a8483-a56e-7f3d-8c25-1d8b18943342
* Version Independent ID: 3b8e451b-95b5-3d26-c7ec-160fef01d85e
* Content: [Troubleshoot installation issues with the App Installer file - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/troubleshoot-appinstaller-issues#feedback)
* Content Source: [msix-src/app-installer/troubleshoot-appinstaller-issues.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/troubleshoot-appinstaller-issues.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Hi there, can you provide more information here. Was this when you tried to install the app?

**Comment by dianmsft** [comment]
Closing. Please reactivate if issue is happening again and provide the asked information above.
