### ISSUE TITLE
XML Example not working

### ISSUE THREAD

**Issue by bergerpascal** [MicrosoftDocs/msix-docs#259]
when i copy the xml example to notepad and save it as *.xml i get errors.
There seams to be an issue with the space characters used in the example.
When i delete the spaces and create new ones it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2317a87f-90c3-7756-7fe3-1c54c2b4b3be
* Version Independent ID: 0757751f-bfb5-fe20-45b5-c202889bc1d3
* Content: [MSIX Shared Package Container - MSIX](https://docs.microsoft.com/en-us/windows/msix/manage/shared-package-container)
* Content Source: [msix-src/manage/shared-package-container.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/manage/shared-package-container.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by bergerpascal** [comment]
i realized that i also had to recreate all the line breaks, otherwise i could not use the example with the add command

**Comment by dianmsft** [comment]
Thanks for posted this. We updated the documented accordingly.
