### ISSUE TITLE
Missing UWP information

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/msix-docs#26]
This page says "Use the MSIX packaging tool to create an MSIX package for any Windows app, old or new" But there is no mention of UWP? Is this just a really weird oversite that someone didn't think UWP was a Windows app or is something else going on here? I'm trying to understand packages, but it's difficult if you don't include the primary modern platform for Windows desktop development.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91be9c0-26f6-d263-099d-e58df9eee583
* Version Independent ID: 31f6e0f8-3951-9c04-f1c4-619a9c07a5fa
* Content: [What is MSIX? - MSIX](https://docs.microsoft.com/en-us/windows/msix/overview)
* Content Source: [msix-src/overview.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/overview.md)
* Product: **msix**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by jvintzel** [comment]
Good feedback.  We will get it updated.  All of UWP was evolved into MSIX, plus the items mentioned in the overview.  So if you are UWP you are ahead of the game.  We will add a reference.

**Comment by Gavin-Williams** [comment]
Great, thanks. It's very easy to get confused and frustrated when not familiar with the technology and pathways are not clearly presented.

**Comment by dianmsft** [comment]
We've updated the relevant UWP documentation with MSIX
