### ISSUE TITLE
Didn't help at all. 

### ISSUE THREAD

**Issue by rogerms** [MicrosoftDocs/msix-docs#261]
[Enter feedback here]
Had a problem re-submitting app to the store but this page didn't help at all. You need instruction on how create certificates using Visual Studio and how to align this cert with the App Store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e95ba48-8d07-d390-d49b-801d70730bae
* Version Independent ID: 047d2736-f14e-610c-7396-89d2eae0f9cc
* Content: [Create a certificate for package signing - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing)
* Content Source: [msix-src/package/create-certificate-package-signing.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/create-certificate-package-signing.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by samiranshah** [comment]
Hi @rogerms, the page you pointed to is under the 'Package from the command line' section. Does this page help? https://docs.microsoft.com/windows/msix/package/packaging-uwp-apps

**Comment by samiranshah** [comment]
Closing this for now. Please reopen if needed.
