### ISSUE TITLE
(Request) Add instructions how to change packaged app icons (assets)

### ISSUE THREAD

**Issue by jebeld17** [MicrosoftDocs/msix-docs#27]
Please add an instructional page under the MSIX Packaging Tool on how to edit and change app assets (tile icons) both during the initial packaging process and how to edit after the MSIX has already been generated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95dd77e9-0c0a-3d24-8e7e-d8f32ecd36b0
* Version Independent ID: 84f5e738-9f68-cfb3-68e8-abed3d5f0182
* Content: [MSIX Packaging Tool Overview - MSIX](https://docs.microsoft.com/en-us/windows/msix/mpt-overview#feedback)
* Content Source: [msix-src/mpt-overview.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/mpt-overview.md)
* Product: **msix**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by dianmsft** [comment]
Information added to update icons in MSIX Packaging Tool.

**Comment by jebeld17** [comment]
> Information added to update icons in MSIX Packaging Tool.

I haven't seen these changes and I think I have the latest version of the packaging tool.

**Comment by mcleanbyron** [comment]
The added information is in this article: https://docs.microsoft.com/en-us/windows/msix/packaging-tool/edit-icons-and-assets.
