### ISSUE TITLE
uiAccess=true is supported in MSIX

### ISSUE THREAD

**Issue by EHO-makai** [MicrosoftDocs/msix-docs#273]
This combination is supported for MSIX packaging.  

<Capabilities>
    <rescap:Capability Name="runFullTrust" />
    <rescap:Capability Name="uiAccess" />
</Capabilities>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12379f43-c827-669f-6aeb-4b4d8650cfdf
* Version Independent ID: fadedb99-8dfe-7371-105a-2944bc8d9766
* Content: [Prepare to package a desktop application (MSIX) - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-prepare)
* Content Source: [msix-src/desktop/desktop-to-uwp-prepare.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-prepare.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by anarvekar-msft** [comment]
@EHO-makai thank you for your comment, I can take care of updating the docs accordingly
