### ISSUE TITLE
MSIX and Forced Provisioning - more information needed

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/msix-docs#275]
This page: https://docs.microsoft.com/en-us/windows/msix/supported-platforms mentions that "Forced Provisioning" is supported as of Windows version 2004.  Can you please provide additional documentation to help explain what “Forced Provisioning” is, how to configure it and how it relates to MSIX.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95b83f04-01b6-c494-1e2a-dcddecaa7dc8
* Version Independent ID: 758db7a1-fd48-56fc-1e82-0fbd7ad3f7dc
* Content: [Supported platforms - MSIX](https://docs.microsoft.com/en-us/windows/msix/supported-platforms)
* Content Source: [msix-src/supported-platforms.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/supported-platforms.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by anarvekar-msft** [comment]
Hi @mjfusa, I think this post might be able to answer your question: https://techcommunity.microsoft.com/t5/msix-deployment/machine-wide-package-provisioning-install-for-all-users/m-p/1766287

The [PackageManager API](https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.provisionpackageforallusersasync?view=winrt-19041) can be used to force the provisioning of your MSIX app package to your devices, making it accessible to all users.

**Comment by mjfusa** [comment]
Thanks @anarvekar-msft. I understand it, if an app has been provisioned and then the app is removed, the app is not brought back with an update.  Force provisioning means that if an administrator re-provisions the app it will be reinstalled for all users.  
I was hoping the docs could be updated with this information.

**Comment by anarvekar-msft** [comment]
@mjfusa thank you for the feedback, that is a good point. I can work on updating the docs accordingly.
