### ISSUE TITLE
Issue with the 20H2 CAB file

### ISSUE THREAD

**Issue by umarlatif-lab** [MicrosoftDocs/msix-docs#276]
The link to the cab file for 20H2 - it's a bad cab file because the certificate is not there, there is an error when trying to install offline with this cab because of this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39e02e6d-02b2-fc96-2ef2-ae27d1d60ae8
* Version Independent ID: ce70da72-0526-53e1-f005-9f64641ed286
* Content: [Using the MSIX Packaging Tool in a disconnected environment - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/disconnected-environment)
* Content Source: [msix-src/packaging-tool/disconnected-environment.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/disconnected-environment.md)
* Product: **msix**
* GitHub Login: @sharlaakers
* Microsoft Alias: **shakers**

**Comment by sharlaakers** [comment]
Hi, the documentation has now been updated with a cab file with a proper certificate.
