### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by bergerpascal** [MicrosoftDocs/msix-docs#279]
in the example there are some mistakes:
the space (between AppSharedPackageContainer  and Name) in this line is not a correct space and makes the xml fail to add:
<AppSharedPackageContainer Name="ContosoContainer"> 

The following line misses a  " at the end bevor the /:
  <PackageFamily Name="Contoso.MainApp_8wekyb3d8bbwe/> 

i attached a working version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2317a87f-90c3-7756-7fe3-1c54c2b4b3be
* Version Independent ID: 0757751f-bfb5-fe20-45b5-c202889bc1d3
* Content: [MSIX Shared Package Container - MSIX](https://docs.microsoft.com/en-us/windows/msix/manage/shared-package-container?source=docs)
* Content Source: [msix-src/manage/shared-package-container.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/manage/shared-package-container.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar*
[Correct.txt](https://github.com/MicrosoftDocs/msix-docs/files/7627278/Correct.txt)
*

**Comment by anarvekar-msft** [comment]
Resolved
