### ISSUE TITLE
Link to "COM Server and OLE Document support for Desktop Bridge" is dead.

### ISSUE THREAD

**Issue by aruproy14** [MicrosoftDocs/msix-docs#28]
The link redirects to https://blogs.windows.com/windowsdeveloper/. I looked at this page two weeks ago.

There is no up to date documentation on how to use COM classes in a desktop bridge app (and no information about using the package manifest to register app-specific COM server classes in the registry).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12379f43-c827-669f-6aeb-4b4d8650cfdf
* Version Independent ID: fadedb99-8dfe-7371-105a-2944bc8d9766
* Content: [Prepare to package a desktop application (Desktop Bridge) - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-prepare#feedback)
* Content Source: [msix-src/desktop/desktop-to-uwp-prepare.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-prepare.md)
* Product: **msix**
* GitHub Login: @mcleanbyron

**Comment by mcleanbyron** [comment]
Thanks for reporting this broken link. This link should point to https://blogs.windows.com/windowsdeveloper/2017/04/13/com-server-ole-document-support-desktop-bridge. I am fixing the error now and the corrected link should be live in the docs shortly.
