### ISSUE TITLE
A lot of MSIX limitations are missing from the documentation 

### ISSUE THREAD

**Issue by TOKN2** [MicrosoftDocs/msix-docs#280]
[Enter feedback here]

There are a lot more MSIX limitations that can be viewed in https://techcommunity.microsoft.com/t5/msix/ct-p/MSIX , but this documentation do not cover them. Could you please update this page with all known limitation so that developers and application packager can be more ready and protected when choosing to go with MSIX technology?

Feel free to reach out to me if you need any help.

Thank you! 
Toms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90047125-ebec-eb94-720b-d54c967b5882
* Version Independent ID: d9bf0abd-cac2-6311-9585-4a3893bd406c
* Content: [Know your installer - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/know-your-installer)
* Content Source: [msix-src/packaging-tool/know-your-installer.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/know-your-installer.md)
* Product: **msix**
* GitHub Login: @sharlaakers
* Microsoft Alias: **shakers**

**Comment by anarvekar-msft** [comment]
Thank you for your question. We're constantly updating our documentation. Is there a specific limitation(s) that you had in mind?

**Comment by TOKN2** [comment]
Yes, I have 13 specific MSIX limitations in my mind that would be useful to see in one place somewhere in the Microsoft documentation as these limitations can completely stop developer path towards MSIX technology and developers want to see them in one place that is clear and understandable.

Here is the list of MSIX limitations we have gathered and as there is no other place on the internet to see the whole list we are continuing to update it as best we can. 

Maybe there is a reason why these limitations are not listed under "Know your installer - MSIX" section?
As you can see from the our list the source of the limitations often comes from YouTube or MSIX community forum that is not ok and we would like to set reference of MSIX limitation to Microsoft documentation. always.

https://www.masterpackager.com/blog/msix-limitations

**Comment by anarvekar-msft** [comment]
@TOKN2  thank you for your feedback and this info. The docs can be updated to reflect this information.
