### ISSUE TITLE
arm/arm64

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/msix-docs#281]
[Enter feedback here]
arm and arm64 versions of the tool are now shipped and this page should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36fa5c17-6f3f-d941-6148-65703136a94f
* Version Independent ID: c64136ad-cc7e-8cff-bf46-fb4d2c908149
* Content: [Create an app package with the MakeAppx.exe tool - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/create-app-package-with-makeappx-tool)
* Content Source: [msix-src/package/create-app-package-with-makeappx-tool.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/create-app-package-with-makeappx-tool.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by anarvekar-msft** [comment]
docs are updated with arm/arm64 paths
