### ISSUE TITLE
The ms-appinstaller protocol has been disabled.

### ISSUE THREAD

**Issue by billvenhaus** [MicrosoftDocs/msix-docs#282]
I see that a very short note has been added to the docs mentioning the error. But it doesn't explain why this is happening or how to enable it. It's worked great in the past so I'm not sure what's changed.

Can you please expand on the note to give us that were using this feature more information?
https://docs.microsoft.com/en-us/windows/msix/app-installer/installing-windows10-apps-web

_The ms-appinstaller protocol has been disabled. Please ask the vendor to update the weblink. For more information go to aka.ms/ms-appinstaller-disabled_

<img width="489" alt="appinstaller" src="https://user-images.githubusercontent.com/6692379/146057156-9809f581-ab7d-40cf-9901-5facd0f663ff.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0414d22b-2b74-000f-9d7b-47f6dcb0e45e
* Version Independent ID: 0e72ec33-b8ad-af27-bcb9-16a45936e2a1
* Content: [Installing Windows 10 apps from a web page - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/installing-windows10-apps-web)
* Content Source: [msix-src/app-installer/installing-windows10-apps-web.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/installing-windows10-apps-web.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by anarvekar-msft** [comment]
Hi @billvenhaus thank you for your question. We removed the ms-appinstaller custom scheme due to a security vulnerability. We do intend to bring this back, and are working on it. For now, you can just update the link to be like this:

`<html>
    <body>
        <h1> MyApp Web Page </h1>
        <a href="http://mywebservice.azureedge.net/HubApp.msix"> Install app package </a>
        <a href="http://mywebservice.azureedge.net/HubAppBundle.msixbundle"> Install app bundle  </a>
        <a href="http://mywebservice.azureedge.net/HubAppSet.appinstaller"> Install related set </a>
    </body>
</html>`

**Comment by billvenhaus** [comment]
Thanks, that worked! Maybe not quite as nice as before since it requires an extra click from the user, but it's simple enough:)
