### ISSUE TITLE
The ms-appinstaller protocol has been disabled

### ISSUE THREAD

**Issue by FixRM** [MicrosoftDocs/msix-docs#283]
What do you mean by "The ms-appinstaller protocol has been disabled" and "Please update the link on the website so that the entire package will be downloaded."? What link should I update to what? All samples in the article start with ms-appinstaller protocol.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0414d22b-2b74-000f-9d7b-47f6dcb0e45e
* Version Independent ID: 0e72ec33-b8ad-af27-bcb9-16a45936e2a1
* Content: [Installing Windows 10 apps from a web page - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/installing-windows10-apps-web)
* Content Source: [msix-src/app-installer/installing-windows10-apps-web.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/installing-windows10-apps-web.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by BlazorDashboard** [comment]
![Screenshot 2021-12-16 154932](https://user-images.githubusercontent.com/43870883/146330330-3e3d14c4-ae36-436b-ac09-f2bb9d4e51c7.png)

I am getting the same error.

Test Link:
https://www.barcoderesource.com/testdownload/

Previously in the same link above I am getting the following:

https://github.com/MicrosoftDocs/msix-docs/issues/277

**Comment by mashbrno** [comment]
Don't know why the protocol is disabled, but can you please update the `index.html` generator so the `Get the app` button just downloads the App Installer file? Now I'm using this workaround:

``` pwsh
(Get-Content -Path AppPackages\index.html -Raw) -replace "href='ms-appinstaller:?source=", 'href=' | Set-Content -Path AppPackages\index.html
```

**Comment by anarvekar-msft** [comment]
We removed the ms-appinstaller custom scheme due to a security vulnerability. We do intend to bring this back, and are working on it. For now, you can update the link on your website by removing 'ms-appinstaller:?source='


<html>
    <body>
        <h1> MyApp Web Page </h1>
        <a href="http://mywebservice.azureedge.net/HubApp.msix"> Install app package </a>
        <a href="http://mywebservice.azureedge.net/HubAppBundle.msixbundle"> Install app bundle  </a>
        <a href="http://mywebservice.azureedge.net/HubAppSet.appinstaller"> Install related set </a>
    </body>
</html>

**Comment by FixRM** [comment]
Thanks, @anarvekar-msft. We will need to install windows updates to get protocol enabled again?

Do we need to have AppInstaller app installed (or developer mode enabled) on target machines to use this workaround? Will auto update work for apps installed without `ms-appinstaller` scheme?

**Comment by nbevans** [comment]
The protocol being disabled has really messed us up. Our app would initiate the ms-appinstaller protocol via a Notification Toast message. The user could then click a button which would activate the protocol. But now when we push out our next update - this method won't work and the user will be presented with a nasty error message.

Why couldn't the App Installer presented a good UX for this instead? It would have been so easy to show the Hyperlink to the .appinstaller file and make this clickable by the user in App Installer. This could have then launched in their web browser as a file download. Thus not completely breaking everyone's app which relied on this protocol to "just work".

**Comment by dianmsft** [comment]
We posted a blog post describing this issue. https://techcommunity.microsoft.com/t5/windows-it-pro-blog/disabling-the-msix-ms-appinstaller-protocol-handler/ba-p/3119479 
We'll be providing updates about enabling the feature and next steps there.

**Comment by yaichenbaum** [comment]
> We removed the ms-appinstaller custom scheme due to a security vulnerability. We do intend to bring this back, and are working on it. For now, you can update the link on your website by removing 'ms-appinstaller:?source='
> 
> <img alt="image" width="595" src="https://user-images.githubusercontent.com/84478144/148301213-7c9d36b0-ffed-44cd-ab6e-02526d183170.png">

@dianmsft @anarvekar-msft will the protocol be enabled again? This "workaround" doesn't support [passing parameters](https://docs.microsoft.com/en-us/windows/msix/app-installer/install-parameters#add-your-custom-activation-protocol-and-parameters-to-the-installation-uri) to AppInstaller which is one of our requirements for using AppInstaller to deploy our application.
