### ISSUE TITLE
ProcessorArchitecture entry for arm64?

### ISSUE THREAD

**Issue by NickeManarin** [MicrosoftDocs/msix-docs#286]
Hi, reading the page, I see that the `ProcessorArchitecture ` can be set to x86 and x64. 
How about arm64?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6411665a-440a-ff7c-046f-20f95b023e95
* Version Independent ID: 59530df8-e40f-e016-eac8-266ce7c43b35
* Content: [Package an application manually (Desktop Bridge) - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-manual-conversion)
* Content Source: [msix-src/desktop/desktop-to-uwp-manual-conversion.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-manual-conversion.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by dianmsft** [comment]
Thanks for pointing this out. The docs are updated now.

**Comment by NickeManarin** [comment]
Great!
