### ISSUE TITLE
Missing important parameter AzureSignTool

### ISSUE THREAD

**Issue by PlottingPanthera** [MicrosoftDocs/msix-docs#287]
Just a couple of items:
In order to complete the AzureSignTool as its built, you must give the tenant ID with parameter "-kvt (--azure-key-vault-tenant-id)". Without it, it will fail.

So, the command should now look something like this:
`AzureSignTool sign -kvt "<tenantID>" -kvu "https://contosoexpenses-blog.vault.azure.net/" -kvi "64fae35e-cb84-4b9f-86eb-5170d169316d" -kvs "this-is-the-secret" -kvc "MyCertificate" -tr http://timestamp.digicert.com -v .\MyContosoApp.msix`

Also (suggestion) - should note that these parameters are aliases. If they would like more information on AzureSignTool, run `AzureSignTool  sign --help` or visit the links provided earlier in the article referencing the Open Source project.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f544e5-da81-b214-b1c9-76fa0d024f37
* Version Independent ID: cc9299c0-cbf0-9283-6f81-11ee96c489c0
* Content: [MSIX and CI/CD Pipeline signing with Azure Key Vault - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/cicd-keyvault)
* Content Source: [msix-src/desktop/cicd-keyvault.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/cicd-keyvault.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by PlottingPanthera** [comment]
Any updates on this? Should be a pretty quick fix - or if you have any feedback, please let me know.

**Comment by dianmsft** [comment]
The docs have been updated.
