### ISSUE TITLE
link to 1.7 sdk download broken

### ISSUE THREAD

**Issue by TravisEz13** [MicrosoftDocs/msix-docs#291]
the page says to get the 1.7 SDK on github but there isn't a 1.7 version available on github.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0af3bfaf-c67e-358d-8398-410529e73eae
* Version Independent ID: 3820f16c-f0d9-146f-7808-3659e5ebc186
* Content: [MSIX SDK Release 1.7 release notes - MSIX](https://docs.microsoft.com/en-us/windows/msix/msix-sdk/release-notes/sdk-release-notes-1.7)
* Content Source: [msix-src/msix-sdk/release-notes/sdk-release-notes-1.7.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/msix-sdk/release-notes/sdk-release-notes-1.7.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by anarvekar-msft** [comment]
@TravisEz13 it looks like the link on that page takes you to the release_v1.7 branch on github https://github.com/Microsoft/msix-packaging/tree/release_v1.7

**Comment by anarvekar-msft** [comment]
If you have any additional questions or the above answer did not suffice, plese reopen the issue.
