### ISSUE TITLE
How to pass arguments to executables

### ISSUE THREAD

**Issue by TaylorTWBrown** [MicrosoftDocs/msix-docs#3]
My application's main executable must always be launched with a command line argument. How can I include this in my AppManifest.xml or template?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6faf60e-9fee-7a8d-21d3-a51162e4ea0b
* Version Independent ID: 18d98dc3-5e8e-3fe0-cb87-4d8b6f6ff419
* Content: [create package using command line interface - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/package-conversion-cli)
* Content Source: [msix-src/packaging-tool/package-conversion-cli.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/package-conversion-cli.md)
* Product: **msix**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback on this article. We will review this feedback to see what updates (if any) should be made to the article and respond back to this issue when the updates are complete. In the meantime, to get timely assistance with product questions like this I recommend that you ask on the [MSIX community forums](https://techcommunity.microsoft.com/t5/MSIX/ct-p/MSIX) forums.
