### ISSUE TITLE
Documentation should be updated/expanded for Azure Web Apps that use asp.net core

### ISSUE THREAD

**Issue by jkewley** [MicrosoftDocs/msix-docs#30]
This documentation is specific to .Net framework deployments which use web.config. .Net core has restrictions about what types of content it serves and the setup to make it work differs from above. This article should be updated, or a sibling article should be written to support deploying to Azure web apps which run on .Net Core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bb47a2e-6082-1edf-a69f-e5802743f721
* Version Independent ID: d65ce9f2-0f4f-181f-915a-018001d810b9
* Content: [Distribute a Windows 10 app from an Azure web app - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/web-install-azure)
* Content Source: [msix-src/app-installer/web-install-azure.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/web-install-azure.md)
* Product: **msix**
* GitHub Login: @c-don
* Microsoft Alias: **cdon**

**Comment by dianmsft** [comment]
.NET Core is in public preview but not yet released. We will update the document closer to the release

**Comment by jkewley** [comment]
I'm not sure I understand - .Net core is on version 2.2. My request was to show how to add the MIME types and such for a web site that is built on .Net Core rather than the full framework.

**Comment by dianmsft** [comment]
Apologize, I meant to say .NET Core 3.0 is in public preview. We will do an update to the doc with the latest changes at that time.
