### ISSUE TITLE
The Starter project mentioned is from 2018

### ISSUE THREAD

**Issue by jbennink** [MicrosoftDocs/msix-docs#302]
The starter project mentioned on the docs page is very old and it's web.config lists less settings then the docs page itself. Update the github starter project to be up to date to the docs page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bb47a2e-6082-1edf-a69f-e5802743f721
* Version Independent ID: d65ce9f2-0f4f-181f-915a-018001d810b9
* Content: [Distribute a Windows 10 app from an Azure web app - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/web-install-azure#feedback)
* Content Source: [msix-src/app-installer/web-install-azure.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/app-installer/web-install-azure.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by anarvekar-msft** [comment]
@jbennink thank you for letting us know about this. I have added this to do item to our backlog.
