### ISSUE TITLE
Persistent Identity documents seem incomplete (or feature is broken), and makeappx gives uninformative error message

### ISSUE THREAD

**Issue by fredemmott** [MicrosoftDocs/msix-docs#304]
I followed the instructions, and have an artifacts.txt, artifact.cat (signed and timestamped), and artifact.xml

I am using makeappx from https://www.nuget.org/packages/Microsoft.Windows.SDK.BuildTools/ 10.0.22000.197

I get:

```
Adding publisher bridging file "artifact.xml" and "artifact.cat" to the package.
[118](https://github.com/fredemmott/OpenKneeboard/runs/5505915627?check_suite_focus=true#step:9:118)

[119](https://github.com/fredemmott/OpenKneeboard/runs/5505915627?check_suite_focus=true#step:9:119)
MakeAppx : error: Error info: Unspecified error
[120](https://github.com/fredemmott/OpenKneeboard/runs/5505915627?check_suite_focus=true#step:9:120)

[121](https://github.com/fredemmott/OpenKneeboard/runs/5505915627?check_suite_focus=true#step:9:121)
MakeAppx : error: Package creation failed.
[122](https://github.com/fredemmott/OpenKneeboard/runs/5505915627?check_suite_focus=true#step:9:122)

[123](https://github.com/fredemmott/OpenKneeboard/runs/5505915627?check_suite_focus=true#step:9:123)
MakeAppx : error: 0x80080218 - MakeAppx encountered an error: ID=0x80080218, Error=317)
[124](https://github.com/fredemmott/OpenKneeboard/runs/5505915627?check_suite_focus=true#step:9:124)
Done Adding Additional Store
```

More details:

passing `/pb` to makeappx here: https://github.com/fredemmott/OpenKneeboard/blob/f62238acf2b437245168d11707d67df2b79346c1/.github/workflows/ci.yml#L52

publisher bridging artifacts: https://github.com/fredemmott/OpenKneeboard/tree/8778109a9c1d2e1ecc75fa8ab76117945af73ec8/src/app/artifacts

Windows 10 file properties tells me the .cat signature is valid

Failed CI run: https://github.com/fredemmott/OpenKneeboard/runs/5505915627?check_suite_focus=true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdec14ed-d6ca-9bd6-f0f7-de3b30915aa3
* Version Independent ID: 7ff21924-0311-5f70-7087-4a1669ee8afe
* Content: [MSIX Persistent Identity - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/persistent-identity)
* Content Source: [msix-src/package/persistent-identity.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/package/persistent-identity.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by lechacon** [comment]
The error code is 0x80080218 = APPX_E_INVALID_PUBLISHER_BRIDGING. This means that the artifact(s) xml+cat did not match the manifest.

I looked at the artifact and manifest, and it seems you are using the "new" publisher name in the manifest. The manifest should use the "old" publisher name. Then, the artifact will allow you to sign the package using a certificate with the "new" name. @fredemmott can you give it a try using the other publisher name in the manifest?

@dianmsft I think the docs may not be clear that the manifest should use the "old" publisher. Can we update them to make it clearer?

**Comment by dianmsft** [comment]
In terms of old certificate, the device will need to have the old certificate in order to install the package and use this feature. 

Thank you for the feedback. We'll put this improvement in our backlog.
