### ISSUE TITLE
Dead link to streaming install blog post

### ISSUE THREAD

**Issue by CDFriend** [MicrosoftDocs/msix-docs#307]
That's all you'll need to get your final AppxContentGroupMap.xml ready for your app! There's still more to do before your app is fully ready for the Microsoft Store. For more information on the complete process of adding streaming install to your app, check out [this blog post](https://docs.microsoft.com/en-us/windows/msix/).

"This blog post" currently links to the documentation root for MSIX - which blog post should it be linking to? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bbe9858-31e0-ecf5-0c92-f1e4fd2060c1
* Version Independent ID: 3bff02ac-7056-080c-ae1b-957465da8d59
* Content: [Create and convert a source content group map - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/create-cgm)
* Content Source: [msix-src/package/create-cgm.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/package/create-cgm.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by anarvekar-msft** [comment]
It appears that blog post isn't available anymore. We removed the broken link from the page. Thank you for your feedback.
