### ISSUE TITLE
.NET requirements are incorrect (>= 4.6.1, not >= 4.6.2, and only for the entry executable)

### ISSUE THREAD

**Issue by jonthysell** [MicrosoftDocs/msix-docs#31]
The actual requirements to package and publish a desktop app using Desktop Bridge are:

- The entry executable must target 4.6.1 or later.
- Other .NET assemblies just need to be able to run on .NET 4.6.1. They can actually target any version less than or equal to what the the entry executable targets.

Originally opened an issue here: https://github.com/MicrosoftDocs/windows-uwp/issues/1670 but it got closed. Hopefully this issue will be more tightly bound to this page, so it gets fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12379f43-c827-669f-6aeb-4b4d8650cfdf
* Version Independent ID: fadedb99-8dfe-7371-105a-2944bc8d9766
* Content: [Prepare to package a desktop application (Desktop Bridge) - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-prepare#feedback)
* Content Source: [msix-src/desktop/desktop-to-uwp-prepare.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-prepare.md)
* Product: **msix**
* GitHub Login: @mcleanbyron

**Comment by mcleanbyron** [comment]
Thanks for your feedback. After following up with the engineering team, we have made some changes to the .NET version guidance on this page to include statements about 4.6.1 and earlier.

**Comment by Lukas34** [comment]
It says that it "requires a version of the .NET Framework earlier than 4.6.2" but in the next sentence, it says that "we recommend that your application target .NET Framework 4.6.2 or later." which makes it unclear if you should target a .NET Framework earlier or later than 4.6.2.
