### ISSUE TITLE
reset-appxpackage does not exist

### ISSUE THREAD

**Issue by dquint57** [MicrosoftDocs/msix-docs#316]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd14364-1f66-9a21-a03a-d00434cef076
* Version Independent ID: f282b99e-d647-167c-d15e-7d426d7e09ad
* Content: [Reset or Repair MSIX Apps - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/managing-your-msix-reset-and-repair)
* Content Source: [msix-src/desktop/managing-your-msix-reset-and-repair.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/desktop/managing-your-msix-reset-and-repair.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by sharlaakers** [comment]
Hi, this command does exist. If you were unable to use this command, please let us know so we can investigate. 

Best,
Sharla
