### ISSUE TITLE
Broken links.

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/msix-docs#317]
The links on this page for the two REDIST installers is no longer valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0faa459-4275-5e3f-3b8a-a5933267a86a
* Version Independent ID: 11ac9620-4534-da7d-802f-797bbfc19483
* Content: [MSIX Toolkit - MSIX](https://docs.microsoft.com/en-us/windows/msix/toolkit/msix-toolkit-overview)
* Content Source: [msix-src/toolkit/msix-toolkit-overview.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/toolkit/msix-toolkit-overview.md)
* Product: **msix**
* GitHub Login: @RDMacLachlan
* Microsoft Alias: **romaclac**

**Comment by anarvekar-msft** [comment]
Links are updated, thank you for the feedback
