### ISSUE TITLE
Old certificate has to be installed on each end-user's machine?

### ISSUE THREAD

**Issue by Baddog240Z** [MicrosoftDocs/msix-docs#318]
"You will still need to install the old certificate (recommended with timestamp) on the machine for the platform to install the package that was signed by the new certificate."

This makes it sound like the old certificate has to be installed on each end-users machine. Is that really the case???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdec14ed-d6ca-9bd6-f0f7-de3b30915aa3
* Version Independent ID: 7ff21924-0311-5f70-7087-4a1669ee8afe
* Content: [MSIX Persistent Identity - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/persistent-identity)
* Content Source: [msix-src/package/persistent-identity.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/package/persistent-identity.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
In order to use this feature and to persist the original package identity that was signed with old certificate, you will need to install the old certificate.
