### ISSUE TITLE
ShowPrompt and UpdateBlocksActivation attributes fail schema validation

### ISSUE THREAD

**Issue by JeroMiya** [MicrosoftDocs/msix-docs#32]
On Windows 1903 (and app's target/min both set to 1903), after adding the ShowPrompt and/or UpdateBlocksActivation attributes to the OnLaunched element, the installer at runtime will fail due to an XML schema validation error stating those attributes are not valid on the OnLaunched element. Are these options deprecated or only valid on preview versions of Windows? https://github.com/MicrosoftDocs/msix-docs/issues/25 states that it was added to the 1809 schema but only implemented in 1903, but in my case it is seemingly neither working/implemented nor in the schema in 1903.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e69e20f-7cfc-aa28-85b8-f2deb8a69873
* Version Independent ID: c3fffd4b-4405-c347-2db8-95c5c0928de5
* Content: [App Installer file update settings - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/update-settings)
* Content Source: [msix-src/app-installer/update-settings.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/update-settings.md)
* Product: **msix**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by Huios** [comment]
Hey @JeroMiya 

Both ShowPrompt and UpdateBlocksActivation require the .appinstallerfile to point to this schema - `xmlns="http://schemas.microsoft.com/appx/appinstaller/2018"`. I'll add a section to the docs to clarify this.

Are you creating the .appinstallerfile from Visual Studio or AppInstaller file builder? The default file  created points to `"http://schemas.microsoft.com/appx/appinstaller/2017"` which needs to be updated to 2018 when you add either ShowPrompt or UpdateBlocksActivation.

Tanaka MSFT
