### ISSUE TITLE
The Debug your Application section is insufficient.  Symbols are not being loaded.

### ISSUE THREAD

**Issue by peterdrier** [MicrosoftDocs/msix-docs#322]
The Debug your Application section is insufficient.  

These instructions don't load the symbols for the attached application, and thus the developer can not set breakpoints or do anything else useful in managed code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ec92f52-df60-93d8-d438-a40f48a3af86
* Version Independent ID: 0fc136c7-ceb0-513d-a033-d3f25e05211c
* Content: [Run, debug, and test an MSIX package - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-debug)
* Content Source: [msix-src/desktop/desktop-to-uwp-debug.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/desktop/desktop-to-uwp-debug.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by anarvekar-msft** [comment]
When you say symbols, what do you mean by that?

**Comment by peterdrier** [comment]
In the context of debugging an application, "symbols" generally means
that which is in the PDB.

--

**Comment by anarvekar-msft** [comment]
Thank you for this feedback @peterdrier , we have made a note to update the docs and are tracking the work internally
