### ISSUE TITLE
wrong word

### ISSUE THREAD

**Issue by stars2022** [MicrosoftDocs/msix-docs#323]
(https://github.com/MicrosoftDocs/msix-docs/tree/main/msix-src/package)/create-app-package-with-makeappx-tool.md
There is a wrong expression in line 28
"ar64" should be"arm64"

**Comment by stars2022** [comment]
> (https://github.com/MicrosoftDocs/msix-docs/tree/main/msix-src/package)/create-app-package-with-makeappx-tool.md There is a wrong in line 28 "ar64" should be"arm64"

**Comment by anarvekar-msft** [comment]
Docs fixed, thank you for the feedback
