### ISSUE TITLE
where is the repo of the "msix packaging tool"?

### ISSUE THREAD

**Issue by rautends** [MicrosoftDocs/msix-docs#324]
Hello,
i don't know where to ask, so i will try it here:
where is the repo of the "msix packaging tool" itself?

Kind Regards,

**Comment by sharlaakers** [comment]
Hi, 
The MSIX Packaging Tool is not open source. You can find documentation on using the MSIX Packaging Tool here: https://docs.microsoft.com/en-us/windows/msix/packaging-tool/tool-overview
