### ISSUE TITLE
Need more clarification on Note "mentioned for Msix package Installer"

### ISSUE THREAD

**Issue by Devanadan** [MicrosoftDocs/msix-docs#328]
Need more clarification on note mentioned in below link, We want to use Msix installer for project, as per mentioned in below note, Is that any specific feature not available or Installer itself not available. Please provide some detailed explanation.

https://docs.microsoft.com/en-us/windows/msix/app-installer/how-to-create-custom-app-installer-ux

Note: "This App Installer feature has been temporarily rolled back and will not work right now. Please check back later for further updates as we plan to bring this feature back."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e23d8ec3-4c72-fe10-55ce-1af1da48d146
* Version Independent ID: e23d8ec3-4c72-fe10-55ce-1af1da48d146
* Content: [How to create a custom App Installer UX - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/how-to-create-custom-app-installer-ux)
* Content Source: [msix-src/app-installer/How-to-create-custom-app-installer-ux.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/app-installer/How-to-create-custom-app-installer-ux.md)
* Product: **msix**
* GitHub Login: @sharlaakers
* Microsoft Alias: **shakers**

**Comment by sharlaakers** [comment]
Hi,

This particular feature (custom App Installer ux) has been rolled back but MSIX and App Installer are still functional and available.
