### ISSUE TITLE
MSIX Packaging Tool Environment: release of the build process

### ISSUE THREAD

**Issue by rautends** [MicrosoftDocs/msix-docs#336]
Hello,
why is the build process of the MSIX Packaging Tool Environment from the Hyper-V Quick Create Gallery ( https://go.microsoft.com/fwlink/?linkid=851584 ) not open source? An unattend.xml for syspreping could be very practical, especially for developers who need to package existing installers (MSI, EXE, ClickOnce, or App-V) and would be versatile for different hypervisor environments. In combination with Packer ( https://www.packer.io/ ), this environment would certainly also be profitable for Azure. Unfortunately, I don't find this approach considered anywhere yet. are there already efforts in this direction?

Kind Regards,

**Comment by anarvekar-msft** [comment]
Thank you for the feedback. We'll look into it for a future release
