### ISSUE TITLE
Broken link for Running MSIX applications on a remote machine

### ISSUE THREAD

**Issue by razaraz** [MicrosoftDocs/msix-docs#338]
In the section titled: "Validate your app package on a remote Windows 10 device", in Step 2, the link for [Run MSIX applications on a remote machine](https://docs.microsoft.com/en-us/visualstudio/debugger/run-windows-store-apps-on-a-remote-machine&preserve-view=true) is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0ca4c24-058f-a798-15a1-6cd3649e45cb
* Version Independent ID: 63dec3d2-273a-a8cc-1a40-e5af423e856b
* Content: [Packaging MSIX apps - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps#validate-your-app-package)
* Content Source: [msix-src/package/packaging-uwp-apps.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/package/packaging-uwp-apps.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by anarvekar-msft** [comment]
Resolved
