### ISSUE TITLE
Cannot view video in UWP packaging article

### ISSUE THREAD

**Issue by ko-vasilev** [MicrosoftDocs/msix-docs#340]
At the end of the article (Additional resources) the Video cannot be viewed and says that "This video is private".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bead27ac-8ed3-9886-26e2-47f49ea1efc0
* Version Independent ID: f354c6b6-b2e0-e070-dd0d-c3452a5635fb
* Content: [Package a desktop app from source code using Visual Studio - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net)
* Content Source: [msix-src/desktop/desktop-to-uwp-packaging-dot-net.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/desktop/desktop-to-uwp-packaging-dot-net.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **tajimha**

**Comment by anarvekar-msft** [comment]
Thank you for your feedback. Resolved!

**Comment by anarvekar-msft** [comment]
Thank you for your feedback, resolved
