### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by RDMacLachlan** [MicrosoftDocs/msix-docs#341]
Links in this document are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61dbc475-482a-3e2f-b41e-bb9d35d100e5
* Version Independent ID: 93e1b53d-8150-5693-ca85-acb317f1f666
* Content: [Update non-Store published apps from your code - MSIX](https://docs.microsoft.com/en-us/windows/msix/non-store-developer-updates)
* Content Source: [msix-src/non-store-developer-updates.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/non-store-developer-updates.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **diahar**

**Comment by anarvekar-msft** [comment]
Resolved
