### ISSUE TITLE
Does msixpackagingtool deprecate makeappx?

### ISSUE THREAD

**Issue by atrauzzi** [MicrosoftDocs/msix-docs#35]
As the title says...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6faf60e-9fee-7a8d-21d3-a51162e4ea0b
* Version Independent ID: 18d98dc3-5e8e-3fe0-cb87-4d8b6f6ff419
* Content: [Create a package using the command line interface - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/package-conversion-cli)
* Content Source: [msix-src/packaging-tool/package-conversion-cli.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/package-conversion-cli.md)
* Product: **msix**
* GitHub Login: @sharlaakers
* Microsoft Alias: **shakers**

**Comment by sharlaakers** [comment]
No, it does not deprecate makeappx. You can use makeappx to generate MSIX packages as well.

**Comment by atrauzzi** [comment]
Out of curiosity, what's the difference between them?

**Comment by qmatteoq** [comment]
makeappx is the tool which takes care of creating a package starting from a folder which already contains all the files required to compose a MSIX package, like the manifest, the VFS folder, the .dat files with the registry keys, etc. The MSIX Packaging Tool uses it at the end of the process, to generate the package starting from the output of the conversion process. Before doing that, however, it detects all the changes made by the installer to the system and it turns them into a proper MSIX folder structure, which is the what the makeappx alone can't do.
