### ISSUE TITLE
Link to MSIX Core is dead

### ISSUE THREAD

**Issue by jpchow26** [MicrosoftDocs/msix-docs#36]
the link in the top paragraph is 404'd. Probably should be pointing to https://github.com/microsoft/msix-packaging/tree/master/preview/MsixCore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37eced72-23b9-9555-6388-38b996277863
* Version Independent ID: 2d144a55-69a9-b4fe-8891-78a2f72b20d8
* Content: [MSIX Core - MSIX](https://docs.microsoft.com/en-us/windows/msix/msix-sdk/msixcore#feedback)
* Content Source: [msix-src/msix-sdk/msixcore.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/msix-sdk/msixcore.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Updated the link to point to https://github.com/microsoft/msix-packaging/tree/master/preview/MsixCore
