### ISSUE TITLE
MSIX features and supported platforms

### ISSUE THREAD

**Issue by Brandon98SE** [MicrosoftDocs/msix-docs#366]
`LTSC 2021` is listed as `20H2` instead of `21H2` under the `MSIX features and supported platforms` table.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95b83f04-01b6-c494-1e2a-dcddecaa7dc8
* Version Independent ID: 758db7a1-fd48-56fc-1e82-0fbd7ad3f7dc
* Content: [MSIX features and supported platforms - MSIX](https://learn.microsoft.com/en-us/windows/msix/supported-platforms)
* Content Source: [msix-src/supported-platforms.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/supported-platforms.md)
* Product: **windows**
* Technology: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by aniketbanerji** [comment]
Hi Brandon,

This is accurate. 2021 LTSC is 20H2, similar to LTSC 2019, which is 1809.

**Comment by Brandon98SE** [comment]
Hi Aniket,

Please can you double check this. Here are the versions and builds for Windows 10 Enterprise `LTSC`/`LTSB` Editions:

- Version `21H2` / Build `19044` == Windows 10 Enterprise `LTSC 2021`
- Version `1809` / Build `17763` == Windows 10 Enterprise `LTSC 2019`
- Version `1607` / Build `14393` == Windows 10 Enterprise `LTSB 2016`
- Version `1507` / Build `10240` == Windows 10 Enterprise `LTSB 2015`

![image](https://github.com/MicrosoftDocs/msix-docs/assets/61706486/4acaceef-c520-47b3-99b5-e36ec28f85b9)
![image](https://github.com/MicrosoftDocs/msix-docs/assets/61706486/86bca9f4-739e-4774-8f6e-78bd775f337e)
