### ISSUE TITLE
Neutral is not listed

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/msix-docs#367]
Neutral is an architecture option in VS Publish, but I see that it is not listed here. I also read the neutral [isn't supported](https://developercommunity.visualstudio.com/t/Packaging-Project-for-Net-60-WPF-appli/10204051#T-N10243943).

It's weird that a scenario is not supported but presented to the user. What's the deal with Neutral?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d3ebc79-107e-4da3-a69e-2833e4b4891f
* Version Independent ID: bcb79b16-6786-3330-d3d6-052b8391a442
* Content: [App package architectures - MSIX](https://learn.microsoft.com/en-us/windows/msix/package/device-architecture)
* Content Source: [msix-src/package/device-architecture.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/package/device-architecture.md)
* Product: **windows**
* Technology: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by aniketbanerji** [comment]
@MisinformedDNA - You're right, MSIX does not support Neutral.
To your concern - Neutral is still an option on VS to support other formats.
