### ISSUE TITLE
Allow fair use of third-party product names - avoids inconsistent application

### ISSUE THREAD

**Issue by rfreytag** [MicrosoftDocs/msix-docs#369]
Non-deceptive usage of third-party brands with products is fair use by Trademark rules [1]. Furthermore, products supporting third-party products must emphasize their supporting/dependent role as shown by many products in the Microsoft Store that incorporate third party products in their name [2].

Microsoft App Store policy bans product names mentioning third-party products [3]. Currently this rule is inconsistently applied by Microsoft Store app reviewers because it isn't clear. Many apps use third-party products in their names.  

Clearly, either the rule must change or all products breaking this Store policy  require a name change (a bad choice IMO).

Please change Store policy to italicize only the third-party product name in Microsoft Store product titles to clarify they are not part of the actual name. Also require a disclaimer below the product name declaring “<third-party product> is a product of <publisher third-party-publisher-name>”.  See pull request on this document: [https://github.com/MicrosoftDocs/windows-dev-docs/pull/4237](https://github.com/MicrosoftDocs/windows-dev-docs/pull/4237).

References:

1. See point #2 “Nominative fair use permits use of another’s trademark to refer to the trademark owner’s goods and services associated with the mark.” ([https://www.inta.org/fact-sheets/fair-use-of-trademarks-intended-for-a-non-legal-audience/](https://learn.microsoft.com/en-us/answers/questions/1161643/third-party-product-names-banned-in-microsoft-stor))

2. Here are products currently in the Microsoft Store that accurately and fairly use the name of a third-party product (names are in the URLs)…

   * [https://apps.microsoft.com/store/detail/prime-video-for-windows/9P6RC76MSMMJ](https://apps.microsoft.com/store/detail/prime-video-for-windows/9P6RC76MSMMJ)
    * [https://apps.microsoft.com/store/detail/huetro-for-hue/9WZDNCRFJJ3T](https://apps.microsoft.com/store/detail/huetro-for-hue/9WZDNCRFJJ3T)
    * [https://apps.microsoft.com/store/detail/shrestha-files-pro-x-file-explorer-for-windows/9NPNFFSV2HQM](https://apps.microsoft.com/store/detail/shrestha-files-pro-x-file-explorer-for-windows/9NPNFFSV2HQM)
    * [https://apps.microsoft.com/store/detail/media-cutter-for-windows/9NS1ZMCH63P8](https://apps.microsoft.com/store/detail/media-cutter-for-windows/9NS1ZMCH63P8)
    * [https://apps.microsoft.com/store/detail/7zip-for-windows/XPDNKVCX4QD2DC](https://apps.microsoft.com/store/detail/7zip-for-windows/XPDNKVCX4QD2DC)
    * [https://apps.microsoft.com/store/detail/screen-recorder-for-windows-11/9N9CCD41TFT3](https://apps.microsoft.com/store/detail/screen-recorder-for-windows-11/9N9CCD41TFT3)
    * [https://apps.microsoft.com/store/detail/ishtar-commander-for-destiny/9PK2Z4MF5MNS](https://apps.microsoft.com/store/detail/ishtar-commander-for-destiny/9PK2Z4MF5MNS)
    * [https://apps.microsoft.com/store/detail/notepad-for-windows-10/9NBLGGH4W20K](https://apps.microsoft.com/store/detail/notepad-for-windows-10/9NBLGGH4W20K)
    * [https://apps.microsoft.com/store/detail/perfect-flicker-best-client-for-flickr/9NBLGGH5170J](https://apps.microsoft.com/store/detail/perfect-flicker-best-client-for-flickr/9NBLGGH5170J)
    * [https://apps.microsoft.com/store/detail/gin-rummy-deluxe-for-hp/9NBLGGH4XC5C](https://apps.microsoft.com/store/detail/gin-rummy-deluxe-for-hp/9NBLGGH4XC5C)
    * [https://apps.microsoft.com/store/detail/aboards-for-trello/9NBLGGH67DBR](https://apps.microsoft.com/store/detail/aboards-for-trello/9NBLGGH67DBR)
    * [https://apps.microsoft.com/store/detail/screen-recorder-pro-for-win10/9N27GQ6MLS5S](https://apps.microsoft.com/store/detail/screen-recorder-pro-for-win10/9N27GQ6MLS5S)
    * [https://apps.microsoft.com/store/detail/yakuza-6-the-song-of-life-for-windows-10/9N9WWM5JXCBZ](https://apps.microsoft.com/store/detail/yakuza-6-the-song-of-life-for-windows-10/9N9WWM5JXCBZ)
    * [https://apps.microsoft.com/store/detail/unigram%E2%80%94telegram-for-windows/9N97ZCKPD60Q](https://apps.microsoft.com/store/detail/unigram%E2%80%94telegram-for-windows/9N97ZCKPD60Q)
    * [https://apps.microsoft.com/store/detail/oberlo-guide-for-shopify-dropshipers/9N97N185SXM6](https://apps.microsoft.com/store/detail/oberlo-guide-for-shopify-dropshipers/9N97N185SXM6)
    * [https://apps.microsoft.com/store/detail/melosik-music-player-for-windows/9NH759PMH26M](https://apps.microsoft.com/store/detail/melosik-music-player-for-windows/9NH759PMH26M)
    * [https://apps.microsoft.com/store/detail/yakuza-kiwami-for-windows-10/9P40SC5DQ9K0](https://apps.microsoft.com/store/detail/yakuza-kiwami-for-windows-10/9P40SC5DQ9K0)
    * [https://apps.microsoft.com/store/detail/ghost-overlay-for-destiny-2/9P9MC43CJH63](https://apps.microsoft.com/store/detail/ghost-overlay-for-destiny-2/9P9MC43CJH63)
    * [https://apps.microsoft.com/store/detail/lighter-for-philips-hue-nanoleaf-razer-chroma/9N5WFWP4453S](https://apps.microsoft.com/store/detail/lighter-for-philips-hue-nanoleaf-razer-chroma/9N5WFWP4453S)
    * [https://apps.microsoft.com/store/detail/makecode-for-adafruit/9PGZHWSK0PGD](https://apps.microsoft.com/store/detail/makecode-for-adafruit/9PGZHWSK0PGD)
    * [https://apps.microsoft.com/store/detail/cool-screen-recorder-lite-for-windows-10/9N7Q6KFH1WSX](https://apps.microsoft.com/store/detail/cool-screen-recorder-lite-for-windows-10/9N7Q6KFH1WSX)
    * [https://apps.microsoft.com/store/detail/yakuza-5-remastered-for-windows-10/9MVX1V7W5SW8](https://apps.microsoft.com/store/detail/yakuza-5-remastered-for-windows-10/9MVX1V7W5SW8)
    * [https://apps.microsoft.com/store/detail/for-asus-ballstrike/9WZDNCRFJCQF](https://apps.microsoft.com/store/detail/for-asus-ballstrike/9WZDNCRFJCQF)
    * [https://apps.microsoft.com/store/detail/pdf-editor-for-windows/9NR56JPFM2W2](https://apps.microsoft.com/store/detail/pdf-editor-for-windows/9NR56JPFM2W2)
    * [https://apps.microsoft.com/store/detail/jewel-star-for-hp/9NBLGGH4X9ZJ](https://apps.microsoft.com/store/detail/jewel-star-for-hp/9NBLGGH4X9ZJ)
    * [https://apps.microsoft.com/store/detail/mrremote-for-kodi/9NBLGGH4QVKX](https://apps.microsoft.com/store/detail/mrremote-for-kodi/9NBLGGH4QVKX)
    * [https://apps.microsoft.com/store/detail/for-asus-nightmares-from-the-deep-the-cursed-heart-free/9WZDNCRDHJD4](https://apps.microsoft.com/store/detail/for-asus-nightmares-from-the-deep-the-cursed-heart-free/9WZDNCRDHJD4)
    * [https://apps.microsoft.com/store/detail/importer-for-media-pro/9PDH7CX56SH8](https://apps.microsoft.com/store/detail/importer-for-media-pro/9PDH7CX56SH8)
    * [https://apps.microsoft.com/store/detail/tutor-for-binance-app/9MWKV2456ZSW](https://apps.microsoft.com/store/detail/tutor-for-binance-app/9MWKV2456ZSW)
    * [https://apps.microsoft.com/store/detail/document-editor-pro-for-windows/9PJP8SS73VQ3](https://apps.microsoft.com/store/detail/document-editor-pro-for-windows/9PJP8SS73VQ3)
    * [https://apps.microsoft.com/store/detail/movie-maker-video-editor-for-windows/9NKG9K8F013P](https://apps.microsoft.com/store/detail/movie-maker-video-editor-for-windows/9NKG9K8F013P)
    * [https://apps.microsoft.com/store/detail/final-fantasy-xv-windows-edition-playable-demo/9PNKZMQZB3B6](https://apps.microsoft.com/store/detail/final-fantasy-xv-windows-edition-playable-demo/9PNKZMQZB3B6)
    * [https://apps.microsoft.com/store/detail/final-fantasy-xv-windows-edition/9NR0N2LZ6TC5](https://apps.microsoft.com/store/detail/final-fantasy-xv-windows-edition/9NR0N2LZ6TC5)
    * [https://apps.microsoft.com/store/detail/ford-f150-raptor-xbox-one-x-edition/9MZSW3LCHMBD](https://apps.microsoft.com/store/detail/ford-f150-raptor-xbox-one-x-edition/9MZSW3LCHMBD)
    * [https://apps.microsoft.com/store/detail/gears-of-war-ultimate-edition-for-windows-10/9NBLGGH3SHM5](https://apps.microsoft.com/store/detail/gears-of-war-ultimate-edition-for-windows-10/9NBLGGH3SHM5)
    * [https://apps.microsoft.com/store/detail/cities-skylines-windows-10-edition/9NWVC7XP3PFD](https://apps.microsoft.com/store/detail/cities-skylines-windows-10-edition/9NWVC7XP3PFD)
    * [https://apps.microsoft.com/store/detail/far-changing-tides-windows-edition/9MT3D7Z4NWDV](https://apps.microsoft.com/store/detail/far-changing-tides-windows-edition/9MT3D7Z4NWDV)
    * [https://apps.microsoft.com/store/detail/corel-painter-microsoft-store-edition/9NZ9S9NFHMNW](https://apps.microsoft.com/store/detail/corel-painter-microsoft-store-edition/9NZ9S9NFHMNW)

3.  See second bullet under 10.1 “Your product must not use a name, images, or any other metadata that is the same as that of other products unless the product is also published by you.” ([https://learn.microsoft.com/en-us/windows/apps/publish/store-policies#101-distinct-function--value-accurate-representation](https://learn.microsoft.com/en-us/answers/questions/1161643/third-party-product-names-banned-in-microsoft-stor))

**Comment by aniketbanerji** [comment]
Hi @rfreytag, Store docs may be a good place to post this.
