### ISSUE TITLE
Incompatibility between this page and the .appinstaller schema docs

### ISSUE THREAD

**Issue by julienshepherd** [MicrosoftDocs/msix-docs#37]
In the docs the UpdateSettings element can contain both OnLaunch and AutomaticBackgroundTask. The problem is Visual Studio allows you to select either one of the two. 

So if you select check every hour, the .appinstaller will contain the OnLaunch element. If you later add the AutomaticBackgroundTask to the published .appinstaller, no user will be able to install your app. They will receive this error:

Deployment Add operation with target volume C: on Package [packageNameAndVersion]_neutral_~_vqex3v0c1enw0 from:  ([packagename].appxbundle)  failed with error 0x80070005. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930536bd-243e-3024-1c8d-b352384a2718
* Version Independent ID: 518c2651-df80-73fb-f28c-a48e8dde863d
* Content: [Create an App Installer file with Visual Studio - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/create-appinstallerfile-vs#feedback)
* Content Source: [msix-src/app-installer/create-appinstallerfile-vs.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/create-appinstallerfile-vs.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by Huios** [comment]
Hey Julien,

I tried to reproduce the issue you mentioned but wasn't able to, my app installed fine when I had both the OnLaunch and AutomaticBackgroundTask elements in <UpdateSettings>
This is what I did:

- I created an App Package in VS
- I selected the "Check For Updates every 1 Hour" Option
- VS created a .appinstaller file
- I modified it and added <AutomaticBackgroundTask/> to the Update Settings.
- I installed the package using the .appinstallerfile which worked fine

My app package has MinVersion="10.0.17763.0" and MaxVersionTested="10.0.18362.0". What are the values in your package and what Windows version were you trying to install on? 

Here is what my .appinstaller file looks like:

`<?xml version="1.0" encoding="utf-8"?>
<AppInstaller
	Uri="<AppInstallerFileLocation>\AppInstaller_TestApp\AppInstaller_TestPkg\AppPackages\AppInstaller_TestPkg_x64.appinstaller"
	Version="1.0.1.0" xmlns="http://schemas.microsoft.com/appx/appinstaller/2017/2">
	<MainPackage
		Name="MyApp"
		Version="1.0.1.0"
		Publisher="CN=MyPublisher"
		Uri="<PackageLocation>/AppInstaller_TestPkg_1.0.1.0_x64_Debug_Test/AppInstaller_TestPkg_1.0.1.0_x64_Debug.msix"
		ProcessorArchitecture="x64" />
	<UpdateSettings>
		<OnLaunch
			HoursBetweenUpdateChecks="1" />
			<AutomaticBackgroundTask/>
	</UpdateSettings>
</AppInstaller>`

**Comment by driesvandamme** [comment]
@Huios Can you check if the update works as well?

1) Host the appinstaller on an webserver (and open it with HTTP).
2) Install the default version of the app (with appinstaller)
4) Generate a new version of the app (with appinstaller version number +1)
3) Then go to the http page and install the update

Does this test work as well for you?

**Comment by julienshepherd** [comment]
> 
> 
> Hey Julien,
> 
> I tried to reproduce the issue you mentioned but wasn't able to, my app installed fine when I had both the OnLaunch and AutomaticBackgroundTask elements in
> This is what I did:
> 
>     * I created an App Package in VS
> 
>     * I selected the "Check For Updates every 1 Hour" Option
> 
>     * VS created a .appinstaller file
> 
>     * I modified it and added  to the Update Settings.
> 
>     * I installed the package using the .appinstallerfile which worked fine
> 
> 
> My app package has MinVersion="10.0.17763.0" and MaxVersionTested="10.0.18362.0". What are the values in your package and what Windows version were you trying to install on?
> 
> Here is what my .appinstaller file looks like:
> 
> `<?xml version="1.0" encoding="utf-8"?> <AppInstaller Uri="<AppInstallerFileLocation>\AppInstaller_TestApp\AppInstaller_TestPkg\AppPackages\AppInstaller_TestPkg_x64.appinstaller" Version="1.0.1.0" xmlns="http://schemas.microsoft.com/appx/appinstaller/2017/2"> <MainPackage Name="MyApp" Version="1.0.1.0" Publisher="CN=MyPublisher" Uri="<PackageLocation>/AppInstaller_TestPkg_1.0.1.0_x64_Debug_Test/AppInstaller_TestPkg_1.0.1.0_x64_Debug.msix" ProcessorArchitecture="x64" /> <UpdateSettings> <OnLaunch HoursBetweenUpdateChecks="1" /> <AutomaticBackgroundTask/> </UpdateSettings> </AppInstaller>`
> 
> Tanaka MSFT

My AppInstaller has this:
```
<?xml version="1.0" encoding="utf-8"?>
<AppInstaller xmlns="http://schemas.microsoft.com/appx/appinstaller/2017"
              Version="1.0.0.16"
              Uri="MyPrivateUri">
              
  <MainBundle Name="MyPrivatePackageName" 
	      Publisher="CN=CompanyName, O=CompanyName, L=CompanyCity, C=CompanyCountryCode"
	      Version="2019.909.1235.0"
              Uri="MyPrivateAppxBundleUri" />

  <UpdateSettings>
      <OnLaunch />
      <AutomaticBackgroundTask />
  </UpdateSettings>
</AppInstaller>
```
The app targets 1803, the minimum target is also 1803.

**Comment by driesvandamme** [comment]
@julienshepherd - Did you try an update of a higher version? Or just an install?

**Comment by julienshepherd** [comment]
> 
> 
> @julienshepherd - Did you try an update of a higher version? Or just an install?

I tried both.

**Comment by Huios** [comment]
@julienshepherd 

Thanks for posting your AppInstallerfile. I think the issue is due to the AppInstaller schema you're referencing in your file.
According to the docs [here]( https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-automatic-background-task) **AutomaticBackgroundTask** requires the xmlns="http://schemas.microsoft.com/appx/appinstaller/**2017/2**" namespace. The one in your current AppInstallerfile is  xmlns="http://schemas.microsoft.com/appx/appinstaller/**2017**"

We have AppInstallerFileBuilder tool that can help with creating a file with the right namespace schema for different update settings. You can check it out [here](https://github.com/microsoft/MSIX-Toolkit/tree/master/AppInstallerFileBuilder).

I hope this helps.

Tanaka MSFT
