### ISSUE TITLE
Downloaded FOD CABs file name can be malformed warning

### ISSUE THREAD

**Issue by rileyz** [MicrosoftDocs/msix-docs#375]
Brower: Edge 110

**Issue**
Download the FOD .cab file for Windows 10, version 2004, x64, as stated in the text and link. The URL is below:
https://download.microsoft.com/download/4/c/7/4c79bf31-946c-444a-bc5f-61398d3b0a76/Msix-PackagingTool-Driver-Package~31bf3856ad364e35~amd64~~.cab

When downloading the cab from URL, Edge (maybe other browsers also) malforms the filename on save, the ~ symbol and converted to a _ symbol. This impacts the cab file and Dism is unable to work.

**Solution**
Add warning on document to ensure file name is as expected. Check that file name is correct with ~ symbols.
Msix-PackagingTool-Driver-Package~31bf3856ad364e35~amd64~~.cab
*not sure why the numbers have a strike through in the link, please ignore.

And not
Msix-PackagingTool-Driver-Package_31bf3856ad364e35_amd64__.cab

**Comment by aniketbanerji** [comment]
Hi @rileyz,

We have found that Dism command works even with '_' symbols, if the file path is correctly specified (with _ and '.cab' extension)
