### ISSUE TITLE
Add WinGet instructions for installing the MSIX Packaging Tool

### ISSUE THREAD

**Issue by denelon** [MicrosoftDocs/msix-docs#376]
[Enter feedback here]
Add:
`winget install "MSIX Packaging Tool"`

Bonus points if you can copy-paste the command.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95dd77e9-0c0a-3d24-8e7e-d8f32ecd36b0
* Version Independent ID: 84f5e738-9f68-cfb3-68e8-abed3d5f0182
* Content: [MSIX Packaging Tool Overview - MSIX](https://learn.microsoft.com/en-us/windows/msix/packaging-tool/tool-overview)
* Content Source: [msix-src/packaging-tool/tool-overview.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/packaging-tool/tool-overview.md)
* Product: **windows**
* Technology: **msix**
* GitHub Login: @sharlaakers
* Microsoft Alias: **shakers**

**Comment by aniketbanerji** [comment]
Done!
