### ISSUE TITLE
What determines if .appx or .msix packages are created?

### ISSUE THREAD

**Issue by devgaia** [MicrosoftDocs/msix-docs#379]
Please clarify what options or manifest-properties that determines if an .appx or .msix package is created by MakeAppx.exe

We're creating UWP-apps for a Windows 10 IoT Core environment and they are installed by Azure IoT DM Client  (Device Management). The DM Client can only install .appx files but when we build with the latest Visual Studio we get .msix packages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36fa5c17-6f3f-d941-6148-65703136a94f
* Version Independent ID: c64136ad-cc7e-8cff-bf46-fb4d2c908149
* Content: [Create an app package with the MakeAppx.exe tool - MSIX](https://learn.microsoft.com/en-us/windows/msix/package/create-app-package-with-makeappx-tool)
* Content Source: [msix-src/package/create-app-package-with-makeappx-tool.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/package/create-app-package-with-makeappx-tool.md)
* Product: **windows**
* Technology: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by aniketbanerji** [comment]
@devgaia - All .appx/.msix get packaged using [Packaging APIs](https://learn.microsoft.com/en-us/windows/win32/appxpkg/interfaces). There is no means to distinguish if a package is packaged via MakeAppx or the packaging APIs just by looking at the manifest or the package, given that MakeAppx also uses the packaging APIs. Visual Studio and MSIX SDK also uses the same packaging APIs
