### ISSUE TITLE
Why is windows 10 enterprise used for hyperv quick create?

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/msix-docs#40]
The msix conversion template for HyperV quick create is based on Windows 10 enterprise.

This refuses the use of a personal Microsoft account.

Two questions:
- is there a reason for which you didn’t use Windows 10 professional as a basis (so that all Microsoft accounts could be used)?
- how difficult is it to create your own vm (template) for msix? Is there documentation for that?

**Comment by jvintzel** [comment]
Enterprise edition has a superset of features over Professional.  While it does not allow Microsoft Accounts it has things like App-V that Pro does not offer.  You can build you own template by installing the MSIX Packaging Tool and the related optional feature MSIX Packaging Tool Driver.
