### ISSUE TITLE
Windows 10 IoT Core support

### ISSUE THREAD

**Issue by rolfik** [MicrosoftDocs/msix-docs#42]
How does App Installer functionality works on Windows 10 IoT Core?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0414d22b-2b74-000f-9d7b-47f6dcb0e45e
* Version Independent ID: 0e72ec33-b8ad-af27-bcb9-16a45936e2a1
* Content: [Installing Windows 10 apps from a web page - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/installing-windows10-apps-web)
* Content Source: [msix-src/app-installer/installing-windows10-apps-web.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/installing-windows10-apps-web.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Hi @rolfik you can use App Installer via APIs on Windows 10 IoT Core.  More information about this here https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.addpackagebyappinstallerfileasync
