### ISSUE TITLE
What if everything is greyed out?

### ISSUE THREAD

**Issue by Fuchur84** [MicrosoftDocs/msix-docs#45]
I have a couple of cordova based apps in the microsoft store and it worked like described here before. But since a couple of weeks/month I can no longer select an entry in the "Store" menu other than "Open developer account" and "Open developer license" (translated from German). When I click on "Open developer account" I am redirected to the page "https://appdev.microsoft.com/StorePortals/de-de/account/signup/start". Firefox tells me, it is not secure and does not show anything but the error message (error code: NS_ERROR_NET_INADEQUATE_SECURITY)

If I click on "Open developer license" I am redirected to the settings of my computer "For developers". I am not sure what I need to do here. It is set to Developer mode of cause and I can activate aor deactivate the device portal or search fo a devise, but I can not see an option to open my license.

Everything else is grayed out. I had a look at my licence (clicking on the upper right icon in visual studio) and it seems to be fine. I refreshed it using the button anyway, but it did not change anything.

Any help what I am missing or what I can do to fix this? It was a very nice and smooth process before, but now I am pretty stuck and can not update my apps anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9757ffa-ccdb-e9f3-3f74-6f147dd04066
* Version Independent ID: 15b5e687-f04d-d893-81fe-8fc86b63fe2d
* Content: [Packaging UWP apps - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps#feedback)
* Content Source: [msix-src/package/packaging-uwp-apps.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/packaging-uwp-apps.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by Fuchur84** [comment]
Any help? I am pretty much stuck on this for weeks now and need some advise.

**Comment by dianmsft** [comment]
Hi @Fuchur84 are you still experiencing this issue?

**Comment by iamtesch** [comment]
FYI, I am also experiencing this issue.  Navigating to the page from the Visual Studio 2019 "Project>Publish" menu in Firefox (v72.0.2) gives this error.

Another example of page causing the problem:
https://appdev.microsoft.com/StorePortals/en-us/Developer/Catalog/ReleaseAnchor

**Comment by KevinLaMS** [comment]
I have had Visual Studio update the link.  Can you make sure this no longer happens.
Sorry for the delay.
