### ISSUE TITLE
This process is not sufficient when compared to earlier functionality in Visual Studio 2017

### ISSUE THREAD

**Issue by johanlindfors** [MicrosoftDocs/msix-docs#46]
In Visual Studio 2017 it was easy to create a test/temp-certificate for local signing for UWP apps which didn't required password or association with specific users (or actually access to a Windows Domain controller). 

For us building apps with CMake/MSbuild in CI environments the proposed process is not viable since there is no way to pass parameters such as SignTool password parameter through MSBuild.

How do you recommend we proceed?

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 8e95ba48-8d07-d390-d49b-801d70730bae
* Version Independent ID: 047d2736-f14e-610c-7396-89d2eae0f9cc
* Content: [Create a certificate for package signing - MSIX](https://docs.microsoft.com/sv-se/windows/msix/package/create-certificate-package-signing#feedback)
* Content Source: [msix-src/package/create-certificate-package-signing.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/create-certificate-package-signing.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by rconard** [comment]
@johanlindfors,

Thank you for this feedback. We realized quickly that this takeback affected our users, and we worked hard to create a better experience as a fix.

We have been tracking this issue in a thread on Developer Community:
https://developercommunity.visualstudio.com/comments/728237/view.html

I am pleased to let you know that our fix is live in recent releases:
https://developercommunity.visualstudio.com/solutions/744872/view.html
