### ISSUE TITLE
How to install an app from the Windows Store via the command line?

### ISSUE THREAD

**Issue by NatoBoram** [MicrosoftDocs/msix-docs#47]
[Enter feedback here]

This article is about sideloading apps. While it's cool and all, it's not very helpful for apps on the store.

I just want to make a script for my first time setup so I can have a bunch of apps easily accessible without having to click all over the place and wait huge delays just to install apps.

So, how do we install apps from the store via command line?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9757ffa-ccdb-e9f3-3f74-6f147dd04066
* Version Independent ID: 15b5e687-f04d-d893-81fe-8fc86b63fe2d
* Content: [Packaging UWP apps - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps#sideload-your-app-package)
* Content Source: [msix-src/package/packaging-uwp-apps.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/packaging-uwp-apps.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Hello, the ability to install apps from the store via the command line is currently not supported.

**Comment by tesar-tech** [comment]
> Hello, the ability to install apps from the store via the command line is currently not supported.

Any plans for future?

**Comment by jvintzel** [comment]
@tesar-tech Its an item in our backlog.  We do not have a specific date.

**Comment by NatoBoram** [comment]
Is there a publicly available issue tracker with this item so I can subscribe to it?
