### ISSUE TITLE
Support for multiple MSIs/EXEs?

### ISSUE THREAD

**Issue by tmccarthy9** [MicrosoftDocs/msix-docs#5]
On the page "[Creating an application package with MSI on a VM](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/create-app-package-msi-vm)", the manual steps to create a package with the GUI allow you to run multiple installers for prereqs:

- "If you need to run multiple installers you can do that manually at this point."
- "If the app needs other pre-reqs, you need to install them now."

These steps are completed before the MSIX is fully created. Does the XML template allow other MSIs or EXEs to be executed before the MSIX is generated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6faf60e-9fee-7a8d-21d3-a51162e4ea0b
* Version Independent ID: 18d98dc3-5e8e-3fe0-cb87-4d8b6f6ff419
* Content: [create package using command line interface - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/package-conversion-cli#)
* Content Source: [msix-src/packaging-tool/package-conversion-cli.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/package-conversion-cli.md)
* Product: **msix**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by pezan** [comment]
This is currently not supported but it is captured in the backlog. You can create a PowerShell script that runs all your MSIs or Setup.exes (or any copy operations) and pass the .ps1 file as your installer argument in the CLI template to workaround this.

**Comment by c-don** [comment]
@tmccarthy9 - please reopen if you would like to followup.
