### ISSUE TITLE
Why only selfsigned certificates

### ISSUE THREAD

**Issue by peterpantheking** [MicrosoftDocs/msix-docs#53]
This article is missing the instructions for pki certificates. please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e95ba48-8d07-d390-d49b-801d70730bae
* Version Independent ID: 047d2736-f14e-610c-7396-89d2eae0f9cc
* Content: [Create a certificate for package signing - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing)
* Content Source: [msix-src/package/create-certificate-package-signing.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/create-certificate-package-signing.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by naikrovek** [comment]
Check the Prerequisites section.  Your PKI administrator should know how to get you a code signing certificate that works.
