### ISSUE TITLE
Appinstaller URI with querystring

### ISSUE THREAD

**Issue by brads55** [MicrosoftDocs/msix-docs#55]
According to https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-appinstaller, the URI attribute (also the URI in the MainPackage element) say nothing about their format, only that they are a web URI. As such I would expect query strings with multiple key/value pairs to work, however they do not.

For example, an .appinstaller such as the following:

```
<?xml version="1.0" encoding="utf-8"?>
<AppInstaller Uri="https://example.com/App.appinstaller?key1=value&key2=value"
              Version="1.0.0.0" xmlns="http://schemas.microsoft.com/appx/appinstaller/2017/2">
    <MainPackage Name="App" Version="1.0.0.0" Publisher="CN=Somebody"
                 Uri="https://example.com/App.msix?key1=value&key2=value"
                 ProcessorArchitecture="x64" />

    <UpdateSettings>
        <OnLaunch HoursBetweenUpdateChecks="0" />
    </UpdateSettings>
</AppInstaller>
```

Results in an uninstallable package. Installing from the .appinstaller locally (an identical copy of the web hosted one), gives "The .appinstaller file is invalid.". And installing from the hosted version using a ms-appinstaller link gives "Failed to locate the app package because the URI is invalid."

Is this intentional? (In which case it should probably be noted somewhere), or is this a bug?

(My use case here is using a shared access signature from azure blob storage)

**Comment by dianmsft** [comment]
Hi @brads55 thank you for writing in. Query strings with multiple key/value pairs are currently not supported but I have put a feature request in our backlog to support it in the future. In addition, we will update the documentation to specify this.

**Comment by dianmsft** [comment]
Also feel free to add any ideas https://techcommunity.microsoft.com/t5/MSIX/idb-p/MSIXIdeas for any future feature request.

**Comment by gabrysgab** [comment]
It's closed as completed but i don't see this feature available in the latest version. What was the resolution for this?

**Comment by Aditya-Rajgor** [comment]
Any update on this?
