### ISSUE TITLE
Store Support: 1803 or 1809?

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/msix-docs#56]
The docs above state: 'Currently, MSIX installation through the Microsoft Store and Microsoft Store for Business require Windows 10 version 1809.' However, Partner Center supports uploads MSIX packages supporting MinVersion &gt;=1803. Should the docs be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95b83f04-01b6-c494-1e2a-dcddecaa7dc8
* Version Independent ID: 758db7a1-fd48-56fc-1e82-0fbd7ad3f7dc
* Content: [MSIX support on Windows 10 version 1709 and 1803 - MSIX](https://docs.microsoft.com/en-us/windows/msix/msix-1709-and-1803-support#feedback)
* Content Source: [msix-src/msix-1709-and-1803-support.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/msix-1709-and-1803-support.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
updated!
