### ISSUE TITLE
AppInstaller Update gets broken on CANCEL.

### ISSUE THREAD

**Issue by driesvandamme** [MicrosoftDocs/msix-docs#60]
Please have a look at the Stackoverflow post. Some microsoft guy already did, but it wasn't solved.

https://stackoverflow.com/questions/55651889/auto-updates-with-app-installer-stop-working-if-user-cancels-the-automatic-updat/58188533#58188533

**Comment by Huios** [comment]
@driesvandamme 

Canceling the in progress update probably broke some internal state in the update pipeline. I've filed an internal bug with our dev team to investigate this scenario. 

Tanaka MSFT

**Comment by Huios** [comment]
@driesvandamme 

A similar issue was fixed in Windows 1903 ( Build 18362). If you're using an earlier build, updating your OS to Build 18362 or greater may resolve the issue.

Tanaka MSFT

**Comment by driesvandamme** [comment]
@Huios - Thanks: We did indeed log a ticket with Microsoft to get it resolved. Seems it was indeed a bug, but was already resolved with a higher Windows 10 version. (My customer however isn't on a newer version yet. They just did an upgrade to 1809)
