### ISSUE TITLE
Package signing

### ISSUE THREAD

**Issue by gavinayling** [MicrosoftDocs/msix-docs#61]
I was directed to this page from https://docs.microsoft.com/en-us/windows/msix/package/sign-app-package-using-signtool in order to find information about signing an app, but there does not appear to be information about that here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bead27ac-8ed3-9886-26e2-47f49ea1efc0
* Version Independent ID: f354c6b6-b2e0-e070-dd0d-c3452a5635fb
* Content: [Package a desktop app from source code using Visual Studio - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net#feedback)
* Content Source: [msix-src/desktop/desktop-to-uwp-packaging-dot-net.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-packaging-dot-net.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Hi @gavinayling are you trying to sign your app using SignTool? or through Visual Studios?
