### ISSUE TITLE
Information our of date for HL2

### ISSUE THREAD

**Issue by ddaymn** [MicrosoftDocs/msix-docs#62]
Does not indicate proper arm information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d3ebc79-107e-4da3-a69e-2833e4b4891f
* Version Independent ID: bcb79b16-6786-3330-d3d6-052b8391a442
* Content: [App package architectures - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/device-architecture#feedback)
* Content Source: [msix-src/package/device-architecture.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/device-architecture.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by KevinLaMS** [comment]
Greetings, we updated our docs in February.  I think we have addressed.  Can you confirm your issues has adequately been addressed?

**Comment by ddaymn** [comment]
Yes it does thanks for following up.
