### ISSUE TITLE
cmd not working

### ISSUE THREAD

**Issue by fmExcense** [MicrosoftDocs/msix-docs#65]
The /m option is required when the [ResourceMetadata] is used in the MappingFile.txt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ac7b115-1e78-bb78-b461-c5d2739524ea
* Version Independent ID: 966a5c8e-f846-9448-9a31-e948733a3c2e
* Content: [Introduction to asset packages - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/asset-packages#feedback)
* Content Source: [msix-src/package/asset-packages.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/asset-packages.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by Huios** [comment]
Thanks for the catch @fmExcense 

![makeappx](https://user-images.githubusercontent.com/5958833/69273679-ac771100-0b8d-11ea-841f-e32c19ecfc29.PNG)
