### ISSUE TITLE
Application ID invalid characters?

### ISSUE THREAD

**Issue by toinevl** [MicrosoftDocs/msix-docs#7]
commandline conversion fails if Application ID includes a "-" character, maybe there are more?
 The error displayed is "Error reading the template file: Application ID is not valid"

**Comment by mcleanbyron** [comment]
Thanks for submitting this feedback. Can you please confirm whether your question is about the MSIX Packaging Tool and the [Create app package using Command Line](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/package-conversion-cli) article? We are investigating and will respond as soon as we can with more information.

**Comment by toinevl** [comment]
Hi, yes it is. Looking forward to your reply. Tnx, Toine

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by mcleanbyron** [comment]
The engineering team has confirmed that only alphanumeric characters and periods are allowed for the Application::ID. They have updated the article with the updated guidance. Thanks for your feedback!
