### ISSUE TITLE
Azure Devops issue

### ISSUE THREAD

**Issue by JanabiSoft** [MicrosoftDocs/msix-docs#71]
Azure pipelines does not support password protected certificates, so how can we create password-less certificate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e95ba48-8d07-d390-d49b-801d70730bae
* Version Independent ID: 047d2736-f14e-610c-7396-89d2eae0f9cc
* Content: [Create a certificate for package signing - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing#feedback)
* Content Source: [msix-src/package/create-certificate-package-signing.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/create-certificate-package-signing.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by Huios** [comment]
@JanabiSoft 

You can use this Code Signing Task to your release pipeline to sign your package with your password protected cert - https://marketplace.visualstudio.com/items?itemName=stefankert.codesigning

You can have a look at a sample that makes use of it here - https://github.com/microsoft/devops-for-windows-apps

Hope this helps.

Tanaka (MSFT)
