### ISSUE TITLE
Ensure that customer do not use this for core OPP and Office product deployment

### ISSUE THREAD

**Issue by Ramonin** [MicrosoftDocs/msix-docs#72]
We should make sure that we talk about whether we expect for customer to use this for core OPP and other office product deployments.  There is a great deal of confusion with our customer on this part can you get a clear statement in the article?  thank you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91be9c0-26f6-d263-099d-e58df9eee583
* Version Independent ID: 31f6e0f8-3951-9c04-f1c4-619a9c07a5fa
* Content: [What is MSIX? - MSIX](https://docs.microsoft.com/en-us/windows/msix/overview?source=docs)
* Content Source: [msix-src/overview.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/overview.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Hi @Ramonin, can you be more specific? Are you talking about the current Office ProPlus deployment?

**Comment by Ramonin** [comment]
We need a clear statement on if the expectation is that MSIX would be used to deploy OPP.
I don’t think that is the intent of MSIX but that should be made clear in the documentation.

Is it or is it not?

Ramon Infante
Principal Program Manager
M365 and Security Group

Microsoft
Office: +1 (425)538-0610
Mobile: 201-647-4962
ramonin@microsoft.com<mailto:ramonin@microsoft.com>

**Comment by dianmsft** [comment]
We are working with the Office team to provide the right experience and documentation on how to work with MSIX.
