### ISSUE TITLE
How to build and package a desktop bridge (Win32 + UWP) app in Azure DevOps for CI/CD?

### ISSUE THREAD

**Issue by dpaulino** [MicrosoftDocs/msix-docs#73]
I'm trying to figure out how to set up a CI/CD pipeline for my desktop bridge project, but I'm having trouble understanding the steps. I have tried setting a up a CI/CD pipeline using the regular UWP build tasks, but it does compile properly with a desktop bridge app (I'm getting errors saying "could not find recipe file for referenced UWP project"). 

Does anyone have a how-to article on setting up a CI/CD pipeline for a desktop bridge app? I want to build and package the desktop bridge app from source code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bead27ac-8ed3-9886-26e2-47f49ea1efc0
* Version Independent ID: f354c6b6-b2e0-e070-dd0d-c3452a5635fb
* Content: [Package a desktop app from source code using Visual Studio - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net)
* Content Source: [msix-src/desktop/desktop-to-uwp-packaging-dot-net.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-packaging-dot-net.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dpaulino** [comment]
I tried creating a yaml file, but it's failing. Here's the file: https://gist.github.com/dpaulino/2247ebb10f0bccadbdfb314bc0770957 

And here's the error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets(518,5): Error : Could not find a recipe file for the referenced UWP application at ''. Please build the project.`

Would be great to hear from someone at Microsoft about this asap!

**Comment by dpaulino** [comment]
Any recommendations?

**Comment by pducolin** [comment]
I think we have the same issue https://github.com/MicrosoftDocs/windows-uwp/issues/2090

**Comment by pducolin** [comment]
Here's Powershell commands I tried:

- msbuild .\Dashlane.sln  /t:Clean,Build /p:Configuration=Release /p:Platform=x86 /p:DefineConstants=PROD /p:AppxBundle=Never

- msbuild .\Dashlane.sln  /t:Clean,Build /p:Configuration=Release /p:Platform=x64 /p:DefineConstants=PROD /p:AppxBundle=Never

- msbuild .\Dashlane.sln  /t:Clean,Build /p:Configuration=Release /p:Platform=x64 /p:DefineConstants=PROD

**Comment by Huios** [comment]
@dpaulino 

We have a CI/CD pipeline sample for MSIX here - https://github.com/microsoft/devops-for-windows-apps

You can also have a look at the //Build talk walking through the sample here - https://mybuild.techcommunity.microsoft.com/sessions/77012

Hope this helps.

Tanaka (MSFT)

**Comment by pducolin** [comment]
Hi @Huios , thank you for your link. I could fix the issue by deploying and building only x64 solution, but on the CI I get few errors for `error APPX1101: Payload contains two or more files with the same destination path` from one UWP component project. The project is referenced by one of the two apps contained in the package project. Duplication seems due to the package project getting output from both referenced project output and contained app's output. This happens only on our CI - using Docker. Locally I can build from command line using msbuild

**Comment by tbolon** [comment]
@Huios This CI/CD pipeline sample should be highlighted in the doc, or listed as "Create a desktop app package from command-line".
