### ISSUE TITLE
Is it possible to publish an app that doesn't work in S mode to Microsoft Store?

### ISSUE THREAD

**Issue by xa0082249956** [MicrosoftDocs/msix-docs#76]
In this [document](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-test-windows-s):
> You can test your Windows app to ensure that it will operate correctly on devices that run Windows 10 in S mode.  In fact, if you plan to publish your app to the Microsoft Store, you must do this because it is a store requirement. 

However, we know that [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) is in Microsoft Store now, but it's [not supposed to](https://github.com/microsoft/terminal/issues/2624) run in S mode (actually it crashes in S). Then it shouldn't be able to publish to Microsoft Store according to the document.

So my question is:
- Is it possible to publish an app that doesn't work (even just crash) in S mode to Microsoft Store?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3568bdd0-9675-78f9-b340-42671ad59875
* Version Independent ID: 7a322546-df50-f804-e3ba-fb993f3b5efc
* Content: [Test your Windows app for Windows 10 S - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-test-windows-s#feedback)
* Content Source: [msix-src/desktop/desktop-to-uwp-test-windows-s.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-test-windows-s.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Thank you @xa0082249956 for writing about this. If your app is a true UWP app and does not include use of extensions (including desktop extensions) then it will run on Windows 10S.
