### ISSUE TITLE
Incorrect PowerShell snippet on package signing page

### ISSUE THREAD

**Issue by PDeets** [MicrosoftDocs/msix-docs#78]
On https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing, it shows this PowerShell snippet:

$pwd = ConvertTo-SecureString -String <Your Password> -Force -AsPlainText 
Export-PfxCertificate -cert "Cert:\CurrentUser\My\<Certificate Thumbprint>" -FilePath <FilePath>.pfx -Password $pwd

This doesn't work because $pwd expands to the current working directory. The variable needs to be named something else like $password.

Also, there should be an explanation about how to have Visual Studio be able to build using the PFX that is generated. I think that requires you to use the PackageCertificatePassword tag in a PropertyGroup and set it to the password used in the PowerShell here, but I'm not sure.

**Comment by dianmsft** [comment]
Hi @PDeets thank you for posting this issue. We are currently fixing the documentation issue to use $password instead of $pwd.

**Comment by dianmsft** [comment]
Changes are live now.
