### ISSUE TITLE
How do I include assets 

### ISSUE THREAD

**Issue by MrAntix** [MicrosoftDocs/msix-docs#79]
I have a console app which exposes an api using asp.net
there is a web app which is built to the www folder
I have a packaging project in the solution, how do I include the web app in my appx package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bead27ac-8ed3-9886-26e2-47f49ea1efc0
* Version Independent ID: f354c6b6-b2e0-e070-dd0d-c3452a5635fb
* Content: [Package a desktop app from source code using Visual Studio - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net)
* Content Source: [msix-src/desktop/desktop-to-uwp-packaging-dot-net.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-packaging-dot-net.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by Huios** [comment]
On the "Applications" node in the packaging project project you can right click and add one or more applications to the project. If you have more than one application you'll need to choose one as the entry point. You can also add a folder or files to the packaging project by right clicking on the project node.

Have a look at https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net
