### ISSUE TITLE
Instructions to Create package folder in VS will add to solution and not project

### ISSUE THREAD

**Issue by edwardskrod** [MicrosoftDocs/msix-docs#8]
"To create the folder in Visual Studio, right click on the root of the Solution Explorer, select Add -&gt; New Folder and name it packages. "

This will add the folder to the solution.  However, we want it added to the project.   This should read:
 "To create the folder in Visual Studio, right click on the project in the Solution Explorer, select Add -&gt; New Folder and name it packages. "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e2aa1ef-b0f5-912e-a012-6510a92d8861
* Version Independent ID: 8abd36f6-a781-07c3-4bf7-bfec7d4b7f88
* Content: [Install a Windows 10 app from an IIS server - MSIX](https://docs.microsoft.com/en-us//windows/msix/app-installer/web-install-iis)
* Content Source: [msix-src/app-installer/web-install-IIS.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/web-install-IIS.md)
* Product: **msix**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for providing your feedback. This issue has been fixed.
