### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by AhmadKelany** [MicrosoftDocs/msix-docs#80]
The Link for: Public Key Infrastructure Cmdlets. is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e95ba48-8d07-d390-d49b-801d70730bae
* Version Independent ID: 047d2736-f14e-610c-7396-89d2eae0f9cc
* Content: [Create a certificate for package signing - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing?source=docs)
* Content Source: [msix-src/package/create-certificate-package-signing.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/create-certificate-package-signing.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by baardhermansen** [comment]
@AhmadKelany Are you sure? I can't reproduce that error, the link is working correctly for me. Due to my settings are English US, i'm redirected to https://docs.microsoft.com/en-us/powershell/module/pkiclient/?view=win10-ps.
Could there be an issue with your redirect?

**Comment by AhmadKelany** [comment]
> @AhmadKelany Are you sure? I can't reproduce that error, the link is working correctly for me. Due to my settings are English US, i'm redirected to https://docs.microsoft.com/en-us/powershell/module/pkiclient/?view=win10-ps.
> Could there be an issue with your redirect?

It was fixed and closed 6 days ago..
