### ISSUE TITLE
Missing info on how to create a Store certificate

### ISSUE THREAD

**Issue by andrewleader** [MicrosoftDocs/msix-docs#81]
There's no documentation on how to create/obtain a Store certificate for signing the package to upload to the Windows Store.

Using VS to "Associate app with Store" no longer creates the Store cert on the machine. So there's no way for us to set up automated builds without a Store cert.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e95ba48-8d07-d390-d49b-801d70730bae
* Version Independent ID: 047d2736-f14e-610c-7396-89d2eae0f9cc
* Content: [Create a certificate for package signing - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing)
* Content Source: [msix-src/package/create-certificate-package-signing.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/create-certificate-package-signing.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by Huios** [comment]
The Store Cert isn't required to submit an app to the Store anymore so marking as closed.
