### ISSUE TITLE
.NET Core 3.1 

### ISSUE THREAD

**Issue by rkone** [MicrosoftDocs/msix-docs#82]
There seems to be issues creating a package for .NET Core 3.1 apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bead27ac-8ed3-9886-26e2-47f49ea1efc0
* Version Independent ID: f354c6b6-b2e0-e070-dd0d-c3452a5635fb
* Content: [Package a desktop app from source code using Visual Studio - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net#feedback)
* Content Source: [msix-src/desktop/desktop-to-uwp-packaging-dot-net.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-packaging-dot-net.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
@rkone can you be more specific about the type of issue you are seeing?

**Comment by rkone** [comment]
Sorry, it's working for me now.

**Comment by dianmsft** [comment]
Excellent!
