### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by nfarrell** [MicrosoftDocs/msix-docs#83]
https://github.com/Microsoft/msix-packaging/tree/master/preview/MsixCore should actually be:

https://github.com/Microsoft/msix-packaging/tree/master/MsixCore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37eced72-23b9-9555-6388-38b996277863
* Version Independent ID: 2d144a55-69a9-b4fe-8891-78a2f72b20d8
* Content: [MSIX Core - MSIX](https://docs.microsoft.com/en-us/windows/msix/msix-sdk/msixcore)
* Content Source: [msix-src/msix-sdk/msixcore.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/msix-sdk/msixcore.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
The broken links are now fixed.
