### ISSUE TITLE
Assigned Access Mode not support  MSIX  package

### ISSUE THREAD

**Issue by Cirnohalo** [MicrosoftDocs/msix-docs#84]
[Enter feedback here]
I've tried to convert Win32 MSI to MSIX, and install it in the local account, then I can't set up a single-app kiosk for this APP(can't find in set-up step). I set up Assigned Access Mode for this APP by MDM. When logs in, Windows attempts to run the application (the blue window appears with the loading spinner). The whole screen flickers for a minute or so and then an error message appears stating:

"We weren't able to start your app. Press Ctrl + Alt + Del to sign out or contact your system admin. For more info, search online for error code: 0x80270254".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6411665a-440a-ff7c-046f-20f95b023e95
* Version Independent ID: 59530df8-e40f-e016-eac8-266ce7c43b35
* Content: [Package an application manually (Desktop Bridge) - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-manual-conversion)
* Content Source: [msix-src/desktop/desktop-to-uwp-manual-conversion.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-manual-conversion.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
The error indicates that the app is not registered or installed. For single-app kiosk have you looked at this article https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app ? 

If you can can you please file feedback so we can take a look? Please write back with the name of feedback so we can find it.

**Comment by dianmsft** [comment]
Let us know if the issue still persist. Closing issue for right now.
