### ISSUE TITLE
Make clear how this relates to dotnet core "PublishReadyToRun" and .NET Native

### ISSUE THREAD

**Issue by Marv51** [MicrosoftDocs/msix-docs#86]
Is the NativeImageCompiler still supported? How does it relate to dotnet core "PublishReadyToRun" and .NET Native?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29cc075e-0893-456e-e0cb-cdb5d6fc6b7e
* Version Independent ID: d32e10c2-a9e8-6d8b-53f7-74f554750f5a
* Content: [Optimize your .NET Desktop apps with native images - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-r2r)
* Content Source: [msix-src/desktop/desktop-to-uwp-r2r.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-r2r.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by Marv51** [comment]
Any progress on this?

**Comment by 3wavellc** [comment]
The whole .NET “Native Code Generation” is becoming a bottomless rabbit hole.

Is NativeImageCompiler simply “NGEN” rebranded? How is this different from “brittle” ngen native compilation?

https://docs.microsoft.com/en-us/dotnet/framework/net-native/net-native-and-compilation

“... If no native image is available for a particular method, NGEN falls back to JITing code. This means that native images must continue to include metadata and IL in the event that NGEN needs to fall back to JIT compilation...“

“... NGEN images tend to be fragile. For example, a patch or change to a dependency typically requires that the assemblies that use it also be re-NGENed...”

**Comment by swaroop-sridhar** [comment]
[NativeImageCompile](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-r2r) and [PublishReadyToRun](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#readytorun-images) are pretty much the same technology. The former is for .net framework/msix, and the later is applicable to .net core apps.

NativeImageCompiler is a package that contains:
• Crossgen compiler for .net framework
• Specially built framekwork reference-assemblies that crossgen can use for native-compilation of desktop apps.

Crossgen was concurrently developed for .net framework and .net core until a couple of years ago, so it’s the same technology. However, subsequent development and improvements are only done for .net core (now re-branded as .net 5).

**Comment by KevinLaMS** [comment]
Thanks Swaroop.  
@3wavellc  @Marv51  Does that suffice?

**Comment by 3wavellc** [comment]
Yes.

Thank you

Pete

Pete Shramko
3rd Wave, llc
2800 Post Oak Blvd Suite 4100
Houston, TX 77056

pshramko@iiiwave.com
954-646-5011
________________________________
