### ISSUE TITLE
Configuration of MIME types in .Net Core ASP web site

### ISSUE THREAD

**Issue by marosklempa** [MicrosoftDocs/msix-docs#87]
Step 7 is not working on newest Microsoft web technology .Net Core. Web site build using .Net Core ASP ignore web.config static content mimeMap. Thus if you click on link described in step 9, installation will not work because web server will return 404 status (non existent file).
To proper configuration of .Net Core web site which will host your MSIX installation you need modify Configure method in Startup.cs file.
Instead of app.UseStaticFile() you have to use
var provider = new FileExtensionContentTypeProvider();
provider.Mappings.Add(".appx", "application/appx");
provider.Mappings.Add(".msix", "application/msix");
provider.Mappings.Add(".appxbundle", "application/appxbundle");
provider.Mappings.Add(".msixbundle", "application/msixbundle");
provider.Mappings.Add(".appinstaller", "application/appinstaller");
app.UseStaticFiles(new StaticFileOptions
{
    ContentTypeProvider = provider
});
Also step 8 is obsolete on .Net Core ASP web site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e2aa1ef-b0f5-912e-a012-6510a92d8861
* Version Independent ID: 8abd36f6-a781-07c3-4bf7-bfec7d4b7f88
* Content: [Distribute a Windows 10 app from an IIS server - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/web-install-iis#feedback)
* Content Source: [msix-src/app-installer/web-install-IIS.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/web-install-IIS.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by kmiller77** [comment]
This just took me hours to figure out. If I hadn't seen this at the very bottom in a tiny spot of the MS doc "Distribute a Windows 10 app from an IIS server", I probably never would have figured it out, the docs definitely need updated!

Thank you @marosklempa !!!

**Comment by dianmsft** [comment]
Documentation should have been updated by now. Please reopen this is still an issue.
