### ISSUE TITLE
Associate App with the Store description needs more detail

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/msix-docs#90]
The brief description given only accounts for the most trivial case and is not sufficient in general or as an aid for issue resolution.
It is worth mentioning that to associate a project with the Store an account with owner permission must be used. The error message given by the wizard "An unexpected network has occured. The app list cannot be refreshed." is too cryptic to be of help.
In a real world scenario, a developer|programmer dealing with a project is unlikely to also be an owner of the dashboard, so an alternative way to obtain StoreKey.pfx and Package.StoreAssociation.xml needs to also be described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9757ffa-ccdb-e9f3-3f74-6f147dd04066
* Version Independent ID: 15b5e687-f04d-d893-81fe-8fc86b63fe2d
* Content: [Packaging MSIX apps - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps)
* Content Source: [msix-src/package/packaging-uwp-apps.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/packaging-uwp-apps.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Hi @avakhrushev can you please file the issue through [Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) The team can help you with your issue there.

**Comment by avakhrushev** [comment]
Hi @dianmsft 
Aren't you guys way too eager to push off work on to someone elses shoulders? This is by large a documentation issue. The cryptic VS message is only one of several points there.

**Comment by dianmsft** [comment]
Hi @avakhrushev I'm working with the VS team on this and they are aware of the issue that you posted. They suggested that this issue is posted on their page and than we can link to it on ours.

**Comment by avakhrushev** [comment]
I guess I could report this to VS support as well, it didn't occur to me that they might not have this reported. As far as I can tell, the "network error" happens to people since at least 2016, and seeing how it isn't any less cryptic in recent Studio this very well might be the intended behavior. Just as you say, they should be already aware of this.
What would their page be, so I could maybe try and look up an existing report for you?
I should probably also make it clear that I'm not looking for support. This is a feedback on experience with the documentation, that is supposed to help make it more complete.
