### ISSUE TITLE
Publish app to Microsoft Store from Windows App Cert Kit

### ISSUE THREAD

**Issue by chrisevans9629** [MicrosoftDocs/msix-docs#91]
Windows app certification failed due to the app already being installed my device.  I uninstalled and would like to run the cert tests again and push it to the Microsoft store, but I see no option to do this.  Is there a way to publish the app bundle to the app store or do I have to rebuild the app all over again?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9757ffa-ccdb-e9f3-3f74-6f147dd04066
* Version Independent ID: 15b5e687-f04d-d893-81fe-8fc86b63fe2d
* Content: [Packaging MSIX apps - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps#automate-store-submissions)
* Content Source: [msix-src/package/packaging-uwp-apps.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/packaging-uwp-apps.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by KevinLaMS** [comment]
Hey Chris.
Sorry for the delay.  You should be able to publish to the store by logging in and going to the partner center.
https://partner.microsoft.com/en-us/dashboard/windows/overview
You will be able to upload your app bundle.
