### ISSUE TITLE
Founder of Buy Listers LLC

### ISSUE THREAD

**Issue by listerharrell1** [MicrosoftDocs/msix-docs#92]
I have been trying to improve my computer skills by being a member of Windows Insiders and I have a lifetime of experience in sales, where I started my first business at 14 and have been fortunate enough to have been my own boss my entire life .
I believe in my abilities in seeing opportunities others miss, as my computer knowledge evolves I believe I can find markets overlooked by traditional big box stores .

I want to thank Dell, Microsoft, and you Insiders for giving me awesome service for 25 years.
Sincerely, Lister Harrell,

**Comment by dianmsft** [comment]
Hello! Thank you for the kind words. We are glad that you have had a wonderful experience with us.
