### ISSUE TITLE
Great videos on MSIX. 

### ISSUE THREAD

**Issue by Abhilash3107** [MicrosoftDocs/msix-docs#93]
Informative walkthrough on MSIX. Would love to know more about the improvements of MSIX on VDI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 915f8c22-43ba-79bd-140a-09665fdc6dbb
* Version Independent ID: 8148245b-80c1-7062-ace3-44c61c03eff7
* Content: [MSIX videos - MSIX](https://docs.microsoft.com/en-us/windows/msix/team-video#feedback)
* Content Source: [msix-src/team-video.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/team-video.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by Huios** [comment]
We've added an MSIX App Attach video to the page. Have a look at:

https://www.youtube.com/watch?v=6kkPLFgPaN8
and 
https://www.youtube.com/watch?v=QLDu6QVohEI
