### ISSUE TITLE
Cannot build new .Net Core 3.1 app (using Application Packaging Project in VS) as "Any CPU"  

### ISSUE THREAD

**Issue by micampbell** [MicrosoftDocs/msix-docs#95]
I'm following the instructions at https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net including the cut-&-paste section, but I get the following error:

> Error	MSB3779	The processor architecture of the project being built "Any CPU" is not supported by the referenced SDK "Microsoft.VCLibs, Version=14.0". Please consider changing the targeted processor architecture of your project (in Visual Studio this can be done through the Configuration Manager) to one of the architectures supported by the SDK: "x86, x64, ARM, ARM64".	medemaPartAnalyzer ApplicationPackaging	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	

I don't believe that any of my nuget packages would prevent this. Is there something else to check?

**Comment by Huios** [comment]
Hi @micampbell 

It sounds like your project is referencing the Microsoft.VCLibs library which doesn't support AnyCPU. You'll have to specify either x86 or x64 as your project build architecture. For that you need to make sure you have the appropriate configurations set up if you want to build x86/x64 for your .NET core application in the configuration manager.

Tanaka (MSFT)

**Comment by micampbell** [comment]
Thank you, I believe that may be right. But I will not be able to test as we've gone a different route now.
