### ISSUE TITLE
Can I sign UWP apps with a Code Signing Certificate?

### ISSUE THREAD

**Issue by encrypt0r** [MicrosoftDocs/msix-docs#96]
Do I need an "EV Code Signing Certificate" or a normal "Code Signing Certificate" would do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76957695-dd9c-1158-f1f0-7e02e48d3903
* Version Independent ID: 44e2e900-9809-2895-3bdd-b549cc451ea1
* Content: [Sign an app package using SignTool - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/sign-app-package-using-signtool)
* Content Source: [msix-src/package/sign-app-package-using-signtool.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/sign-app-package-using-signtool.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by jvintzel** [comment]
It can be either.

**Comment by encrypt0r** [comment]
@jvintzel Thank you
