### ISSUE TITLE
what about error 0x80070032?

### ISSUE THREAD

**Issue by mattMedemaLabs** [MicrosoftDocs/msix-docs#97]
I've been trying to follow this so that I can sign my MSIX without needing the Store or a third party CA. I'm just trying to get a MSIX to beta testers. If Device Guard the proper approach for this? Also, it took me a while, but I think you're missing a line in the PowerShell script above ('client_secret' = '...').

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93165f41-8dfc-0316-f37a-1df2e8a8fd8c
* Version Independent ID: b15947b8-83fe-7bd8-1d76-ebd040c28258
* Content: [Sign an MSIX package with Device Guard signing - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/signing-package-device-guard-signing)
* Content Source: [msix-src/package/signing-package-device-guard-signing.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/signing-package-device-guard-signing.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Thanks for the feedback. We made a change to include the client secret to the example.
